### ISSUE TITLE
Out of memory error when requiring mercure

### ISSUE THREAD

**Issue by kirannuclear** [dunglas/mercure#101]
I tried to install mercure using composer. I get this error:

$  composer require symfony/mercure
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

Warning: Module 'openssl' already loaded in Unknown on line 0
Using version ^0.1.0 for symfony/mercure
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

VirtualAlloc() failed: [0x00000008] Not enough memory resources are available to process this command.

VirtualFree() failed: [0x000001e7] Attempt to access invalid address.

VirtualAlloc() failed: [0x00000008] Not enough memory resources are available to process this command.

VirtualFree() failed: [0x000001e7] Attempt to access invalid address.

PHP Fatal error:  Out of memory (allocated 1570766848) (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Out of memory (allocated 1570766848) (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

**Comment by dunglas** [comment]
Hi, thanks for reporting. This error doesn't looks related to Mercure. You haven't enough RAM on your computer to allow Composer to solve the dependencies.

If increasing the memory doesn't help, feel free to reopen on Composer bug tracker.

**Comment by varungowda24** [comment]
@dunglas how much RAM Space required for this

**Comment by kirannuclear** [comment]
@dunglas setting the memory to -1 worked. i had 128M before. What is the minimum value I should set?

**Comment by Spomky** [comment]
I have the same issue with a memory limit set to 2G.
I agree that this is not directly related to the package, but the error may be caused be the dependency tree of Mercure.
Investigation should be performed.

**Comment by kirannuclear** [comment]
@dunglas hey.. can you please tell me if this will work with pwa and push notification. I think the connection needs to persist for server to send event. if i use this can i send a pwa push notification?
