### ISSUE TITLE
 401 Unauthorized in symfony 4 at publish

### ISSUE THREAD

**Issue by thehatami** [dunglas/mercure#103]
install symfony 4 + mercure in windows 10 and many hours try pass the  401 Unauthorized.

i read all question about 401 but can not solve my problem.

i set environment variables in control panel like this.
```
ADDR: 127.0.0.1:3000
ALLOW_ANONYMOUS: 1
CORS_ALLOWED_ORIGINS: http://127.0.0.1:3000
JWT_KEY: aVerySecretKey
PUBLISHER_JWT_KEY: aVerySecretKey
SUBSCRIBER_JWT_KEY: aVerySecretKey
```
and run 
```
c:\mercure> mercure.exe
```

here is my symfony .env:
```
###> symfony/mercure-bundle ###
MERCURE_PUBLISH_URL=http://127.0.0.1:3000/hub
MERCURE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
###< symfony/mercure-bundle ###
```

my js connection worked!

but in update i got 
```
Unable to publish the update to the Mercure hub: file_get_contents(http://127.0.0.1:3000/hub): failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized
```

here is my controller
```
/**
     * @Route("/test/publish")
     * @param Publisher $publisher
     * @return Response
     */
    public function testpublish(Publisher $publisher): Response
    {
        $update = new Update(
            'foo',
            json_encode(['status' => 'done'])
        );

        $publisher($update);
    }
```

whats my wrong?

**Comment by sidikhalifa** [comment]
hello,
 first why you have?
```
JWT_KEY: aVerySecretKey
PUBLISHER_JWT_KEY: aVerySecretKey
SUBSCRIBER_JWT_KEY: aVerySecretKey
```
you can either _JWT_KEY_ **or** _PUBLISHER_JWT_KEY_ and _SUBSCRIBER_JWT_KEY_

i can see your `services.yaml` and mercure.yaml configuration?

You can see configuration a small project i create to test `mercureBundle` https://github.com/short-edition/tuto

**Comment by sidikhalifa** [comment]
If you understand French, you can see a very good tutorial on MercureBundle [Here](https://www.youtube.com/watch?v=pV4jXfDECjU)

**Comment by thehatami** [comment]
thx @sidikhalifa. that exactly i want.
