### ISSUE TITLE
Max input value for data

### ISSUE THREAD

**Issue by JSmythSSG** [dunglas/mercure#104]
Is there a limit on the amount of characters that can be received?

The post data is being sent correctly yet when the message come back from the hub it is missing half the data?

Originally I thought it was my server limiting the post chars so I upped  max_input_vars to 8000 in my php.ini and that worked however the mercure data JSON isnt the full character count

**Comment by football2801** [comment]
It does not appear so. I just sent 14,321 characters without any issue and without making any special changes to my php.ini file.

**Comment by JSmythSSG** [comment]
So it turns out that after using JSON.Stringify I also had to encodeURIComponent(msgJSON) before sending the xhttp request in Javascript since it was being sent as application/x-www-form-urlencoded.

Happy to say its working and I got my webRTC video chat making calls using Mecure to send the offer,answer and ice candidates :)
