### ISSUE TITLE
Client cant connect to HTTPS

### ISSUE THREAD

**Issue by thehatami** [dunglas/mercure#108]
i can connect to mercure with url as `http://www.testme.com:9753` from browser.

but clients get error from script
`
Mixed Content: The page at 'http://www.testme.com/en/box' was loaded over HTTPS, but requested an insecure EventSource endpoint 'http://www.testme.com:9753/hub?topic=ping%3Fuser%3D4'. This request has been blocked; the content must be served over HTTPS.
`

my nginx configuration

```
server {
    listen [::]:443 ssl; #managed by Certbot
    listen 443 ssl http2; #managed by Certbot

    listen 80;

    index index.php;
    client_max_body_size 100m;

    server_name testme.com www.testme.com;
    root /var/www/html/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?:ht|git|svn) {
        deny all;
    }

    location ~* ^.+\.(css|js|min.css) {
       access_log off;
       log_not_found off;
    }

    ssl_certificate /etc/letsencrypt/live/testme.com/fullchain.pem; #managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/testme.com/privkey.pem; #managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; #managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; #managed by Certbot

    access_log /var/log/nginx/rocket_access.log;
    error_log /var/log/nginx/rocket_error.log;
}

server {
    listen 80;
    listen [::]:80;

    return 301 https://testme.com$request_uri;

    server_name testme.com www.testme.com;
    return 404; #managed by Certbot
}

server {
    listen 9753 ssl http2;
    listen [::]:9753 ssl http2;

    ssl_certificate /etc/letsencrypt/live/testme.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/testme.com/privkey.pem;

    location / {
        proxy_pass http://localhost:8080/hub;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
```

whats my wrong?

**Comment by dunglas** [comment]
The error message is explicit: if the main page is served using HTTPS, the hub must be exposed using HTTPS or the browser will block the connection.

**Comment by thehatami** [comment]
ok. but how. i try to use HTTPS protocol as described in readme.md.
```
 sudo JWT_KEY='aVerySecretKey' ACME_CERT_DIR='/etc/letsencrypt/live/tesetme.com' ACME_HOSTS='tesetme.com' ADDR=':8080' ./mercure
```

but i get these error
```
http: TLS handshake error from 46.209.6.72:60789: acme/autocert: unable to authorize "tesetme.com"; challenge "tls-alpn-01" failed with error: acme: authorization error for tesetme.com: 403 urn:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge; challenge "http-01" failed with error: acme: authorization error for tesetme.com: 403 urn:acme:error:unauthorized: Invalid response
```

**Comment by dunglas** [comment]
Can you show the code you use in the browser?

**Comment by guycalledseven** [comment]
@dunglas I have similar scenario which maybe could help here. I have front (haproxy) and back app servers setup (mercure). 

I managed to get mercure work properly with haproxy, but only when I ssl terminated **only** on haproxy and had connection to mercure via http on 80.

When I used tcp passthrough (did not do ssl terminate on haproxy) but instead used my ssl certificates in mercure, I got wrong client IP adderess issue which I could't handle. AFAIK `X-Forwarded-For`/`X-Real-IP` cannot be forwarded in that way properly, so mercure was only seeing my haproxy ip and not ever a client ip. This then caused all sort of issues with clients.

@thehatami in your case that would mean that you only ssl terminate on nginx and do a port 80 proxy connection to mercure, as on example config in readme.md.

@dunglas If this is correct behaviour, maybe write this down as well in readme if you agree?

**Comment by dunglas** [comment]
Also, if you use Let’s Encrypt, you must use the default port (not 8080). Can you try to remove the ADDR env var?
We must update the readme to make that clearer.

**Comment by tpharaoh** [comment]
> Also, if you use Let’s Encrypt, you must use the default port (not 8080). Can you try to remove the ADDR env var?
> We must update the readme to make that clearer.

I had a similar question, that @dunglas solves it for me with this answer
