### ISSUE TITLE
How to authenticate subscriber from mobile (React Native)?

### ISSUE THREAD

**Issue by ramrami** [dunglas/mercure#112]
The EventSource is working fine from React Native when I'm using `ALLOW_ANONYMOUS=1`, but for `ALLOW_ANONYMOUS=0` I don't know how to send the JWT token. 
Is there a possibility to send it in the query string ?

**Comment by dunglas** [comment]
You can store the JWT in a cookie named `mercureAuthorization` or pass it in an `Authorization` header (`Authorization: Bearer <JWT>`).

The polyfill supports both.

**Comment by ramrami** [comment]
But the polyfill uses xhr, it's not really performant, isn't it? That's why I'm asking about the possibility to send the token in the query string over Https ?

**Comment by dunglas** [comment]
The polyfill only use a timer on very old browsers, on newer browsers it receives pushes.
