### ISSUE TITLE
mercure.error.log : Client IP wrong

### ISSUE THREAD

**Issue by Pyrrah** [dunglas/mercure#114]
Hello,

I am using Mercury behind a nginx proxy with the following configuration:
    location / {
        proxy_pass http://127.0.0.1:xxxx;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

Unfortunaly, in the logs file "mercure.error.log", the specified IP address is incorrect: client IP is always 127.0.0.1 :(

I tried to add parameters "proxy_set_header", but no success :
    proxy_set_header Host $ host;
    proxy_set_header X-Real-IP $ remote_addr;
    proxy_set_header X-Forwarded-For $ proxy_add_x_forwarded_for;

Can you fix the problem to have the real IP addresses?
Merci par avance Kévin :)

**Comment by dunglas** [comment]
`Forwarded` and `X-Forwarded-For` headers aren't currently supported. It would be a nice addition.
To do so, I suggest to introduce a new environment variable to trust some headers, and then register Gorilla's ProxyHeaders handler: https://github.com/gorilla/handlers

The configuration can be similar to Symfony's one: https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

**Comment by Pyrrah** [comment]
Great idea, I'm interested!

**Comment by dunglas** [comment]
Would you be interested on working on a patch? I can assist you if needed!

**Comment by Pyrrah** [comment]
Honestly, I have never worked with Golang and I have never created a patch. We can always try, with some help, and see :)

**Comment by dunglas** [comment]
I’m working on it.

**Comment by Pyrrah** [comment]
Thanks for the feedback. Maybe for next time (ça me laissera du temps pour jeter un œil sur Golang)

**Comment by dunglas** [comment]
@Pyrrah could you try if https://github.com/dunglas/mercure/pull/120 does the job?

**Comment by Pyrrah** [comment]
It's ok for me. I have good datas with IPv4 and IPv6 in the logs.

I pushed a pull request to update the README with good nginx parameters to use argument USE_FORWARDED_HEADERS=1.

Thank you Kevin for the work !
