### ISSUE TITLE
Can't create certificate

### ISSUE THREAD

**Issue by MarioZ2002** [dunglas/mercure#116]
Hello.

I'm struggling to make it run in production mode. 

When i run the docker image on Ubuntu 18.04 like:
```
docker run \
    -e JWT_KEY='myJWTKey' -e ACME_HOSTS='mydomain.com' \
    -p 80:80 -p 443:443 \
    dunglas/mercure
```

it gives me the following logs:
```
 2019/07/12 12:04:35 http: TLS handshake error from 2.203.251.78:62646: Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority
 2019/07/12 12:04:35 http: TLS handshake error from 2.203.251.78:62648: acme/autocert: missing certificate
```

It works fine with http.
Somehow it is not able to obtain a certificate.

Does anyone has an idea what the cause might be?

**Comment by dunglas** [comment]
Are you using some kind of proxy servers, a hotel wifi or something like that? It looks like there is some kind of network issue between the hub and Let's Encrypt's servers.

**Comment by MarioZ2002** [comment]
i managed to get it working by using the binary. Maybe it was something weird with Ovh.com VPS.
