### ISSUE TITLE
Where do you modify the JWT_KEY and with what?

### ISSUE THREAD

**Issue by dchorel** [dunglas/mercure#118]
I am having trouble finding wich JWT_KEY I have to change. Do I have to make an .env.local or do I change the one in .env? Do I change the one in the .bat? (I created a .bat to launch the server since I'm on Windows 10.) 

I'd also like to know how I generate a key for the JWT_KEY.

I tried different things but I always get an error on the web page:
The provided JWT is not valid.

**Comment by dunglas** [comment]
Hi:

* in the `.bat`, pass the **secret** used to sign the JWT (not the JWT itself). It's a bad practice to hardcode the secret, use an environment variable instead for instance.
* Then you should use the JWT (signed with this secret key) in `.env.local` (that will not be versioned in Git). `.env` should only contain a safe example value

> I'd also like to know how I generate a key for the JWT_KEY.

It's any random string. It's like a password. Try this tool to generate (and sign) a valid JWT: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJmb28iLCJiYXIiXSwicHVibGlzaCI6WyJmb28iXX19.LRLvirgONK13JgacQ_VbcjySbVhkSmHy3IznH3tA9PM
