### ISSUE TITLE
Pushing with API updates. How does it work?

### ISSUE THREAD

**Issue by dchorel** [dunglas/mercure#122]
I've been trying to understand how it works here: [https://api-platform.com/docs/core/mercure/ ](url)
but I don't understand a couple of things. 

1. Do I have to get the updates in the controller/template or does it update the entity by itself? 

2. What do I need to do in the other classes (Template/Controller) to display the data getting updated? (I can already display it but I have to refresh to see it.)

3. Do I have to subscribe the template to the DB? If so, how?

Sorry for multiple questions, but thank you in advance for your answers!

**Comment by dunglas** [comment]
Sorry but I don't understand the question. Can you add a bit more context? There are no concepts of templates nor of controller in API Platform (and still less in Mercure).

**Comment by dchorel** [comment]
Yes, sorry. I'm using Symfony 4. The templates is where we design and display the website pages and the controllers helps with that.

**Comment by dchorel** [comment]
I'll try using other words.
How I understand Mercure works is that someone will send an update by clicking a button or sending texts. Then the update is caught by the publisher wich sends the data to the view. Although, I don't know how to catch the update if the update occurs in the database. 
So I was wondering if the API was catching the updates and updating the entities automatically. If it updates everything, does it send any updates to the Hub? 
Do we catch the updates the same way as we do without an API? 
Furthermore, I have not been able to see my data update in real-time on the web page. Do I have to do the update when onmessage is called with the eventSource or will the API do magic? 
I hope it's more clear. Thank you.

**Comment by dchorel** [comment]
What I really want to know is... Is it possible to see data change without doing any action on the web page? No button press or message sent. Just data coming from the database and getting displayed.

**Comment by BallisticPain** [comment]
@dchorel ... I believe I understand what you are asking. I will attempt to answer.

Context: You are using a standard MVC setup using the Symfony framework with Doctrine ORM connected to MySQL for your database.
You have Models that facilitate communication to the database.
You have Controllers that handle incoming web requests and respond with a View (likely written in Twig).

You are wanting the View that has been already sent to the browser to receive notification and update itself based on a change in the database and you're asking if Mercure can do this?

I believe the short answer is yes, that is what it is designed to do. However, I don't believe there is any "magic" that does this for you. The API-Platform component and Mercure component work well together with the Symfony framework, however, it would be up to your View (JavaScript) to be subscribed to the necessary topics (events) to be updated without needing to refresh the browser. The browser refresh just calls back into the Controller and retrieves the latest data. If you had a subscription on the View to the Mercure hub, the View could update itself (using JavaScript), and would not require a refresh of the page in the browser.

Does this answer your question? I know I didn't give you the "how to", but I believe you can likely pursue and accomplish that knowing that it is possible and part of what Mercure was designed to do.

I hope this helps!
