### ISSUE TITLE
[Question] Best practices

### ISSUE THREAD

**Issue by marcio199226** [dunglas/mercure#123]
Hi i have a question by design how I should handle messages of different type?
An example once user was signed in my app i would like to listen to some real time events, those events usually are dispatched like this:
`$publisher(new Update('page_url', json_encode(['data' => 'test'])))`
`$publisher(new Update('page_url_2', json_encode(['data' => 'test'])))`
`$publisher(new Update('global', json_encode(['data' => 'test'])))`
And so on....

Each page on my front-end should listen only for events which interest it + some globals events.

In your opinion its better to create multiple EventSource object or create only one and then filter events to subscribers (in terms of rxjs of fe)?

**Comment by dunglas** [comment]
The best solution is to use a format supporting advanced typing. For instance, the JSON-LD format contains a `@type` key that you can use to add type information to the JSON document (XML also natively supports typing).

In your case, it could be something like:

```
 $publisher(new Update('page_url', json_encode(['@type' => 'https://mynamespace.com/type1', 'foo' => 'bar'])))
$publisher(new Update('page_url_2', json_encode(['@type' => 'https://mynamespace.com/type2', 'foo' => 'baz'])))
$publisher(new Update('global', json_encode(['@type' => 'https://mynamespace.com/type3', 'foo' => 'global'])))
```

Then, client-side, you can discard (or store to use later) the events having a type you aren't interested in.

**Comment by marcio199226** [comment]
Ok I had thought about doing the same way, are there any pros/cons of setting "type" into message data instead of message itself ? I mean this https://github.com/symfony/mercure/blob/master/src/Update.php#L38

**Comment by dunglas** [comment]
It depends of the use case:

* The `type` field of the Server-Sent Event is a technical type. Client-side, you'll have to register a different listener per type (using `addEventListener()`) if you use this one.
* The `@type` key of JSON-LD represents a domain (like in types in OOP languages), and it is transport-agnostic.

For instance, SSE's `type` will be `update`, `deletion`, `finished` or something like that. JSON-LD's type will be `http://example.com/book`, `http://example.com/review`,  `http://example.com/user` or something like that, and will still be available when you'll store the data in memory, in the local storage etc.

**Comment by marcio199226** [comment]
Ok thanks, can you explain me what's the difference between the **topics** and **targets** parameters of [update](https://github.com/symfony/mercure/blob/master/src/Update.php#L38) ?

**Comment by zorn-v** [comment]
@dunglas 
By the way - publisher as invocable is bad idea, I think
```php
$this->publisher($update)
```
gives an error, you should use ugly
```php
($this->publisher)($update)
```
Why you so love invocable classes ?

**Comment by dunglas** [comment]
Invokable class are used in many places in Symfony (Messenger handlers, forms, controllers...).

**Comment by AlexBergal** [comment]
> @dunglas
> By the way - publisher as invocable is bad idea, I think
> ```
> $this->publisher($update)
> ```
> gives an error, you should use ugly
> ```
> ($this->publisher)($update)
> ```
You can use this
`$this->publisher->__invoke($update);`
