### ISSUE TITLE
Publisher with update as a parameter returns an error.

### ISSUE THREAD

**Issue by dchorel** [dunglas/mercure#125]
I get this error: 

> Argument 1 passed to Symfony\Component\Mercure\Publisher::validateJwt() must be of the type string, object given, called in Path\to\publisher\vendor\symfony\mercure\src\Publisher.php on line 57

when calling this method:

    public function getUpdate(Publisher $publisher){
        $update = new Update("http://mysite.com", "[]");
        $publisher($update);
        return $this->redirectToRoute('/somewhere');
    }

Any clue what is causing this error? Thank you.

**Comment by dchorel** [comment]
I think I found why it was doing that. 
$publisher was invoked from an other method wich was not forcing a string so it was returning an object...

**Comment by land22** [comment]
i have same problem. But i don't know how can i fix it. I'am trying in symfony 4

**Comment by andreaspaita** [comment]
in JwtProvider add 

        $token =  (new Builder())
            ->set('mercure',  ['subscribe' => ['*']])
            ->sign(new Sha256(), new Key($this->secret))
            ->getToken()
            ->toString();
