### ISSUE TITLE
Error creating certificate, unauthorized

### ISSUE THREAD

**Issue by tpharaoh** [dunglas/mercure#126]
I am running this as root
`JWT_KEY='myJWTKey' ACME_HOSTS='domain.com' ADDR=':3000' ./mercure`

`2019/07/27 00:05:46 http: TLS handshake error from 105.200.193.107:61833: acme/autocert: unable to authorize "domain.com"; challenge "tls-alpn-01" failed with error: acme: authorization error for domain.com: 403 urn:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge; challenge "http-01" failed with error: acme: authorization error for q3dot.com: 403 urn:acme:error:unauthorized: Invalid response from http://domain.com/.well-known/acme-challenge/pdhGTi50WH_KmaV2Jy9ucI18rLtiBRHJiqaTE5GlWiA [79.134.108.155]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"`

is there a missing dependancy?

**Comment by dunglas** [comment]
You cannot create a Let's Encrypt certificate for the port 3000. Your server must listen on the default HTTP and HTTPS ports.

**Comment by tpharaoh** [comment]
Thanks. Yea, I was testing on a server which had a *:443 setup, so the cert wasn't created. Deployed to another server and done.

Perfectly easy :)
