### ISSUE TITLE
[SUPPORT] Lexik JWT and User auth

### ISSUE THREAD

**Issue by stipic** [dunglas/mercure#128]
Hi,

i have question about authentication. 

I use Lexik JWT authentication and when my user login i need to connect him on Mercure topic but what if someone else connect too on same topic and listen data that he don't have permissions.

I have channel for every user ```user/{id}``` and i want to prevent any other user or anonymous connect to someone else topic.

If i need to use COOKIE there is another problem, my application is on two different domains.

app.domain.com <- Angular front application
api.domain.com <- symfony api platform

Thanks, great project and srry for probably noob question but documentation is very shy.

**Comment by dunglas** [comment]
For secure (private) updates, you have to use the `targets` as described here: https://github.com/dunglas/mercure/blob/master/spec/mercure.md#authorization

For the cookie, you can set a cookie for the whole domain (including subdomains): https://stackoverflow.com/a/23086139/1352334

I hope this helps.
