### ISSUE TITLE
AWS EB - Certificate signed by unknown authority

### ISSUE THREAD

**Issue by brutalnv** [dunglas/mercure#130]
Hello!
I faced this issue running mercure on AWS ElasticBeanstalk instance:

```
-------------------------------------
/var/log/eb-docker/containers/eb-current-app/eb-771cc6604e34-stdouterr.log
-------------------------------------
time="2019-08-01T19:42:27Z" level=info msg="Mercure started" protocol=https
2019/08/01 19:43:44 http: TLS handshake error from 31.132.178.66:6018: Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority
2019/08/01 19:43:58 http: TLS handshake error from 31.132.178.66:6017: acme/autocert: missing certificate
```

My Dockerrun file:

```
{
 "AWSEBDockerrunVersion": "1",
 "Image": {
  "Name": "dunglas/mercure"
 },
 "Ports": [
	 {
	  "HostPort": "80",
	  "ContainerPort": "80"
	 },
	 {
	  "HostPort": "443",
	  "ContainerPort": "443"
	 }
 ]
}
```

Any ideas what the cause might be?
I'm currently using a workaround by mapping volume with manually generated certs to the docker container and it works like a charm.

**Comment by dunglas** [comment]
It looks like a proxy or a security rule (in Beanstalk?) prevents the hub to contact Let's Encrypt. Another cause can be that the default TLS cert bundles isn't installed, but if you use the official Docker image it shouldn't be the case. Sorry I don't know Beanstalk very well and I never tried Mercure on it.

**Comment by byhoratiss** [comment]
I'm using Mercure as a service with AWS ECS.
I'm using an AWS SSL certificate (provided by ACM), linked to an LB.
My LB is receiving HTTP & HTTPS connections, but only using HTTP to Mercure service running on HTTP only, and you must use the HEARTBEAT environment variable to avoid problems in Mercure service.

I hope I explained myself correctly, let me know if you need some help.

**Comment by brutalnv** [comment]
Thanks for your advice, will try to deploy using ECS and load balancer. Looks like it will be good choice in my this case.

**Comment by Richard87** [comment]
Hi, I got the same problem, but posted in on this issue #175

**Comment by Richard87** [comment]
The problem is the docker image, it is missing the ca-bundle...
Adding thins in the final image in Dockerfile solves the problem:

`
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
`

**Comment by thedomeffm** [comment]
> and you must use the HEARTBEAT environment variable

What do you mean exactly? I have issues in my setup with (AWS-LB and AWS-ECS)

**Comment by byhoratiss** [comment]
@thedomeffm Inside definition task within AWS-ECS, use the environmental config "HEARTBEAT_INTERVAL". I'm using "25s" cause of high latency of my users.
The config is described in docs: https://mercure.rocks/docs/hub/config
