### ISSUE TITLE
TLS handshake error acme/autocert: missing certificate

### ISSUE THREAD

**Issue by btribouillet** [dunglas/mercure#135]
Hi,

I'm trying to deploy to production (so far on the staging environment) an app I built using Mercure.

Following the documentation :

> To run it in production mode, and generate automatically a Let's Encrypt TLS certificate, just run the following command as root:

`JWT_KEY='myJWTKey' ACME_HOSTS='example.com' ./mercure`

Unfortunately, an error was thrown :

> ERRO[0000] listen tcp :443: bind: permission denied

I'm using an AWS pre-config through Cloudways (PaaS). Therefore the port 443 might already be used (as confirmed below from their support). 

> As port 443 is already listening for HTTPS therefore I have enabled port 5000 and used ADDR=":5000" with the command to make it working

So following the given solution from Cloudways I executed :

`JWT_KEY='myJWTKey' ACME_HOSTS='staging.domain.com' ADDR=":5000"  ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* ./mercure`

So far so good :

> INFO[0000] Mercure started                               protocol=https

Then when I launch my app using SSE :

```
const item_updated_es = new EventSource(('https://staging.domain.com:5000/hub?topic=' + encodeURIComponent(`https://domain.com/api/v1/endpoint/${id}`));
item_updated_es.onmessage = e => {
  // ...
};
```

Error is thrown in the server console :

> 2019/08/14 07:16:44 http: TLS handshake error from 164.177.43.41:53062: acme/autocert: unable to authorize "staging.domain.com"; challenge "tls-alpn-01" failed with error: acme: authorization error for staging.domain.com: 403 urn:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge; challenge "http-01" failed with error: acme: authorization error for staging.domain.com: 403 urn:acme:error:unauthorized: Invalid response from http://staging.domain.com/.well-known/acme-challenge/KG0mNB_uGmFnrZbA8-GK0-_uc4GuECdB1tg-NIC3xF0 [54.93.91.1]: "<!DOCTYPE html>\n\n<"
> 2019/08/14 07:16:44 http: TLS handshake error from 164.177.43.41:3112: acme/autocert: missing certificate

I then tried using the cert & key files used by my Letsencrypt SSL Certificate

`JWT_KEY='myJWTKey' ACME_HOSTS='staging.domain.com' ADDR=":5000"  ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* CERT_FILE='/pathToSslDir/server.crt' KEY_FILE='/pathToSslDir/server.key' ./mercure`

The same error as above is thrown :

> 2019/08/14 07:16:44 http: TLS handshake error from 164.177.43.41:53062: acme/autocert: unable to authorize "staging.domain.com"; challenge "tls-alpn-01" failed with error: acme: authorization error for staging.domain.com: 403 urn:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge; challenge "http-01" failed with error: acme: authorization error for staging.domain.com: 403 urn:acme:error:unauthorized: Invalid response from http://staging.domain.com/.well-known/acme-challenge/KG0mNB_uGmFnrZbA8-GK0-_uc4GuECdB1tg-NIC3xF0 [54.93.91.1]: "<!DOCTYPE html>\n\n<"
> 2019/08/14 07:16:44 http: TLS handshake error from 164.177.43.41:3112: acme/autocert: missing certificate

Any ideas what should I do?

**Comment by dunglas** [comment]
As stated in the docs, Let's Encrypt only supports the standard HTTPS port. If you use another port, you cannot use Let's Encrypt.
Also, a valid HTTPS server MUST run on port 443. A certificate issued for a custom port will be considered invalid by most browsers.

**Comment by Adeptuce** [comment]
Hi,
I had a similar question, and if I understand, I can't have an Apache server and Mercure hub both HTTPS under the same vhost. Is that rigth ?
