### ISSUE TITLE
Connection error with IE

### ISSUE THREAD

**Issue by Pyrrah** [dunglas/mercure#136]
Hello Kevin,

I tested the release mercure 0.6 with IE11 (and I'm already crying).

For the compatibility with IE, I choose the polyfill JS "Yaffle/EventSource".
I tried also with 2 others polyfills "remy/polyfills" and polyfill.io. Unfortunaly it's the same thing: no connection to the hub and IE error "SCRIPT445: Object doesn't support this action" (line: const url = new URL)

Also, when I try to connect directly to "/hub", I have a HTTP 400 error.
Same thing on https://demo.mercure.rocks/hub with IE11.

Here my code :

```
<!-- Polyfill Yaffle/EventSource -->
<script src="/eventsource.min.js"></script>

<!-- Demo JS Mercure -->
<script>
const url = new URL('https://my.best.hub.mercure/hub');
url.searchParams.append('topic', 'https://my.best.hub.mercure/topicmercure');
const eventSource = new EventSource(url, {withCredentials: true});
eventSource.onmessage = function (e) {
	demo = JSON.parse(e.data);
	if (demo.info) toastr.info(demo.info, 'Info');
};
</script>
```

Can you help me ?

**Comment by dunglas** [comment]
The `URL` API isn't supported by IE11: https://caniuse.com/#feat=url

Can you try with `new EventSource('https://my.best.hub.mercure/hub?topic=https://my.best.hub.mercure/topicmercure', {withCredentials: true});`?

**Comment by Pyrrah** [comment]
Thank you, the problem comes from there.
It works fine now!

Have a good day,
