### ISSUE TITLE
[Help] Issues while using cookie to subscribe

### ISSUE THREAD

**Issue by julestruong** [dunglas/mercure#137]
Hi @dunglas  and first, thank you for your work. ❤️ 

I have 2 things to say, one is just an advice and the other is my problem, which i will develop at the end of this issue.

Since Mercure is new, i think you should totally log way more than you actually did. Activating debug should display a lot more than right now, like the content of a jwt, list of current subscribers and so on...

**Second : Here is my issue.**

I watched this video (https://www.grafikart.fr/tutoriels/symfony-mercure-1151), and perfectly followed it.

Everything worked except one thing (otherwise , i would not be posting here 😃  )

When trying to send "private" messages through targets, i'm unable to receive them. I'm sure i'm sending them , there are no errors, and there are logs prouving it : ("Update published")

This is how i create my ES : 
```javascript 

        const url = new URL('http://localhost:1337/hub');
        url.searchParams.append('topic', 'http://example.com/message/{id}');

        const eventsource = new EventSource(url, { withCredentials: true});

        console.log('eventsource', eventsource);

        eventsource.onmessage = e => {
          this.addMessage(JSON.parse(e.data));
        };
```

I use docker
Mercure is using 1337
And my Symfony/Nginx is using 80 

At this point, i'm not able to figure out if this is a "configuration" issue or simply my app.
When i subscribe on the http://localhost:1337/ , i can receive messages. 
When i subscribe through my Symfony App (http://localhost), i'm not.

Do you know where it comes from, and if not , how can i help myself figure it out, it's a pain to debug ...

Thanks in advance.

**Comment by dunglas** [comment]
Hi, can you:

* verify that the browser sends the cookie to the hub
* paste the code you use to set the cookie

Thanks!

**Comment by julestruong** [comment]
1) Verifying ...

Actually this is really strange, with Chrome i only get this : 
![Capture d’écran 2019-08-16 à 18 47 43](https://user-images.githubusercontent.com/3956660/63183888-65412780-c056-11e9-98a5-57a2ec62d91c.png)
But with firefox i can see the cookie in the request.
Plus when i remove the `{withCredentials}`, i get an 401, so i believe this works on Chrome ? or does it ?

2) Code setting cookie 
```php
    public function generate(User $user)
    {
        $token = (new Builder())
            ->set('mercure', [
                'subscribe' => ["http://example.com/user/{$user->getId()}"]
            ])
            ->sign(new Sha256(), $this->secret)
            ->getToken();

        return "mercureAuthorization={$token}; path=/hub; httponly;";
    }
```

**Comment by dunglas** [comment]
And can you also post the publication code? Are the targets matching?

**Comment by julestruong** [comment]
publisher code inc ...

```php
 if (
            is_null($this->tokenStorage->getToken()) ||
            !is_object($this->tokenStorage->getToken()->getUser())
        ) {
            return;
        }

        /** @var User $userConnected */
        $userConnected = $this->tokenStorage->getToken()->getUser();
        /** @var User $target */
        $target =
            $dealMessage
                ->getDeal()
                ->getBuyer()
                ->getId() === $userConnected->getId()
                ? $dealMessage->getDeal()->getSeller()
                : $dealMessage->getDeal()->getBuyer();
        $update = new Update(
            "http://example.com/message/{$dealMessage->getId()}",
            json_encode([
                'dealId' => $dealMessage->getDeal()->getId(),
                'authorId' => $dealMessage->getAuthor()->getId(),
                'authorImg' => $dealMessage
                    ->getAuthor()
                    ->getProfilePicture()
                    ->getUrl(),
                'author' => $dealMessage->getAuthor()->getFirstname(),
                'body' => $dealMessage->getBody()
            ]),
                        ["http://example.com/user/{$target->getId()}"]
        );

        $this->logger->debug('event pushed', [
            'dealId' => $dealMessage->getDeal()->getId(),
            'target' => sprintf('http://example.com/user/%s', $target->getId()),
            'author' => $dealMessage->getAuthor()->getId()
        ]);

        $toto = $this->publisher;
        $toto($update);
```

And yes, i'm definitly sure they are matching.
I log the target when i'm publishing a message, and i check the cookie jwt that subscribe on the other hand. They are the same :'(

**Comment by julestruong** [comment]
ah je viens de voir que j'avais ça 
![Capture d’écran 2019-08-16 à 19 39 57](https://user-images.githubusercontent.com/3956660/63186822-a7ba3280-c05d-11e9-9d67-b8cc3f9dc371.png)

pourtant je suis en : CORS_ALLOWED_ORIGINS=*

**Comment by julestruong** [comment]
( merde j'suis passé en francais lol ) 

Bon bah c'était ça , fallait juste que je lise l'erreur : CORS_ALLOWED_ORIGINS=http://localhost
it worked ! :) 

merci pour ta réactivité ^^
