### ISSUE TITLE
Bug with nginx and curl

### ISSUE THREAD

**Issue by UncertaintyP** [dunglas/mercure#138]
I have a Laravel app using Symfonys Mercure package. The hub is setup behind an nginx reverse proxy as described in the documentation. 
From time to time I receive the following error:
`Error in the HTTP2 framing layer for "https://domain.example/hub". {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0)`

The reason is one the one side the way nginx handles http2 connections ([see](https://trac.nginx.org/nginx/ticket/1250)) on the other hand curl in older versions (that are currently used by Ubuntu 16/18 LTS and maybe others).
A fix has been introduced in version curl-7_65_3 ([see](https://github.com/curl/curl/commit/3f5da4e59a556fc68272a9857a38dd75234d0c04)).

According to the ticket at nginx this affects browsers as well (can't tell if clients had this already) and a workaround is to set `http2_max_requests` to an extremely large number (e.g. many millions).

Should that be mentioned in the nginx documentation part and the fix be incorporated in the provided nginx configuration example?

**Comment by dunglas** [comment]
We could add it with a comment pointing to the Nginx issue indeed. Thanks for investigating and finding a fix!

**Comment by UncertaintyP** [comment]
I did some testing, e.g. sending thousands of messages to nginx/mercure.
The proposed nginx fix (`http2_max_requests = 20000000;`) did not help but the current version (7.65.3) of curl (libcurl for php-curl to be more precise) seems to resolve the bug.

**Comment by UncertaintyP** [comment]
Forgot about this. So for everyone reading the libcurl version did resolve the error in local dev environment but not in production. Have yet to find out why it is occurring and how to resolve it.
