### ISSUE TITLE
401 unauthorized subscriber

### ISSUE THREAD

**Issue by pifaace** [dunglas/mercure#139]
Hi @dunglas 
I'm trying to implement Mercure in a real app. I appreciate your work then I'd like to say thank you !

But I have an issue about Authorization topic.
My app allows my users to be connected, then, they can receive some notifications.
So the updates will be private.

I'm using docker, here my mercure and server container :
```
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server

  mercure:
    image: dunglas/mercure
    ports:
      - '3000:80'
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - DEBUG=1
```
I don't allow anonymous connection.

When a new article is published, a notification is pushed
```php
$this->articleManager->create($article);
$update = new Update(
                'http://symfony-blog.fr/new/article',
                json_encode(['event' => 'newArticle']),
                ['http://symfony-blog.fr/group/users']
            );
$publisher($update);
```

Then I created a service to generate the cookie the users 
```php
public function generate(): string
    {
        $token = (new Builder())
            ->withClaim('mercure', ['subscribe' => ['http://symfony-blog.fr/group/users']])
            ->getToken(new Sha256(), new Key($this->secret));

        return sprintf('%s=%s; path=hub/; httponly;', self::MERCURE_AUTHORIZATION_HEADER, $token);
    }
```
And I set this cookie thanks to a subscriber for each response 
```php
public function onKernelResponse(ResponseEvent $event)
    {
        if (null === $this->tokenStorage->getToken() || !$this->tokenStorage->getToken()->getUser() instanceof User) {
            return;
        }

        $cookie = $this->cookieGenerator->generate();

        $event->getResponse()->headers->set(
            'set-cookie',
            $cookie
        );
    }
```

Finally my client subscribe to the topic 
```twig
{% if is_granted('ROLE_USER') %}
            <script>
                const url = new URL('http://localhost:3000/hub');
                url.searchParams.append('topic', 'http://symfony-blog.fr/new/article');

                const eventSource = new EventSource(url);

                // The callback will be called every time an update is published
                eventSource.onmessage = e => console.log('New article has been published'); // do something with the payload
            </script>
        {% endif %}
```

The cookie is set in the headers, as you can see there
https://zupimages.net/up/19/34/y3f8.png
But also the hub throw a 401 unauthorized..

Here is the token from my server side -> [token](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.EcVwk1fVIQISeru1hT4roufm_kycTjzb8_8B3kcYF_k)
And here the token generate by my service for the cookie -> [token](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJodHRwOlwvXC9zeW1mb255LWJsb2cuZnJcL2dyb3VwXC91c2VycyJdfX0.2vsJuxecvlup1G-GTm9kMuz-yMLG1ubfIiTgdnzVphE)

I don't know whats wrong.
I tried to add `{withCredentials: true}` to the EventSource object but didnt work.

Second question, do I have to send the cookie in every request ?

Thanks a lot for your help

**Comment by dunglas** [comment]
Can you paste the logs of the hub? It should tell why a 401 is thrown.

> Second question, do I have to send the cookie in every request ?

No, as it's a cookie, it has to be set only one time, then the browser will take care of sending it to the hub automatically until it expires.

**Comment by pifaace** [comment]
Here is the logs from the container :
[screen](http://zupimages.net/viewer.php?id=19/34/kf0y.png)

But I success to do something but I'm not sure how.
So in my docker-composer I added this : `CORS_ALLOWED_ORIGINS=http://symfony-blog.fr:8000`
Then I added `{withCredentials: true}` to the EventSource object cuz like a understand (correct me if i'm wrong) the hub and my app are not on the same `Domain`

And it works ! 

Also I noticed something, 
I assume that public updates are unauthorized
All my user must have a cookie to be connected to the hub
I tried this : 
A user with no cookie tries to subscribe to a topic,  he gets a 401
And now I set a cookie to this user and I refresh the page, but He gets a 401 again, even though he has the jwt in his cookies

Is that normal ? 

Hope I was clear

**Comment by byhoratiss** [comment]
I believe your problem is your "path" in your cookie.
In the screenshot, the domain for your "site" is "symfony.fr" and the domain for mercure is "localhost", so, cookies should be "path=localhost" or "symfony.fr".

Of course you have to set the cookie JWT using exactly the same JWT_KEY and cypher (can't remember exactly which now, is late).

One way to solve could be using a subdomain for your mercure service, kinda "mercure.symfony.fr", and changing your cookie path to "path=.symfony.fr" (note the dot at the begining) so your cookie can be shared across all "symfony.fr" domain and subdomains.

Hope it helps

**Comment by pifaace** [comment]
Hi @byhoratiss thanks for your answer
yeah, this is a problem about the domain for sure.
I didn't notice this /hub in the path
Anyway, I'll try your solution as soon as possible :)
I'll keep you up to date

**Comment by pifaace** [comment]
So I wanted to change the mercure domain for the same that my app `symfony-blog.fr`, to do things simply.
i changed the ADDR 
```yml
mercure:
    image: dunglas/mercure
    ports:
      - '3000:80'
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=http://symfony-blog.fr
      - DEBUG=1
      - ADDR=symfony-blog.fr:3000
```
But now, I cant access to the hub anymore
![Screenshot_20190905_170311](https://user-images.githubusercontent.com/17497139/64354102-13f5d980-cfff-11e9-811b-4b7941a7408c.png)

I tried without docker with
`JWT_KEY='aVerySecretKey' ADDR='symfony-blog.fr:3000' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* ./mercure `
And it works
Weird ..

**Comment by byhoratiss** [comment]
I don't use the ADDR in my mercure service definition. Did you try removing that?

**Comment by pifaace** [comment]
If I remove it, the hub address will be localhost (default value), not what i want

**Comment by byhoratiss** [comment]
If you remove the ADDR, the port 3000 will be mapped to your "localhost", but if you have your "/etc/hosts" alias like `127.0.0.1 localhost symfony-blog.fr` it should work.

If you are experiencing "weird" behaviours, what are the logs saying?

**Comment by pifaace** [comment]
yeah `127.0.0.1 localhost symfony-blog.fr` allows me to access to the hub 
![Screenshot_20190905_174827](https://user-images.githubusercontent.com/17497139/64357671-633f0880-d005-11e9-9f71-7bd3a030854c.png)
but its a lure cuz the real address is localhost:3000/hub
So `MERCURE_PUBLISH_URL=http://symfony-blog.fr/hub` will not work

**Comment by byhoratiss** [comment]
Are you using docker? If yes, you should use the "service name" instead of full URL.
Something like "http://mercure/hub" if your service is defined as "mercure" in docker-compose file.

**Comment by pifaace** [comment]
you absolutely right, I'm tired sorry
I'll put `{withCredentials: true}` for my dev env and I added http://symfony-blog.fr:8000 in the CORS_ALLOWED_ORIGINS
```
mercure:
    image: dunglas/mercure
    ports:
      - '3000:80'
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=http://symfony-blog.fr:8000
      - DEBUG=1
```
And it works thank you :)
