### ISSUE TITLE
Unable to get it working locally

### ISSUE THREAD

**Issue by maryo** [dunglas/mercure#14]
Hi. Thank you for the work. Looks awesome. I wish you best luck with this project.
I had a problem to get it working but now it works fine so i deleted the contents of this message. Not sure what exactly was the problem. Probably something with exclamation mark in JWT key :-).

**Comment by dunglas** [comment]
Maybe do you need to escape the exclamation mark by putting single quotes around the value?
Btw, I'm interested in Windows's user feedback. The Windows binary is currently not generated because I don't know if it works properly on this platform.

**Comment by kevinsegal** [comment]
I'm stuck on this as well. Trying to deploy an instance via Kubernetes, keep getting unauthorized no matter what I do, even if I'm trying to use the ALLOW_ANONYMOUS it still comes back 401. Does the exclamation mark matter, or why does it still ask for auth despite permitting anonymous connections? Or could this be a problem with authorized publishing access, is there a * wildcard option for publisher origins?

**Comment by dunglas** [comment]
@kevinsegal if you have set `ALLOW_ANONYMOUS` to 1, do **not** provide a JWT token (or cookie) when subscribing. `new EventSource('https://example.com/hub?topic=foo` should work (clear your cookies if it doesn't).
However, you still need a valid JWT to publish updates, and it must have a `publish` key set to an empty array.
Also, be sure to set the secret key in the environment variable, not a token.

**Comment by dunglas** [comment]
Thank you very much for your detailed feedback @maryo. I'll add the Windows build to the release page asap then.

**Comment by dunglas** [comment]
@kevinsegal @maryo I've added a  "troubleshooting" section to the readme: https://github.com/dunglas/mercure/pull/15

Would you mind checking if it helps?

**Comment by maryo** [comment]
Great. It helped me to better understand the authorization.
