### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by mati2251** [dunglas/mercure#140]
I have issue. I have server in node and this server return error 401. This is server code: 

```
const http = require('http');
const querystring = require('querystring');

const demoJwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJmb28iLCJiYXIiXSwicHVibGlzaCI6WyJmb28iXX19.LRLvirgONK13JgacQ_VbcjySbVhkSmHy3IznH3tA9PM';

const postData = querystring.stringify({
    'topic': 'http://localhost:3000/demo/books/1.jsonld',
    'data': JSON.stringify({ key: 'updated value' }),
});

const req = http.request({
    hostname: 'localhost',
    port: '80',
    path: '/hub',
    method: 'POST',
    headers: {
        Authorization: `Bearer ${demoJwt}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(postData),
    }
}, (res) => {
    console.log(`Status: ${res.statusCode}`);
    console.log(`Headers: ${JSON.stringify(res.headers)}`);
});

req.on('error', (e) => {
    console.error(`An error occured: ${e.message}`);
});

req.write(postData);
req.end();

req.write(postData);
req.end();
const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('Hello World\n');
});

server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
}); 
``` 

and i run mercure hub command:
` sudo docker run     -e JWT_KEY='*' -e DEMO=1 -e ALLOW_ANONYMOUS=1 -e PUBLISH_ALLOWED_ORIGINS='http://localhost'     -p 80:80     dunglas/mercure`

**Comment by dunglas** [comment]
Can you check in the logs of the Hub what’s the error? The token is most lively invalid

**Comment by mati2251** [comment]
where i can find log?  hub only returned empty string `"POST /hub HTTP/1.1" 401 13 "" ""`

**Comment by mati2251** [comment]
> Can you check in the logs of the Hub what’s the error? The token is most likely invalid.
where i can find log? hub only returned empty string "POST /hub HTTP/1.1" 401 13 "" ""

**Comment by mati2251** [comment]
> Can you check in the logs of the Hub what’s the error? The token is most likely invalid.

msg="signature is invalid"

**Comment by dunglas** [comment]
So your signature is invalid. It is maybe signed with the bad key. You can use jwt.io to debug.

**Comment by dunglas** [comment]
> `JWT_KEY='*'`

`*` looks like a very weird secret key. You probably don't have signed your token with this key, so the problem is here.

**Comment by mati2251** [comment]
Thanks. Finally works.
