### ISSUE TITLE
Error net::ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by Valkii** [dunglas/mercure#142]
We are trying to use Mercure for a notification system. We made a Chrome plugin to receive notification in real time. We are using EventSourcePolyfill from Yaffle for connection because we have two different domains (one for mercure service and the other one for our Symfony application), with a JWT. 
The connection between hub and plugin does not have any problem.

However, when I locked my PC and I came back after 1 hour for example, I have many errors in browser console (approximately 70 times) and the connection is again established. 
The error is : 
> GET https://notification-example/hub?topic=topic_example net::ERR_NETWORK_IO_SUSPENDED

After investigating, I have to error too in EventSourcePolyfill source :
![eventSource3](https://user-images.githubusercontent.com/52078056/63495268-d43bd780-c4bf-11e9-871b-3055d223684f.PNG)

I used XMLHttpRequest and fetch method, I had same errors. 
I tested this process like 3 days (each times I came back on my PC like morning..), these errors appeared every time. 
Meanwhile, when I don't have this error, I can receive notifications even when after coming back. But during this period, I can't receive notifications. Sometimes, the connection can not be done anymore. 

We set heartbeatInterval at 15s. 

If you have an idea to solve the problem, it would be appreciated !

**Comment by dunglas** [comment]
According to the error, it's because the laptop disable the network when in sleep mode. There is nothing we can do to wake up the network, however the error could maybe be caught to not pollute console logs: https://developer.mozilla.org/en-US/docs/Web/API/EventSource/onerror
