### ISSUE TITLE
[Question] HISTORY_* environment variables

### ISSUE THREAD

**Issue by rmikalkenas** [dunglas/mercure#144]
Testing mercure and dont understand `HISTORY_SIZE` and `HISTORY_CLEANUP_FREQUENCY` environment variables. 
Few questions:
1. `HISTORY_SIZE` what value should i use to keep in history for example 5 records? At this moment if I set `HISTORY_SIZE=5`, publish 10 messages and then subscribe with `Last-Event-ID=(first published message id)` - I receive 9 messages, shouldnt it be 4 messages?
2. `HISTORY_CLEANUP_FREQUENCY=1` should cleanup history on every new published message (if I understand it correctly), but it doesnt. (Same scenario as described in 1.)

**Comment by dunglas** [comment]
It's maybe a bug, but as the implementation is probabilistic in partly in memory, can you try with bigger numbers?
