### ISSUE TITLE
How to run Mercure in production with Apache

### ISSUE THREAD

**Issue by Adeptuce** [dunglas/mercure#148]
Hello,

I have a symfony projet on an Apache server that uses Mercure.

To run the Mercure hub in production, I extract the archive mercure_0.6.2_Linux_x86_64.tar.gz into a subfolder mercure at the root of my project.

Then I run the command:
JWT_KEY='myJWTKey' ACME_HOSTS='example.com' ./mercure
with my informations

But the hub doesn't run with this error:
FATA[0000] listen tcp :443: bind: permission denied

Can you help my please?

Thank you

**Comment by zorn-v** [comment]
Port  443 already used. By apache I think.

> I have a symfony projet on an Apache server

Use nginx Luke :smile: (not regarding to this issue)

**Comment by Adeptuce** [comment]
Thank you @zorn-v for your reply.

When I set CERT_FILE and KEY_FILE env vars with cert and key of my domain, the Mercure hub run in HTTPS. I also add ADDR=':3000'.
I can see Mercure Debugging Tools on https://mydomain.com:3000
But when I want to POST a message toward the hub I've got this error:
http: TLS handshake error from 146.88.237.131:58704: remote error: tls: unknown certificate authority

**Comment by dunglas** [comment]
If Apache is already acting the TLS termination, then just run mercure on the another port listening on a local IP only, and use Apache as a proxy: https://httpd.apache.org/docs/2.4/en/mod/mod_proxy.html

It will be as fast and as secure. And in this case, you don't have to use Mercure's HTTP support, just let Apache doing the TLS/HTTP/2 termination.

**Comment by Adeptuce** [comment]
I installed the new version (0.7.1) and I finally see the following error:
DEBU[0074] Subscriber not authorized to receive this update (no targets matching)  event_id=0e1c7c20-fb63-454f-8f9e-d522fbe3781e event_retry=0 event_type= last_event_id= remote_addr="146.88.237.131:47968" subscriber_targets="[]" subscriber_topics="[activite]" update_data="{\"userId\":2}" update_targets="[parc/1]" update_topics="[activite]"

I use the cookie authentication system with this cookie generator:
`public function generate(Parc $parc)
    {
        $token = (new Builder())
            ->set('mercure', ['subscribe' => ["parc/{$parc->getId()}"]])
            ->sign(new Sha256(), $this->secret)
            ->getToken()
        ;

        return "mercureAuthorization={$token}; path=https://myhub.com/hub; httponly;";
    }`

And I use `{withCredentials: true}` with EventSource.

**Comment by dunglas** [comment]
The `path` of the cookie is invalid: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Scope_of_cookies
It should only be the path. Use `domain` for the domain (and keep in mind that the domain setting the cookie and the mercure hub must be the same - or the hub can be a subdomain).

**Comment by Adeptuce** [comment]
I set domain and path=/hub and now everything works.

Thanks a lot @dunglas and @zorn-v !

**Comment by disco07** [comment]
how to put mercury in production with apache in ubuntu. Can you help me please ? Urgent

**Comment by frizquierdo** [comment]
[Adeptuce](https://github.com/Adeptuce) Hi, I'm trying to make run mercure with apache proxy and SSL virtualhost (https://mysite.com for example), but I don't understand your solution. Can you help me?
