### ISSUE TITLE
Allow pass JWT as query parameter

### ISSUE THREAD

**Issue by zorn-v** [dunglas/mercure#150]
As native EventSource does not support set headers, may be allow to pass JWT via url ?

**Comment by dunglas** [comment]
Native EventSource support cookies. In the context of a web browser, using cookies is the most secure solution, and should always be preferred.

**Comment by zorn-v** [comment]
In which case it "most secure" ? Headers and query string is visible over http. If using https only server owner can get it. Yes, headers does not logged, but who forbid server owner to log appropriate headers ?

**Comment by dunglas** [comment]
If the cookie is marked HttpOnly (which we recommend), it cannot be accessed through JavaScript, and so make XSS vulnerabilities less critical. Using HttpOnly Secure cookies to store tokens is considered a best practice by the entire web community, especially now that the SameSite option is widely implemented.

**Comment by zorn-v** [comment]
If NOT uinng cookie, token stored only in you code :wink:
