### ISSUE TITLE
[Symfony 4] How to send missed message when an user reconnect

### ISSUE THREAD

**Issue by Xutyr** [dunglas/mercure#151]
Hi,

First of all, thanks a lot regarding the project. :)

**What I want to do :**
I'm trying to used the mercure protocol for a notification system for my users (like notify the user when a new invoice has been published). 
Thanks to the documentation and Grafikart's video, I'm able to send a message to a specific user as soon as he's login.
However I don't understand how to send missed messages when the user came back to the website.

**What I did :**
I read the documentation and found the Reconnection and State Reconciliation part and the Discovery part (which I think I didn't understand...).

I tried to inject the Last-Event-ID of the last message received in a cookie as below:
```
var handleMercure = () => {
   const url = new URL('http://mysite.fr:3000/hub');
   url.searchParams.append('topic', "http://mysite.fr/notif");
   const eventSource = new EventSource(url, {withCredentials: true});
   console.log(url);
   eventSource.onmessage = e => {
       console.log(e);
       document.cookie = `Last-Event-ID=${e.lastEventId}`;
   }
};
```

On the publisher side I don't understand what should I config to make this work:
```
public function sendNotif(?User $User=null){
     $target = [];
     if($User!==null){
         $target = ["http://mysite.fr/notif/user/{$User->getId()}"];
     }
     $update = new Update("http://mysite.fr/notif", json_encode("test"), $target);
     var_dump($update);
     $this->bus->dispatch($update);
}
```
**What is happening :**
When the user close the site or login out, then come back/reconnect to the site, the notifications send during this time aren't pushed to him.

Could you help me please in order to understand what I missed?
  
Thanks in advanced for the help.

**Comment by dunglas** [comment]
The re-connection mechanism is mostly intended for network failures (the connection is lost, then retrieved). In this case the reconciliation is automatic.

For your case, if you know the ID of the last event sent my Mercure, you can just pass it through the Hub URL:

```js
   const url = new URL(`http://mysite.fr:3000/hub?Last-Event-ID=${e.lastEventId}`);
```

You can also use an HTTP header named `Last-Event-ID`.

**Comment by dunglas** [comment]
In your case, you'll probably need some ACK system. The client will have to mark a notification on the server as received.
For instance, you could expose the available notification objects as a REST API, and issue a `PUT` request on a specific notification object to mark it as read when it has been received (through Mercure of any other way, such as Web Push, or SMS) by the client. Then, when a client reconnect after a long time, you have the list of unread notifications to push.

**Comment by Xutyr** [comment]
Hello Dunglas,

Thanks for your answer. I have a better understanding now.
I close the issue.
