### ISSUE TITLE
Having trouble seeing messages for Subscribers

### ISSUE THREAD

**Issue by fabioelia** [dunglas/mercure#152]
I have a local development version working fine, where I have the symfony app publish and browsers receiving those events.

However after moving the mercure server into a production environment in AWS / ECS I'm never seeing the "Event Sent" log.

Here's a snippet of most of the traffic I'm seeing
```
time="2019-09-07T16:39:00Z" level=info msg="New subscriber" remote_addr="10.0.0.34:8222"
time="2019-09-07T16:39:06Z" level=info msg="Update published" event_id=acdd05b1-fb10-4094-a033-979a7123482c remote_addr="10.0.0.34:8224"
10.0.0.34 - - [07/Sep/2019:16:39:06 +0000] "POST /hub HTTP/1.1" 200 42 "" "Symfony HttpClient/Curl"
```

The docker settings (going back to the most basic / open settings):
![image](https://user-images.githubusercontent.com/633247/64477809-e8453180-d16d-11e9-9bc1-17e13835913c.png)

I can see locally when it works, a "Event Sent" message gets fired, and then the browsers receive that update. In this setup I'm never seeing that happen, so hopefully that is a clue for debugging this.

Is there a way to enable more logging? Can we log out the topic url's on the server / If a user is reachable?

**Comment by dunglas** [comment]
That's weird. I plan to add more detailed logs soon. Are you using target? Are you sure that there are no CORS error in the console of the web browser? `*` is sometime not enough, for some features you need to explicitly whitelist the domains.

**Comment by dunglas** [comment]
Can you try with the master version (I'll tag a new version tomorrow if it helps) and `DEBUG=1`. I added much more logs. It should help to figure out what's going on.
