### ISSUE TITLE
Client connection re-establishment

### ISSUE THREAD

**Issue by joeblew99** [dunglas/mercure#153]
Mobiles will close the connection after a certain time ( especially browsers)
So we can use https://github.com/appleboy/gorush. In this case if the HUB detects that the client is no longer connected, it can send the message via gorush.
This will open the app, and so re-establish the SSE connection.

**Comment by dunglas** [comment]
Indeed, using Web Push to "awake" an that has been closed is a common pattern with Mercure! The browser will never close the connection when the page or app is running in foreground.
