### ISSUE TITLE
401 json: cannot unmarshal string (subscription)

### ISSUE THREAD

**Issue by one1two2** [dunglas/mercure#164]
Hey,  

First I want to thank you for this module It is very promising and I didn't have any problems with public subscribing/publishing

Right now I am trying to set authorization with mercure, but I got some famous 401 error with mercure log:
level=info msg="json: cannot unmarshal string into Go struct field mercureClaim.subscribe of type []string"
Then 401 error.

I tried two auth methods by cookie:

```
    const es = new EventSourcePolyfill(this.MERCURE_HOST + '?topic=http://localhost:8000/user/1', {
      withCredentials: true
    });
```

by token

```
    const es = new EventSourcePolyfill(this.MERCURE_HOST + '?topic=http://localhost:8000/user/1', {
      headers: {
        Authorization: 'Bearer ' + token
      }
    });
```

I noticed that in second method I got authorization header but error output is the same.

Cookiegenerator:

```
        $token = (new Builder())
            ->withClaim('mercure', ['subscribe' => "http://localhost:8000/user/1"])
            ->getToken(new Sha256(), new Key($this->mercureSecret));

        return "mercureAuthorization={$token}; path=/hub; secure; httponly;";
```

If I understand the secret is JWT_KEY from docker configuration.

Mercure docker:
<img width="1427" alt="mercure" src="https://user-images.githubusercontent.com/6128314/65953545-739ba500-e444-11e9-90ac-aeecf8381fb3.png">

Request:
<img width="1018" alt="request" src="https://user-images.githubusercontent.com/6128314/65953591-9332cd80-e444-11e9-81db-7b157f4b90f9.png">

Request Cookie:
<img width="1031" alt="cookie" src="https://user-images.githubusercontent.com/6128314/65953680-c70df300-e444-11e9-9e47-6eaca7305cfc.png">

Well I guess I read documentation, check issues twice but It is possible that I am missed something obvious in configuration.

**Comment by dunglas** [comment]
Can you copy the content of the JWT please? It looks like it contains invalid JSON.

**Comment by one1two2** [comment]
<img width="1224" alt="jwt" src="https://user-images.githubusercontent.com/6128314/65954830-0fc6ab80-e447-11e9-8cad-8ad8faa773f5.png">

If that is what you asked hope it helps. Right now I'm bit confused.

**Comment by dunglas** [comment]
Got it. Should be `['subscribe' => ["http://localhost:8000/user/1"]]` (an array of strings, not a string)!
