### ISSUE TITLE
Usage of asymetric key

### ISSUE THREAD

**Issue by julien-leclercq** [dunglas/mercure#165]
Hello, 

Just saw your talk about mercure this morning and to be honest this looks great. 
I currently work at fewlines on a OAuth provider and we are implementing asymetric key signatures on JWT and this made me wonder if it would be a possible future feature for mercure or if this has been investigated already. 

Cheers Julien.

**Comment by dunglas** [comment]
Hi Julien, and thanks for the feedback. Yes it's being implemented: #156
