### ISSUE TITLE
How to set a cluster

### ISSUE THREAD

**Issue by pyatnitsev** [dunglas/mercure#174]
Hi!

Thanks for mercure!

In the documentation you're wrote that have an Private beta HA version. 

Can you write how to run mercure in clusetr mode? Is it supported or not?

**Comment by dunglas** [comment]
It's only supported by the (paid) HA version. The on premise HA version is already available (contact me directly if you need more information: dunglas+mercure@gmail.com), the managed version will be available soon.

Alternatively, you can also write an adapter for clustering mode by yourself in using the Go library we provide.

**Comment by pyatnitsev** [comment]
Ok, thanks!

**Comment by Kyngo** [comment]
Any updates on this? @dunglas
