### ISSUE TITLE
Possible lost of update

### ISSUE THREAD

**Issue by jderusse** [dunglas/mercure#178]
If a subscriber "ask" for updates since a given ID, the current implementation may lost updates 

https://github.com/dunglas/mercure/blob/a7887c0569b18bae8d8fce3750e3b29b99060286/hub/subscribe.go#L91-L100

between the last update sent by `h.sendMissedEvents()` at line 92 and `h.newSubscribers <- updateChan` at line 100 updates may have been sent and not dispatched to the subscriber..

**Comment by dunglas** [comment]
Good catch, thanks for reporting this! Could you try if https://github.com/dunglas/mercure/pull/179 fixes the issue?
