### ISSUE TITLE
Specify target don't send to specify user

### ISSUE THREAD

**Issue by tymon82** [dunglas/mercure#180]
i've made publish token with payload:
`{
  "mercure": {
    "publish": [
      "*"
    ]
  }
}`

And set target: `user`

Then generate token for subscriber with payload:

`{
  "mercure": {
    "subscribe": [
      "user"
    ]
  }
}`

And i cant get any update with defined target when publish.

What i'm doing wrong. Im using APi Platfom

**Comment by tymon82** [comment]
anyone?

**Comment by dunglas** [comment]
Can you paste what you get in the logs?

**Comment by tymon82** [comment]
> Can you paste what you get in the logs?

which logs?

**Comment by dunglas** [comment]
The logs of the Hub.

**Comment by tymon82** [comment]
@dunglas 
`time="2020-02-07T12:55:47Z" level=info msg="Update published" event_id=d9f0196b-13b7-40d4-9eac-1c6cd89f394f event_retry=0 event_type= remote_addr=54.93.247.111 update_targets="[/subscriber/a0311b4d-fe97-4ea5-8b58-4bf9dc02ef02 /subscriber/313d68cd-92f6-4181-b19e-43b9bc6cb52d]" update_topics="[https://localhost:8900/api/projects/ca5be07c-ec79-4b0a-8641-3a423645b716/stories]"`

**Comment by tymon82** [comment]
user token has subscribe filled:
`{
  "mercure": {
    "subscribe": [
      "/subscriber/a0311b4d-fe97-4ea5-8b58-4bf9dc02ef02"
    ],
    "publish": [
    ]
  }
}`

**Comment by tymon82** [comment]
@dunglas what are differences between `update_targets` and `subscriber_targets`

**Comment by tymon82** [comment]
@dunglas 
`time="2020-02-13T11:12:20Z" level=info msg="Event sent" event_id=3c5fdc1b-0dc6-4a76-b2a4-9c050278e54b event_retry=0 event_type= last_event_id= remote_addr=79.190.104.138 subscriber_targets="[/subscriber/c0b69708-c337-4b60-a18b-234cfa919b82 /subscriber/chat/c0b69708-c337-4b60-a18b-234cfa919b82]" subscriber_topics="[/activity/{id}]" update_targets="[]" update_topics="[/activity/c0b69708-c337-4b60-a18b-234cfa919b82]"`

**Comment by tymon82** [comment]
@dunglas what must be set to get it worked?

**Comment by monstrum** [comment]
Check this video on youtube. I don't speak french, but the code might help. It was long time ago I try mercure rock. couldn't found my implementation anymore.

https://www.youtube.com/watch?v=pV4jXfDECjU
