### ISSUE TITLE
Installation on Catalina Mac

### ISSUE THREAD

**Issue by castroCrea** [dunglas/mercure#183]
Hi,
I download the this version of mercure mercure_0.7.2_Darwin_x86_64.tar.gz
unzipped and execute it with:

```
JWT_KEY='!ChangeMe!' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure
```

And i got this message

![image](https://user-images.githubusercontent.com/20707343/66904710-dd02e280-f004-11e9-84cf-11721cf7894b.png)

I never tried on other version of Mac, i normally used the docker image.

**Comment by dunglas** [comment]
It looks like it's a new "feature" introduced in Catalina, fortunately it can be disabled in Mac OS settings: https://github.com/hashicorp/terraform/issues/23033#issuecomment-539736692

**Comment by castroCrea** [comment]
Thanks @dunglas 
I just try and the process is:

- In the Finder on your Mac, locate the app you want to open.
- Control-click the app icon, then choose Open from the shortcut menu.
- Click Open.

Then you will have a warning 
![image](https://user-images.githubusercontent.com/20707343/66986766-ca011880-f0bf-11e9-983b-df6bff19791a.png)

Then just run 
```
JWT_KEY='!ChangeMe!' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure
```

It will work.🎊
![image](https://user-images.githubusercontent.com/20707343/66986877-f9178a00-f0bf-11e9-8101-b2a4cd09eb31.png)

**Comment by dunglas** [comment]
Would you mind adding a note in the docs explaining this :)?
