### ISSUE TITLE
OVH is considering Mercure component as a malware

### ISSUE THREAD

**Issue by gdalyy** [dunglas/mercure#184]
After deploying mercure to production along with a symfony 4 application , [OVH](https://www.ovh.com) is considering it as a malware and has bloqued my site.

**Comment by dunglas** [comment]
Do you have more information about this (some logs or something?).

**Comment by dunglas** [comment]
Did you try to contact the support? Unfortunately there is nothing I can do on my side, it's to OVH to fix this.

**Comment by gdalyy** [comment]
I've no logs unfortunately, all what they said that their robots has dected a malware. 
This is their response : 

```
Notre système de surveillance a détecté une opération irrégulière au niveau de votre site. Ce message a pour but de vous alerter sur le fait que votre site et vos données peuvent encourir un risque.
Par mesure de sécurité, nous venons de bloquer l'accès à votre site, cependant, l'accès à votre espace d'hébergement (FTP) reste tout de même accessible.

Vous trouverez ci-dessous les détails techniques de cette opération :

Problème rencontré : Un script malveillant a été détecté sur votre hébergement
Commande apparente : ./mercure
Horodatage: 2019-10-17 03:40:14
```
Apparently they're not authorizing mercure use on mutualized hosting , i'll check with them again the possibility to use it on a VPS.

So i'm closing this . thanks .

**Comment by ctsDevel** [comment]
Hey! can you give us some news? I'm really interested :)

**Comment by gdalyy** [comment]
Hey there , it works on a VPS.
