### ISSUE TITLE
How to revoke subscribers?

### ISSUE THREAD

**Issue by stanleyk** [dunglas/mercure#19]
Hi,

I have a question regarding targeting updates. Let's say I have an Account with many Members and I want to publish an update of the Account info to its Members on an "accounts" topic. At the same time I don't want this update to be received by other subscribers who are not Members.

I thought that Member ID should be target and when the Member is removed from the Account, I remove the Member ID from targets of the update. But what if I have a large Account, with, let's say, thousands of Members? A JWT token containing all Member IDs would be huge and the update would sooner or later hit performance limits...

In the protocol specs you mention a "group of subscribers", which might be a solution regarding the token size, but how do I revoke a subscriber from such group? Is it even possible?

**Comment by dunglas** [comment]
Revocation will have to be handled at the JWT level. Every subscriber will have the "account-<id>" target, to remove a subscriber from this account, you may:

* use a short expiration time for the JWT, so the subscriber will have to refresh it often, and when it will be removed, after the expiration time of the JWT you'll be sure that the subscriber access is revoked
* handle JWT revocation in a stateful auth mechanism that you'll put in front of the mercure hub: then you'll store in a persistence layer the list of revoked JWT, and prevent access if it is

wdyt?
