### ISSUE TITLE
404 in mercure website

### ISSUE THREAD

**Issue by Rashguir** [dunglas/mercure#194]
Hi, i was browsing Mercure's website when i encountered a 404.

The link to [libraries implementing Mercure](https://mercure.rocks/docs/ecosystem/resources#libraries) leads to a 404.

I tough i'd notice you guys :)

**Comment by dunglas** [comment]
Hi, and thanks for reporting. Do you remember where you have found this link? The correct URL is https://mercure.rocks/docs/ecosystem/awesome

**Comment by Rashguir** [comment]
On the "getting started" page : https://mercure.rocks/docs/getting-started
Thanks for the link :)
