### ISSUE TITLE
[Hub] Feature request: Login

### ISSUE THREAD

**Issue by Richard87** [dunglas/mercure#199]
Hi!

What do you think about a /login endpoint, where the user could add the Authorization header/jwt token, and the Hub just responds with a 200 / 401 and SetCookie (if authenticated).

Then the user could connect with a native EventSource with the cookie set, and no dependency on a shared domain

**Comment by dunglas** [comment]
But how this endpoint would know what to do? Wouldn't using an authentication solution with JWT support such as [Auth0](https://auth0.com/docs/tokens/jwt-claims#custom-claims) or [Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) or [Ory](https://www.ory.sh/docs/oathkeeper/pipeline/mutator) (open source).

I suggest to add an example using Auth0 or another solution instead.

**Comment by Richard87** [comment]
I was imagining just validating the jwt and if approved, copying the jwt to a cookie...

But as I write this, I realize the js client could just set the cookie manually before sending the request :)
