### ISSUE TITLE
Publish a helm chart for Kubernetes installation

### ISSUE THREAD

**Issue by sagikazarmark** [dunglas/mercure#211]
Are you planning to publish a helm chart for Mercure?

I'd be happy to create one for the project.

For a fully functioning helm chart you would also need a chart repository. If you are up for running one for yourself, then [ChartMuseum](https://chartmuseum.com/) is the official repository implementation. Otherwise I would humbly suggest using a hosted service published by Banzai Cloud (the company I work for): https://charts.banzaicloud.io/

As a last resort, I can offer hosting the chart in our chart repository: https://github.com/banzaicloud/banzai-charts

We have several third party projects hosting their charts there (like Cadence and Pomerium). (That would also have the advantage of appearing on [Helm Hub](https://hub.helm.sh/))

One last concern regarding helm charts is releasing them. Helm charts are usually versioned independently from the main application. That means you either create a separate repo for charts and version them there or introduce a versioning schema, like `chart/mercure/0.1.0` (and handle tags conditionally in CI).

Let me know what works for you.

**Comment by Ilshidur** [comment]
[There's already an official Helm Chart](https://github.com/dunglas/mercure/blob/master/docs/hub/install.md#kubernetes) : https://hub.helm.sh/charts/stable/mercure 😉

**Comment by sagikazarmark** [comment]
Oh God, I swear I looked a dozens of places, guess just not the right ones. 😄 

Thanks and sorry for noise.
