### ISSUE TITLE
Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by ngdo-pro** [dunglas/mercure#213]
Hi, I tried to deploy Mercure on an OVH Vps.

I created a systemd service and made an nginx conf, but when I try to make an http call, i get this message with a 400 error : 

`Client sent an HTTP request to an HTTPS server.`. 

I'm not really experimented with servers, nginx and co.
Can anyone help ? :sweat_smile: 

Here is my systemd conf:
```
Description= mercure server
After=network.target

[Service]
User=root
Group=www-data
Environment="JWT_KEY='!ChangeMe!"
Environment="ACME_HOSTS='http://localhost'"
Environment="ADDR=:3014"
Environment="USE_FORWARDED_HEADERS=1"
ExecStart=/path-to-mercure/mercure
[Install]
WantedBy=multi-user.target
```

My nginx conf:
```
server {
    server_name example.com;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    location / {
	add_header Access-Control-Allow-Origin *;
        proxy_pass http://localhost:3014;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    ssl_certificate /path/to/ssl/cert.crt;
    ssl_certificate_key /path/to/ssl/cert.key;
}
```

Even a `wget` from my server gets the 400: Bad Request:
```
wget http://localhost:3014/
--2019-11-15 23:07:34--  http://localhost:3014/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3014... connected.
HTTP request sent, awaiting response... 400 Bad Request
2019-11-15 23:07:34 ERROR 400: Bad Request.
```

**Comment by stas3on** [comment]
Hello, you need to change from
`proxy_pass http://localhost:3014;`
to
`proxy_pass https://localhost:3014;`

**Comment by ngdo-pro** [comment]
Thank you @stas3on , in the end, I just took an other vps and removed nginx.

I tried your solution, but it changed nothing. After weeks trying multiple things, the new vps solution was the less painful for me.

**Comment by gponty** [comment]
Same error here
I use Plesk (then with nginx) and like you error 400 (Client sent an HTTP request to an HTTPS server.)
