### ISSUE TITLE
[API PLATFORM] Couldn't connect to server

### ISSUE THREAD

**Issue by Birdiz** [dunglas/mercure#217]
Hi everyone,

I'm just trying to set up the Mercure bundle and using it with an @ApiResource, but I'm facing a problem.

I'm using the following container for the hub :
`mercure:
        image: dunglas/mercure
        environment:
            - JWT_KEY=mykey
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - PUBLISH_ALLOWED_ORIGINS=http://localhost:3000/
            - DEBUG=1
            - CORS_ALLOWED_ORIGINS=*
        ports:
            - "3000:80"`

I got my three environment's variables : 
`MERCURE_PUBLISH_URL=http://localhost:3000/.well-know/mercure
MERCURE_SUBSCRIBE_URL=http://localhost:3000/.well-know/mercure
MERCURE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyIqIl0sInB1Ymxpc2giOlsiKiJdfX0.TJAuKphC4KkMbc99n6VXvxGWoMBfXSwKoLKibuJGQPA`

Then when I'm directly doing a POST request with Insomnia on http://localhost:3000/.well-know/mercure, I get a 200 with a hashed key.
But when I'm trying an update, for instance, on my @ApiResource (with mercure=true), it seems that I can't reach the hub.

`"detail": "Couldn't connect to server for \"http:\/\/localhost:3000\/.well-known\/mercure\"."`

I'm suspecting a authorization's problem.

Any ideas :) ?

**Comment by dunglas** [comment]
Did you try to use the API Platform distribution? It comes with a Mercure hub properly configured: https://github.com/api-platform/api-platform/blob/master/docker-compose.yml#L71-L88

**Comment by Birdiz** [comment]
Hi,

Thanks for your answer.
I didn't use the API Platform distribution delivered with docker.
We did it manually...

I'll try with your configuration.
Thanks again.
