### ISSUE TITLE
multiple identical messages for one recipient

### ISSUE THREAD

**Issue by zserg84** [dunglas/mercure#218]
Hi.
I have graphql api and method to subscription to update from a topic.
```
public function resolveUpdateBalanceSubscribe(): SubscriptionData
{
        $user = $this->userManager->currentUser();
        $token = $this->jwtProvider->getSubscribtionToken([$user->getId()->toString()]);
        $topic = 'balance/update';

        return new SubscriptionData((string) $token, $topic);
}

// jwtProvider
public function getSubscribtionToken(array $targets): Token
{
        return (new Builder())
            ->withClaim('exp', time()+$this->expirationTime)
            ->withClaim('mercure', ['subscribe' => $targets])
            ->getToken(new Sha256(), new Key($this->secretKey))
            ;
}
```

I want user can subscribe to topic after login on the site.
And if my client calls this method, it receives the jwt token. And everything is ok. After I publish a message, my client receives it. 
If my client calls api method for subscribing again, it receives another jwt token. And after I publish a message my client receives two more the same message. 
![Снимок экрана в 2019-11-28 11-45-40](https://user-images.githubusercontent.com/9441791/69783131-ac51c380-11d4-11ea-874a-c622a361491b.png)

Is it right behavior? 
I would like to receive only one message for one topic, no matter how many times a subscription to updates is called.

**Comment by dunglas** [comment]
Are you sure that you close the first EventSource connection? Can you take a screenshot of what happens in DevTools's network panel?

**Comment by zserg84** [comment]
Thank you for your answer.
You're right/ Old connection was not closed.
