### ISSUE TITLE
raspberry PI 4 Mercure ARMv6

### ISSUE THREAD

**Issue by GRUXXKi** [dunglas/mercure#221]
Hello,

I've build an app that run with Symfony and mercure. I need to make it works on Pi for internal application.

I've made one with a previous version of mercure and got no problem. Obiously no problem either while developping the app on Linux PC.

But when running it on Pi got that on publish :

INFO[1269] runtime error: invalid memory address or nil pointer dereference

**Comment by GRUXXKi** [comment]
Just to complete, I've installed the 7.2 version and it works properly.

**Comment by dunglas** [comment]
You mean if only affects the 0.8 branch? I don't own a Raspberry PI 4, could you try to run the test suite on this platform? Did you try to set the `DEBUG` env var to 1 to see if there is a stack trace?

**Comment by GRUXXKi** [comment]
Yes only for the 0.8 branch. I'm not sure how I can run the test suite on the platform but if you give me the process I will. 

I did not set the DEBUG env var, but will try that as soon as possible.

**Comment by dunglas** [comment]
Here is the process to run the test suite: https://github.com/dunglas/mercure/blob/master/CONTRIBUTING.md#hub
