### ISSUE TITLE
Account creation on ACMEv1 is disabled (HTTPS, SSL, ACMEv2)

### ISSUE THREAD

**Issue by stas3on** [dunglas/mercure#223]
Hello, I tried to setup working HTTPS mercure for several days, but nothing works for me.
**Last configuration on Debian 9**

**Dockerfile** (https://github.com/Richard87/mercure/blob/d8269b5a475b67d32fc4d12ecf635a692af5c6e9/Dockerfile)
```
# First stage: build the app
FROM golang:1 as build

ENV GO111MODULE on
WORKDIR /go/src/app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

COPY ./ .

RUN go get -v
RUN CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
RUN chmod +x ./mercure

# Build the actual image
FROM scratch
COPY --from=build /go/src/app/mercure .
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY public ./public/
COPY fixtures ./fixtures/
CMD ["./mercure"]
EXPOSE 80 443
```

**.env**
```
ACME_HOSTS=localhost.example.com
ADDR=:3000
ALLOW_ANONYMOUS=1
DEBUG=1
DEMO=1
JWT_KEY='test'
LOG_FORMAT=JSON
PUBLISH_ALLOWED_ORIGINS=https://localhost.example.com:3000
ALLOW_ANONYMOUS=1
```

**/etc/hosts**
```127.0.0.1 localhost.example.com```

**Build docker**
```docker build -t app .```

**Run docker**
```
docker run --env-file .env -p 3000:3000 app:latest
{"addr":":3000","level":"info","msg":"Mercure started","protocol":"https","time":"2019-12-17T11:52:18Z"}
```

**Send CURL**
```
curl 'https://localhost.example.com:3000/.well-known/mercure'
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Got error in docker**
```2019/12/17 11:52:24 http: TLS handshake error from 172.17.0.1:60794: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.```

Please help me. What I need to do to get working HTTPS mercure?

**Comment by stas3on** [comment]
@Richard87

**Comment by Richard87** [comment]
My fork is out of date, so I would recommend using the proper one, that might solve your problem :) 

https://github.com/dunglas/mercure/blob/master/Dockerfile

(I have not tested the latest release, and the Dockerfile only builds the image, it doesn't compile Mercure Hub)

**Comment by stas3on** [comment]
> My fork is out of date, so I would recommend using the proper one, that might solve your problem :)
> 
> https://github.com/dunglas/mercure/blob/master/Dockerfile
> 
> (I have not tested the latest release, and the Dockerfile only builds the image, it doesn't compile Mercure Hub)

```
Sending build context to Docker daemon  7.847MB
Step 1/5 : FROM gcr.io/distroless/static
 ---> e4d2a899b1bf
Step 2/5 : COPY mercure /
COPY failed: stat /var/lib/docker/tmp/docker-builder569196793/mercure: no such file or directory
```

**Comment by stas3on** [comment]
Attempt with docker from https://github.com/dunglas/mercure/releases

**.envdocker**
```
ACME_HOSTS=localhost.example.com
ADDR=:3000
ALLOW_ANONYMOUS=1
DEBUG=1
DEMO=1
JWT_KEY='test'
LOG_FORMAT=JSON
PUBLISH_ALLOWED_ORIGINS=https://localhost.example.com:3000
ALLOW_ANONYMOUS=1
```

**Build & run**
```
docker pull dunglas/mercure:latest
docker run --env-file .envdocker -p 3000:3000 dunglas/mercure:latest
time="2019-12-17T17:02:58Z" level=info msg="Mercure started" addr=":3000" protocol=https
```

**curl**
```
curl 'https://localhost.example.com:3000/.well-known/mercure'
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Error in docker**
`2019/12/17 17:03:06 http: TLS handshake error from 172.17.0.1:14180: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/1781730325" for domain "localhost.example.com": no viable challenge type found`

**Comment by stas3on** [comment]
@dunglas please, help

**Comment by dunglas** [comment]
I don't understand why you try to build a new image? The existing one supports HTTPS and Acme.

**Comment by stas3on** [comment]
Because it don't work for me too.

**/etc/hosts**
`127.0.0.1 localhost.example.com`

**Attempt 1**

```
server {
    listen 80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name socket.mydomain.com;

    ssl_certificate "/etc/letsencrypt/archive/socket.mydomain.com/fullchain1.pem";
    ssl_certificate_key "/etc/letsencrypt/archive/socket.mydomain.com/privkey1.pem";

    location / {
        proxy_pass https://localhost.example.com:3000/.well-known/mercure;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Access-Control-Allow-Origin $http_origin;
    }
}
```

```
docker run \
-p 3000:3000/tcp \
--restart=always \
-e 'JWT_KEY=test' \
-e 'ADDR=:3000' \
-e 'ACME_HOSTS=socket.mydomain.com' \
-e 'ACME_CERT_DIR=/certs' \
-e 'DEBUG=1' \
-e 'PUBLISH_ALLOWED_ORIGINS=https://localhost.example.com:3000' \
-e 'USE_FORWARDED_HEADERS=1' \
dunglas/mercure:latest
time="2019-12-24T19:55:05Z" level=info msg="Mercure started" addr=":3000" protocol=https
```

`curl 'https://socket.mydomain.com'`

`2019/12/24 19:55:38 http: TLS handshake error from 172.17.0.1:59832: acme/autocert: missing server name`


**Attempt 2**
```
docker run \
-p 3000:3000/tcp \
--restart=always \
-e 'JWT_KEY=test' \
-e 'ADDR=:3000' \
-e 'ACME_HOSTS=localhost.example.com' \
-e 'ACME_CERT_DIR=/certs' \
-e 'DEBUG=1' \
-e 'PUBLISH_ALLOWED_ORIGINS=https://localhost.example.com:3000' \
-e 'USE_FORWARDED_HEADERS=1' \
dunglas/mercure:latest
```

`time="2019-12-24T18:58:21Z" level=info msg="Mercure started" addr=":3000" protocol=https`

`curl 'https://localhost.example.com:3000'`

`2019/12/24 18:58:40 http: TLS handshake error from 172.17.0.1:56734: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/1908453201" for domain "localhost.example.com": no viable challenge type found`

**Comment by stas3on** [comment]
@dunglas Kevin, please help

**Comment by thehatami** [comment]
i think HTTPS is a real problem on production mode. every thing is work on http but after switching to https, server not receive any thing or return <nil> and i cant find any solution. i have a dedicated server for hub and try varoius param with these command but nothing work.

`sudo ./mercure --jwt-key="*" --acme-hosts="example.com"`
