### ISSUE TITLE
How can I get Mercure server working with custom certificates and docker?

### ISSUE THREAD

**Issue by JoergSommer** [dunglas/mercure#225]
Hi!

I installed the mercure server by docker and with http it works fine. Now I have to change to https and get an SSL error with both, publishing and subscribing.

I tought the certificate is generated automatically with letsencrypt, but it seems to do not working.

So I tried to give working certificates to the server with CERT_FILE and KEY_FILE like:

```
docker run -itd --name mercure \
                  -e JWT_KEY='my secret key)' \
                  -e ACME_HOSTS='(my domain)' \
                  -e CERT_FILE='/etc/letsencrypt/live/(my domain)/cert.pem' \
                  -e KEY_FILE='/etc/letsencrypt/live/(my domain)/privkey.pem' \
                  -p 8080:80 -p 4430:443 \
                  (mercure-image)
```

But I get an error:
FATA[0000] open /etc/letsencrypt/live/(my domain)/cert.pem: no such file or directory

But the file is there!

I guess I have to copy the certificates to the docker image but this is not so easy because there is no shell etc.

Thx for help!

**Comment by dunglas** [comment]
Does this file exist? It must be in the container. To share a file between the host and a container, use a volume.

**Comment by JoergSommer** [comment]
Ok, I will try. I tried mounts of type bound. Did not get them working.
Volumes are not so nice because letsencript (i use too) has to update the certificates every quarter of a year. But I can use a cron job for this...
