### ISSUE TITLE
A question on performance

### ISSUE THREAD

**Issue by iluuu1994** [dunglas/mercure#229]
We're planning to use Mercure for an event with ~3000 attendees. We'll have to push data to all users in real-time. The data pushed to the clients is small and personalized. What I'm wondering is what is the better approach:

* Push all data (~600 KB) to all clients simultaneously
* Push the data of one user (~200 bytes) to 3000 clients individually

One thing I've observed is that publishing 3000 times on my local machine takes a significant amount of time (~1 minute), even with an empty payload. Pushing all data (600 KB, but only to 1 device) only takes only 0.5s. However I'm not sure if these tests are even remotely accurate. I was hoping to get some advice from someone who is experienced in running Mercure in production. Excuse me if this has been answered before.

Thanks again!

**Comment by dunglas** [comment]
Are you pushing (making the POST requests) in parallel? Honestly I don't know which strategy would be faster. I've the feeling that pushing multiple times will perform a bit better, but I'm not sure, it deserves a proper test. Maybe that the load test can be adapted to measure this: https://github.com/dunglas/mercure/blob/master/LoadTest.scala

**Comment by iluuu1994** [comment]
Thanks for your feedback. I went with sending all data at once to all clients. The event was canceled because of COVID-19 so unfortunately I never found out if that was the right decision. Maybe next year 🙂
