### ISSUE TITLE
How to deal with 401 Errors with the JS client?

### ISSUE THREAD

**Issue by JoergSommer** [dunglas/mercure#230]
Hi!

What ever I do, I get an 401 Unauthorized if I try to connect the Mercure hub by a JS client. Everything else is working. The hub runs on dev.example.com:20000. I can send updates to it by the backend with a generated JWT that is based on my secret key. I run the hub by docker. Start script is:
`docker run -itd --name mercure-dev -e JWT_KEY='Hello' -p 19101:443 -e CERT_FILE='/certificates-dev/fullchain.pem' -e KEY_FILE='/certificates-dev/privkey.pem' -e CORS_ALLOWED_ORIGINS=https://dev.example.com server-mercure-dev`

server-mercure-dev is a 1:1 of your image + certificates.

I tried it out with secret: Hallo
I build a JWT with publish and subscribe with *

JS script, I use:
```
        $(function () {
            document.cookie = "mercureAuthorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.foAa0rerWaTHJqDjXqXbXdSwCHwbSGuzF7BIe09otUI; path=/; Secure; domain=.example.com; HttpOnly; SameSite=strict";
            const eventSource = new EventSource('https://dev.example.com/.well-known/mercure?topic=<my topic uri>'));

            eventSource.onmessage = event => {
                update();
            }
        });
```
What ever of combination I tried for the cookie, it does not work. With/without SameSite, with/without HttpOnly, etc. And I try to variate path and domain. If I set HttpOnly, there is no cookie (why?). All other combinations lead to a 401.

If i use:
`-e ALLOW_ANONYMOUS=1`
everything works fine.

If I use DEBUG = 1 I can not see any differences in the error log of the hub nor in the response.

Configuration of my JWT:
`{
  "alg": "HS256",
  "typ": "JWT"
}
{
  "mercure": {
    "publish": [
      "*"
    ],
    "subscribe": [
      "*"
    ]
  }
}
`

Questions:
Do I use the right key for mercureAuthorization? I used the JWT but in the manual you write JWS?
Why DEBUG makes no difference?
How can it be that publishing works greate and subscribing does not (with the same JWT).
How can I get better error messages?
Do I have to use publish only in publisher JWT and subscribe only in subscriber JWT?

**Comment by pgedzba** [comment]
You have to use some EventSource polyfills which supports authorization, default one doesn't

**Comment by alxndrbauer** [comment]
@pgedzba the documentation says that you only need the pollyfill if you use the authorization header.

**Comment by CreaDEV** [comment]
I thought I need the polyfills if i want to use header. If i use cookies for auth, it's not needed
