### ISSUE TITLE
Can't get multiple hubs to be launched on the same server

### ISSUE THREAD

**Issue by mikaelcom** [dunglas/mercure#234]
Hi, thanks for your work!

I used `supervisor` at first as advised but I faced an issue that encouraged me to use `systemd` in order to remove a layer of management in hope to make it work as wanted. Sadly, the same issue is here and I don't know if I'm mistaken or if it is a limitation from the mercure bin.

Concretely, I have two environments on the same server, two domains with each a proper SSL certificate and JWT settings.

The prod systemd service file is:
```bash
[Unit]
Description=Project [PROD] - Mercure

[Service]
Environment="PUBLISHER_JWT_KEY=PROD" "SUBSCRIBER_JWT_KEY=PROD"
ExecStart=/home/project/public_html/platform/prod/shared/bin/mercure --addr=:3333 --cert-file=/home/project/domains/pubsub.project.fr/ssl.cert  --cors-allowed-origins=https://project.fr --key-file=/home/project/domains/pubsub.project.fr/ssl.key --publish-allowed-origins=https://project.fr --allow-anonymous=0 --debug=1
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

The dev systemd service file is:
```bash
[Unit]
Description=Project [DEV] - Mercure

[Service]
Environment="PUBLISHER_JWT_KEY=DEV" "SUBSCRIBER_JWT_KEY=DEV"
ExecStart=/home/project/domains/dev.project.fr/public_html/platform/dev/shared/bin/mercure --addr=:3334 --cert-file=/home/project/domains/pubsub.dev.project.fr/ssl.cert  --cors-allowed-origins=https://dev.project.fr --key-file=/home/project/domains/pubsub.dev.project.fr/ssl.key --publish-allowed-origins=https://dev.project.fr --allow-anonymous=0 --debug=1
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

Currently, only the first one service to be launched, using `systemctl start project-[dev|prod].service`, displays the debug message such as:
```text
systemd[1]: Started Project [PROD] - Mercure.
mercure[28677]: time="2020-02-06T14:14:49+01:00" level=info msg="Mercure started" addr=":3333" protocol=https
time="2020-02-06T14:15:05+01:00" level=info msg="New subscriber" remote_addr="[::1]:56688" subscriber_topics="[notification_ba4999cd82e551fafaa0567cd8a0c85a]" target="[]"
```
The second service only displays:
```text
systemd[1]: Started Project [DEV] - Mercure.
```

When using `htop` I can see the two processes running respectively on ports `3333` (PROD) and `3334` (DEV) but the second one is not reachable by the client. If I use a basic test from command line (very basic test ;)), I get this:
```bash
$ # dev
$ curl localhost:3334
curl: (7) Failed connect to localhost:3334; Connexion refusée
$ # prod
$ curl localhost:3333
Client sent an HTTP request to an HTTPS server.
```

Any idea? Any lead? Need any additional details? 
Thanks

**Comment by stephanvierkant** [comment]
Same problem  here, but using Supervisor.

```
[program:mercure_foo_example.com]
environment=JWT_KEY="foobar", CORS_ALLOWED_ORIGINS="https://foo.example.com", PUBLISH_ALLOWED_ORIGINS="*"
command=/home/ubuntu/mercure --addr ":3000"
process_name=%(program_name)s
numprocs=1

[program:mercure_bar_example.com]
environment=JWT_KEY="foobar", CORS_ALLOWED_ORIGINS="https://bar.example.com", PUBLISH_ALLOWED_ORIGINS="*"
command=/home/ubuntu/mercure --addr ":3001"
process_name=%(program_name)s
numprocs=1
```
I can see `/home/ubuntu/mercure --addr :3000` and `/home/ubuntu/mercure --addr :3001` in `service supervisor status`, so both processes are started. But the second process hangs until the first is terminated.

```
$ sudo supervisorctl -i
mercure_bar_example.com            RUNNING   pid 20788, uptime 0:03:23
mercure_foo_example.com            RUNNING   pid 20772, uptime 0:03:23
```

**Comment by stephanvierkant** [comment]
I had the same problem and thanks to @dunglas I've found the solution. You can't have multiple instances using one database, so you should use `--transport-url` (or `TRANSPORT_URL` env variable) to point to another database.

Maybe we should add this to the documentation?
