### ISSUE TITLE
[enhancement] Prometheus metrics endpoint

### ISSUE THREAD

**Issue by dvc** [dunglas/mercure#242]
It is strongly needed in production to monitor service state and statistics.

Health check is minimum.

But more stats is better :) 

For example:

- service version, 
- start time (to calculate uptime), 
- memory
- cpu
- disk_size/history_size/history_max
- connections count, 
- messages rate, 
- errors rate, 
- pub/sub auth errors rate
- ...

Any format is good. May be Prometheus? :)

**Comment by dunglas** [comment]
👍 for Prometheus!

**Comment by jdecool** [comment]
Some metrics has been added by #251, #265, #276 & #287

**Comment by MinDBreaK** [comment]
Would it be possible to disable authentication on the metrics endpoint ? 

When you are using annotation-based scraping in Kubernetes, you cannot set basic auth, and you have to set it globally in Prometheus, which would probably conflict if you have some services that check authorization even if not mandatory. Or if multiple teams use the same cluster.

Maybe a source check or a dedicated endpoint could be used, like Traefik does ?

**Comment by jdecool** [comment]
> Would it be possible to disable authentication on the metrics endpoint ?

Authentication on metrics endpoint is not mandatory. If you don't set a login or password the authentication is not enabled.

Isn't that enough ?

If you disable the authentication on metrics endpoint, you could set the security configuration in Kubernetes ?

**Comment by MinDBreaK** [comment]
Actually I though because of the configuration of the Helm Chart that generate credentials, so I though It was mandatory.

Yes, I could set the security configuration from kubernetes by disabling the access to the path. 
However, I think a dedicated port could be a nice to ease the configuration. But that would only be a nice to have. 

Thanks for the answer, I'll just for now update the helm chart !

**Comment by sagikazarmark** [comment]
I agree, exposing the metrics endpoint on a different port is a best practice in the kubernetes world. Then the whole authentication thing becomes unnecessary in the first place.

**Comment by dunglas** [comment]
Pull request welcome! But please keep authentication support, it can be helpful outside of the k8s world.

**Comment by sagikazarmark** [comment]
Can we make that explicit (eg. an enabled/disabled flag)? Implicitly enabling features is generally not a good idea IMHO. The default generated values of the Helm chart is a great example why.

**Comment by sagikazarmark** [comment]
Bump, there is a PR.
