### ISSUE TITLE
Published event not arriving

### ISSUE THREAD

**Issue by thorau** [dunglas/mercure#243]
Hi,

I am publishing multiple events in a short range of time.
The last event is never arriving at the Client (EventSource).

For the last message there is "Update published" but no "Event sent":

This last message did not arrive.
```
time="2020-03-04T15:06:11+01:00" level=info msg="Update published" event_id=da2b3ee4-9b69-4e22-a01a-1aa2c80f7c41 event_retry=0 event_type= remote_addr="127.0.0.1:39964" update_targets="[]" update_topics="[https://....]"
```
This messages before all arrived
```
time="2020-03-04T15:06:10+01:00" level=info msg="Event sent" event_id=3b26b259-9bd8-4580-94f4-cf2c88358cf0 event_retry=0 event_type= last_event_id= remote_addr="127.0.0.1:39928" subscriber_targets="[]" subscriber_topics="[https://....]" update_targets="[]" update_topics="[https://....]"

time="2020-03-04T15:06:10+01:00" level=info msg="Update published" event_id=3b26b259-9bd8-4580-94f4-cf2c88358cf0 event_retry=0 event_type= remote_addr="127.0.0.1:39962" update_targets="[]" update_topics="[https://....]"
```
What could be the reason for the hub not sending the last event?

**Comment by thorau** [comment]
Is there maybe a limit for the publishing frequency?
Does the hub ignore multiple messages at the same second?

**Comment by dunglas** [comment]
Not there are no limits. You're maybe hitting a bug, it needs to be debugged.
