### ISSUE TITLE
Subscription events not working?

### ISSUE THREAD

**Issue by tsdevelopment** [dunglas/mercure#247]
Hi @dunglas ,

thank you for your update so we can use subscription events. I cloned the branch and built the hub so I can use the functionality but it seems not to work. Whenever I subscribe the following event:

```
https://mercure.rocks/targets/subscriptions
```
I never get a ```subscription``` event as you wrote in the documentation. I also added several log outputs to be sure that the specific code will be called. And yes, it is called. But I never get the message back to my application.

Here is what I use:

```javascript
var url = new URL('my-hub-url');
url.searchParams.append('topic', 'https://mercure.rocks/targets/subscriptions');

var eventSource = new EventSourcePolyfill(url);
eventSource.onmessage = this.onMessage.bind(this);
eventSource.onerror = this.onError.bind(this);
eventSource.onopen = this.onOpen.bind(this);

// Example message method (works in my application) but is never 
// called when a new user connects
onMessage: function(e) {
    console.log({ e });
}
```

The `onMessage` -method is called when I send updates to the hub. But never when a new user connects to the hub. Maybe I am doing something wrong and you can provide me a tip? Or isn't it implemented completely?

**Comment by monstrum** [comment]
You are missing the JWT Token,
make sure your token contains your subscription topic.
Your token look like this using "!ChangeMe!" as secret:
`
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJodHRwczovL21lcmN1cmUucm9ja3MvdGFyZ2V0cy9zdWJzY3JpcHRpb25zIl19fQ.uOGeOiEPeYGa3Iah4ij8AAOjl_hRwY3VfpyAR70gW0o
`
The payload look like this
`
{
  "mercure": {
    "subscribe": [
      "https://mercure.rocks/targets/subscriptions"
    ]
  }
}
`
And update your code using the token like this. It should work. There are two auth methods, either using cookie or bearer token. Default event source doesn't support headers as I know currently. By using Event source polyfill, it is support headers.
`
var eventSource = new EventSourcePolyfill(
   url,
   {headers: {Authorization: `Bearer ${JWT_TOKEN}`}}
);
`

**Comment by tsdevelopment** [comment]
Thanks for your reply. I already use token authentication. My code above was not complete, only a few snippets:

```javascript
var eventSource = new EventSourcePolyfill(url, {
    headers: {Authorization: mercureToken},
});
```
The payload for my token looks like this:

```
{
  "mercure": {
    "subscribe": ["*"]
  }
}
```
Messaging works, only subscriptions don't work.

**Comment by monstrum** [comment]
I think I misunderstood your questions. You mean the connected and disconnected event from other user, which on commit https://github.com/dunglas/mercure/commit/94f8813749db9fa7caa7c661a96ec2a13b707a11?

Maybe it is because of this?
``` 
The topic of this update **MUST** follow the pattern
"https://mercure.rocks/subscriptions/{topic}/{subscriptionID}" where "topic" is the URL-encoded
value of the subscribed topic and "subscriptionID" is an unique identifier for this subscription.
"subscriptionID" **MAY** be a UUID [@RFC4122].
```

**Comment by tsdevelopment** [comment]
Yes, exactly. I understood that whenever a user connects an event will be published.

```
In order to only allow authorized subscribers to receive subscription events, the subscription update MUST be marked as intended for subscribers providing the following targets:

the fixed value https://mercure.rocks/targets/subscriptions

a URL following the pattern https://mercure.rocks/targets/subscriptions/{topic} where topic is the URL-encoded value of the subscribed topic
```
That's why I want to subscribe to `https://mercure.rocks/targets/subscriptions` - I think I missunderstood anything?

**Comment by dunglas** [comment]
@tsdevelopment are you using the development version? This feature is not available in the stable version yet.

**Comment by tsdevelopment** [comment]
> @tsdevelopment are you using the development version? This feature is not available in the stable version yet.

Yes, I checked out the master branch and build the application to use the latest features.

**Comment by stefanpoensgen** [comment]
i would appreciate to see a working example. i'm trying to realise an online/offline status of users.

**Comment by dunglas** [comment]
Here is an example: https://github.com/dunglas/mercure/blob/94f8813749db9fa7caa7c661a96ec2a13b707a11/hub/subscribe_test.go#L348-L349

We must add it to the documentation (help doing this is very welcome :)).

**Comment by dunglas** [comment]
Ok I got the problem. `https://mercure.rocks/targets/subscriptions` is the target IRI that must be in the JWT token provided to the Mercure hub. Wat you want to subscribe to is `https://mercure.rocks/subscriptions/{topic}/{connectionID}`. Update your code like this:

```js
var url = new URL('my-hub-url');
url.searchParams.append('topic', 'https://mercure.rocks/targets/subscriptions');
// ...
```

Also, double check that the JWT is properly send to the Hub and contains the appropriate target.

**Comment by tsdevelopment** [comment]
Thanks for your reply, but I don't get it working anyway. Here is exactly what I use:

```bash
# Token:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9pcGJvYXJkLnRlc3QiLCJtZW1iZXJfaWQiOjEsIm1lcmN1cmUiOnsic3Vic2NyaWJlIjpbIioiLCJodHRwczpcL1wvbWVyY3VyZS5yb2Nrc1wvdGFyZ2V0c1wvc3Vic2NyaXB0aW9ucyJdLCJwdWJsaXNoIjpbIioiLCJodHRwczpcL1wvbWVyY3VyZS5yb2Nrc1wvdGFyZ2V0c1wvc3Vic2NyaXB0aW9ucyJdfX0.lXDAackoaZVMktlnNKBCXFJQKMPjaBiqp63WTPtldp0
```

```bash
# Key:
!ChangeMe!
```

```bash
# Starting hub (latest master) as follows:
./mercure --jwt-key='!ChangeMe!' --addr='localhost:3000' --allow-anonymous --cors-allowed-origins='*'
```

```javascript
// Connect to hub
var mercureToken = 'Bearer ' + token;
var url = new URL('http://127.0.0.1:3000/.well-known/mercure');
url.searchParams.append('topic', 'https://mercure.rocks/subscriptions/{topic}/{connectionID}');

// Create event source and connect to hub
var eventSource = new EventSourcePolyfill(url, {
    headers: {
        Authorization: mercureToken,
    },
});

// This never will be called when another connection is established
// What exactly is wrong here?
eventSource.onmessage = function(e) {
    console.log({ e });
}

eventSource.onopen = function(e) {
    console.log({ e });
}
```

I don't know what is wrong. The connection looks good, the token includes the subscriptions you mentioned.

<img width="1427" alt="Connection image" src="https://user-images.githubusercontent.com/4952908/78475501-799c7680-7744-11ea-8b65-bdd4a9d89fb9.png">

Messaging works, but no connection events.

**Comment by tsdevelopment** [comment]
Okay, i was a little bit too fast. After adding `--dispatch-subscriptions` to the starting command of the hub it is working! Thanks for your patience! Maybe we should provide my example above.

**Comment by grago** [comment]
Hi, i'm not being able to make this work, is this supposed to work on the 0.9.0 binary release? 

I'm using the exact example from @tsdevelopment 

Thanks!

**Comment by grago** [comment]
Ok, i got it working. Had to build from the latest source in order to get the targets in the updates.

**Comment by BonBonSlick** [comment]
What a messed up docs, loosing so much time to do such a simple stuff, while the package should make it easier.
Nothing works

 ```
 // const subscribingUrl = new URL(`${mercureSubscribersUrl}${activeRoom}`);
  const subscribingUrl = new URL(mercureUrl);
  // console.trace({subscribingUrl});
  // const subscribingUrl = new URL(mercureSubscribersUrl);
  // const subscriptionsPath = `/.well-known/mercure/subscriptions/${activeRoom}/{chat}`;
  // const subscriptionsPath = `${mercureSubscribersUrl}${activeRoom}`;
  // const subscriptionsPath = `chat/${activeRoom}`;
  // const subscriptionsPath = `${activeRoom}`;
  // nothing works as expected
  // const subscriptionsPath = `/.well-known/mercure/subscriptions/${activeRoom}/${activeRoom}`;
  // const subscriptionsPath = `/.well-known/mercure/subscriptions/${activeRoom}/${makeid(12)}`;
  // const subscriptionsPath = `/.well-known/mercure/subscriptions/chat/${activeRoom}`;
  // const subscriptionsPath = `/.well-known/mercure/?topic={/.well-known/mercure/subscriptions/chat/${activeRoom}}`;
  // const subscriptionsPath = `https://symfchat.loc/.well-known/mercure/subscriptions/chat/${activeRoom}`;
  // const subscriptionsPath = `https://symfchat.loc:3000/.well-known/mercure/subscriptions/chat/${activeRoom}`;
  const subscriptionsPath = `${mercureSubscribersUrl}/chat/${activeRoom}`;
  // const subscriptionsPath = encodeURI(`/.well-known/mercure/?topic={/.well-known/mercure/subscriptions/chat/${activeRoom}}`);
  // const subscriptionsPath = `/.well-known/mercure/subscriptions/${activeRoom}/${activeUser.username}`;
  // subscribingUrl.searchParams.append("topic", subscriptionsPath);
  // subscribingUrl.searchParams.append("topic", encodeURI(subscriptionsPath));
  subscribingUrl.searchParams.append('topic', `https://mercure.rocks/subscriptions/{${activeRoom}}`);

```

**Comment by BonBonSlick** [comment]
> Okay, i was a little bit too fast. After adding `--dispatch-subscriptions` to the starting command of the hub it is working! Thanks for your patience! Maybe we should provide my example above.

nope
```

onbon@bonbon:~$ sudo systemctl status mercure.service 
● mercure.service - Mercure service
   Loaded: loaded (/etc/systemd/system/mercure.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Mar 02 14:06:41 bonbon systemd[1]: mercure.service: Main process exited, code=killed, status=15/TERM
Mar 02 14:06:41 bonbon systemd[1]: mercure.service: Succeeded.
Mar 02 14:06:41 bonbon systemd[1]: Stopped Mercure service.
Mar 02 14:06:41 bonbon systemd[1]: Started Mercure service.
Mar 02 14:06:41 bonbon mercure[15714]: 2021/03/02 14:06:41 /!\ This Mercure binary is deprecated, use the binary based on Caddy Server instead! See https://mercure.rocks/docs/UPGRADE
Mar 02 14:06:41 bonbon mercure[15714]: {"level":"info","ts":1614686801.4598558,"caller":"mercure/handler.go:123","msg":"Mercure started","protocol":"https","addr":":3000"}
Mar 02 14:06:51 bonbon systemd[1]: Stopping Mercure service...
Mar 02 14:06:51 bonbon systemd[1]: mercure.service: Main process exited, code=killed, status=15/TERM
Mar 02 14:06:51 bonbon systemd[1]: mercure.service: Succeeded.
Mar 02 14:06:51 bonbon systemd[1]: Stopped Mercure service.
bonbon@bonbon:~$ sudo systemctl restart mercure.service 
bonbon@bonbon:~$ sudo systemctl status mercure.service 
● mercure.service - Mercure service
   Loaded: loaded (/etc/systemd/system/mercure.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-03-02 14:07:25 EET; 1s ago
  Process: 15751 ExecStart=/var/www/symf-chat/mercure --addr=:3000 --subscriptions --dispatch-subscriptions --allow-anonymous --cors-allowed-origins=https://symfchat.loc --publish-allowed-origins=* (code=exited,
 Main PID: 15751 (code=exited, status=2)

```

**Comment by BonBonSlick** [comment]
> Ok, i got it working. Had to build from the latest source in order to get the targets in the updates.

Also nope, after upgrading to latest 0.11 binary got error
```

bonbon@bonbon:~$ sudo systemctl status mercure.service 
● mercure.service - Mercure service
   Loaded: loaded (/etc/systemd/system/mercure.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-03-02 14:27:55 EET; 2s ago
  Process: 18172 ExecStart=/var/www/symf-chat/mercure --addr=:3000 --subscriptions --allow-anonymous --cors-allowed-origins=https://symfchat.loc --publish-allowed-origins=* (code=exited, status=1/FAILURE)
 Main PID: 18172 (code=exited, status=1/FAILURE)

```

**Comment by BonBonSlick** [comment]
Well, seems package is dead, I would not recommend to use it.

**Comment by divine** [comment]
> Well, seems package is dead, I would not recommend to use it.

@BonBonSlick welcome to the open-source world!

If you can't fix it yourself **be kind** and patiently wait for the reply whenever the maintainer will have a look at this.

Being toxic won't help here, this isn't upwork where you get paid for this type of work. /end.

Thanks!

**Comment by dunglas** [comment]
Yes, this should work as expected.

**Comment by abda11ah** [comment]
Hi, i also don't understand why the documentation says that the "@context" should be a fixed value "https://mercure.rocks/". Please explain about this. Does mercure.rocks is a free public server or should we use https://our-domain instead ?

**Comment by dunglas** [comment]
This URL serves a JSON-LD context when the `Accept` header is set to `application/ld+json`. You can copy this context file on your own server if you need.
