### ISSUE TITLE
Invalid header response ?

### ISSUE THREAD

**Issue by remyg4g** [dunglas/mercure#253]
Hi everyone,

We tried to use mercure 0.9.0 (from 0.5.1) in production last week-end and we ran into one (giant ?) problem.
When the traffic is very high, some timeout error occurs which is normal, but all these errors seems to have invalid header response. The one we saw in the console was 
```
Access to resource at 'https://mercure.glory4gamers.com/.well-known/mercure' from origin 'https://beta.glory4gamers.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Which was very odd considering the service worked very well before these errors occured and the CORS policy were set long ago and work fine. We are using mercure on AWS, using elasticbeanstalk and the `CORS_ALLOWED_ORIGINS` option is set to *
<img width="984" alt="Capture d’écran 2020-04-14 à 10 35 04" src="https://user-images.githubusercontent.com/35451045/79203645-9e2ad980-7e3b-11ea-98f4-f71213477b84.png">

**Comment by dunglas** [comment]
Hi,

Could you share the logs emitted by the Mercure Hub? If the hub is not able to serve the response, it looks "normal" to me that headers aren't generated either.

By the way, using `*` is usually discouraged. To improve the security, you should whitelist only the origins allowed to connect to the Mercure hub.

**Comment by JSmythSSG** [comment]
Did you get this working? I've just moved over from the legacy to the new Caddy version and getting the same
`has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by JSmythSSG** [comment]
> Hi,
> 
> Could you share the logs emitted by the Mercure Hub? If the hub is not able to serve the response, it looks "normal" to me that headers aren't generated either.
> 
> By the way, using `*` is usually discouraged. To improve the security, you should whitelist only the origins allowed to connect to the Mercure hub.

`{"level":"info","ts":1610116467.3811321,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"188.114.110.34:29984","proto":"HTTP/1.1","method":"GET","host":"XXXXXXXXX:8443","uri":"/.well-known/mercure?topic=https%3A%2F%2FXXXXXXXXX%2Fv1%2Fmanage%2Fcontacts%2F4311","headers":{"Cf-Request-Id":["078404a26b0000ff6867993000000001"],"Cdn-Loop":["cloudflare"],"Origin":["https://192.168.1.170"],"Referer":["https://192.168.1.170/"],"Accept-Language":["en-GB,en-US;q=0.9,en;q=0.8,nl;q=0.7"],"Sec-Fetch-Site":["cross-site"],"Cf-Connecting-Ip":["86.134.113.95"],"X-Forwarded-Proto":["https"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Accept":["text/event-stream"],"Cache-Control":["no-cache"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Dest":["empty"],"Connection":["Keep-Alive"],"Accept-Encoding":["gzip"],"X-Forwarded-For":["86.134.113.95"],"Cf-Ipcountry":["GB"],"Cf-Ray":["60e6a3b0ad41ff68-MAD"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"","proto_mutual":true,"server_name":"XXXXXXXXX"}},"common_log":"188.114.110.34 - - [08/Jan/2021:14:34:27 +0000] \"GET /.well-known/mercure?topic=https%3A%2F%2FXXXXXXXXX%2Fv1%2Fmanage%2Fcontacts%2F4311 HTTP/1.1\" 0 0","duration":0.00000684,"size":0,"status":0,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3-32=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"]}}
 `
