### ISSUE TITLE
Multiple subscribers limit

### ISSUE THREAD

**Issue by smokezp** [dunglas/mercure#254]
Hi, I have issue with multiple subscribers. Somehow mercure lost(or disconnect) other subscribers. It seems like mercure has limit 6 for subscribers. How can I increase this limit?
All other eventsources have status pending.

Here is log:

- INFO[0000] Mercure started                               addr="localhost:3000" protocol=http
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46688" subscriber_topics="[job.18]"
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46692" subscriber_topics="[job.17]"
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46696" subscriber_topics="[job.19]"
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46700" subscriber_topics="[job.20]"
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46704" subscriber_topics="[job.21]"
INFO[0000] New subscriber                                remote_addr="127.0.0.1:46708" subscriber_topics="[job.22]"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46708" subscriber_topics="[job.22]"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46688" subscriber_topics="[job.18]"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46692" subscriber_topics="[job.17]"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.22 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.17 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.18 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46798" subscriber_topics="[job.16]"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46794" subscriber_topics="[job.23]"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.20 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.21 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
127.0.0.1 - - [14/Apr/2020:17:53:28 +0300] "GET /.well-known/mercure?topic=job.19 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46700" subscriber_topics="[job.20]"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46704" subscriber_topics="[job.21]"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46814" subscriber_topics="[job.12]"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46802" subscriber_topics="[job.15]"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46806" subscriber_topics="[job.14]"
INFO[0008] New subscriber                                remote_addr="127.0.0.1:46810" subscriber_topics="[job.13]"
INFO[0008] Subscriber disconnected                       remote_addr="127.0.0.1:46696" subscriber_topics="[job.19]"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46802" subscriber_topics="[job.15]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.15 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46798" subscriber_topics="[job.16]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.16 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46814" subscriber_topics="[job.12]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.12 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46794" subscriber_topics="[job.23]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.23 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46810" subscriber_topics="[job.13]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.13 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] Subscriber disconnected                       remote_addr="127.0.0.1:46806" subscriber_topics="[job.14]"
127.0.0.1 - - [14/Apr/2020:17:53:37 +0300] "GET /.well-known/mercure?topic=job.14 HTTP/1.1" 200 2 "http://apapi.loc:7000/admin/?entity=Job&action=list&menuIndex=6&submenuIndex=0&sortField=id&sortDirection=DESC&page=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47126" subscriber_topics="[job.23]"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47138" subscriber_topics="[job.20]"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47134" subscriber_topics="[job.21]"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47130" subscriber_topics="[job.22]"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47142" subscriber_topics="[job.19]"
INFO[0013] New subscriber                                remote_addr="127.0.0.1:47146" subscriber_topics="[job.18]"

**Comment by smokezp** [comment]
Also I have issue with the same multiple subscribers in a different browser tabs. Sometimes only one subscriber is work

**Comment by mpereal** [comment]
Hi I have the same problem. Did you find a solution ? Thanks

**Comment by smokezp** [comment]
> Hi I have the same problem.
> Did you find a solution ?
> For me seems to be a limit of 6 per browser for example : same computer 6 on chrome and 6 on safari are working. For both, the 7th is not working
> Thanks

No, I'm looking for a new bundle

**Comment by mpereal** [comment]
Hi 
In fact that’s a limit of the browser with EventSource. 
I found a way by destroying the object when changing the active tab of the browser and reactivating it when the tab becomes active.

**Comment by dunglas** [comment]
Are you sure that you are using HTTP/2 (it requires HTTPS)? There are no limits with HTTP/2, however browsers have limit when using HTTP/1.

**Comment by mpereal** [comment]
I'm in HTTP, I will try in HTTPS. Thanks for your answer.
