### ISSUE TITLE
Connection Limit under High Load

### ISSUE THREAD

**Issue by Leenert** [dunglas/mercure#255]
Hi All,
We're currently using Mercure in a chat environment with approx. 1200 participants. From time to time, mercure stops to accept new connections. In that case, all OPTIONS requests are arriving and printed in the log, but no connection / subscription can be established.

In some (not all) of theese occurences, we're experiencing a system error:
`accept4: too many open files`

We've already increased all corresponding limits, but no improvement. The mercure server is currently running on a EC2 m5.8xlarge instance.

Any help is much appreciated.

**Comment by dallen66** [comment]
Your OS may be limited to a maximal number of connections (open file descriptors). Setting maximum number of open file descriptors to 2048:
`ulimit -n 2048`
