### ISSUE TITLE
CLOSE_WAIT blocking mercure from creating new connections

### ISSUE THREAD

**Issue by kaplandani** [dunglas/mercure#259]
We're using Mercure behind nginx proxy. 
IT works great with average of 6000 connections (netstat)
after several hours  - something causes our container to "lock down" - investigating I've found 27000 CLOSE_WAIT connections on netstat and established connections dropped to 400. 
Restarting the container solves this.

Any idea what can cause this situation ?

**Comment by dunglas** [comment]
Thanks for the report. I’m investigating.

**Comment by dunglas** [comment]
I've found a problem that may be related: https://github.com/dunglas/mercure/pull/263

**Comment by dunglas** [comment]
@kaplandani this patch should fix the problem: #263
Could you try it and give me if it fixes your issue? Thanks!

**Comment by kaplandani** [comment]
I'm running mercue inside a container. if a binary replacement can help - I will replace the binary - but how can I get a compiled binary of this version ?  (I can try to compile the project - but I'm no go-lang developer :-) )

**Comment by dunglas** [comment]
I merged the PR in master, so you can create a production build this way:

```
git clone https://github.com/dunglas/mercure
cd mercure
CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
```

If you need help, contact me by mail (dunglas@gmail.com) or on Symfony's Slack, I'll send you a build. If the problem occurs again, it would be nice to try a debug build to have a proper stack trace!

**Comment by trisua** [comment]
Hi @dunglas,
I have same issue,
trying build master branch,  but got a lot of CPU load and huge memory usage and no "lock down" issue
master branch CPU
https://i.imgur.com/fOWqbMD.png
master branch memory
https://i.imgur.com/2XkU0T4.png

same EC2 instance (m5a.xlarge) but image: dunglas/mercure:v0.9
CPU
https://i.imgur.com/ricfMBN.png
memory
https://i.imgur.com/JH9JH83.png

BUT random "lock down" container

**Comment by dunglas** [comment]
This has been fixed in the master branch. Thanks a lot @kaplandani for your feedback and your time to test the patches!
