### ISSUE TITLE
Missing Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by deivid11** [dunglas/mercure#27]
I'm trying to access the hub from a subdomain in a web browser using  EventSource(url, {withCredentials: true}). First I got an error saying wildcard * can not be used when include credentials mode is enabled so I changed the mercure server flag 'CORS_ALLOWED_ORIGINS' and set my domain instead "*". Now when I send an update from the hub to the client I'm getting "No 'Access-Control-Allow-Origin' header is present on the requested resource"

**Comment by deivid11** [comment]
I can figure out my problem, I was setting the cookie in my application server, a different domain of my mercure server. I've changed the cookie authentication method to header method.

**Comment by dunglas** [comment]
Thanks for the head up
