### ISSUE TITLE
Suppport redis to transport?

### ISSUE THREAD

**Issue by koolay** [dunglas/mercure#270]

**Comment by dunglas** [comment]
Redis isn't currently supported officially (but there is official support for Kafka, Pulsar and Postgres). If you want to try an experimental stuff, checkout #181.

**Comment by dunglas** [comment]
Redis is now supported in the HA version: https://mercure.rocks/docs/hub/cluster

**Comment by julienhay** [comment]
Hello @dunglas,

How can I get HA version? I tried to contact contact@mercure.rocks but without any feedback.

Thank you
