### ISSUE TITLE
[bug] logged an incorrect error

### ISSUE THREAD

**Issue by koolay** [dunglas/mercure#282]
`log.WithFields(s.LogFields).Error(err)`

https://github.com/dunglas/mercure/blob/a38f4dc8b77b30b65bad201dab513cd5634008a6/hub/subscribe.go#L113

**Comment by dunglas** [comment]
Can you give more context? I don't understand what you mean.

**Comment by koolay** [comment]
`h.transport.AddSubscriber(s) ` , the returen's error not be logged.

```
	if h.transport.AddSubscriber(s) != nil {
		http.Error(w, http.StatusText(http.StatusServiceUnavailable), http.StatusServiceUnavailable)
		h.dispatchSubscriptionUpdate(s, false)
		log.WithFields(s.LogFields).Error(err)   // this 'err' is not h.transport.AddSubscriber(s) 
		return nil
	}
```

**Comment by dunglas** [comment]
Thanks! Good catch :) #285 fixes this issue.
