### ISSUE TITLE
Symfony throws error SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by adares2** [dunglas/mercure#292]
I have a Nginx Proxy running in front off the Hub that uses the same Certificate and key as the Main Nginx Server. The Main Server works with the Files. 
I use Docker for my Setup. The Proxy run under Port 7000.

In the Symfony .env file i have:
MERCURE_PUBLISH_URL=https://myDomain.com:7000

Symfony throws an Error: SSL peer certificate or SSH remote key was not OK for "https://myDomain.com:7000/".
in vendor/symfony/http-client/Chunk/ErrorChunk.php (line 64)

**Comment by adares2** [comment]
I have found the solution. Enter the original address of the hub in Symfony. Everything works as expected.

**Comment by Lyro1** [comment]
Hello @adares2, I am running on the same issue, and don't understand your solution.
Which address are you referring to?
