### ISSUE TITLE
Docker container mlock failed

### ISSUE THREAD

**Issue by BelphegorPrime** [dunglas/mercure#294]
Hi,

today I had the following error that crashed my docker container
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

Following https://github.com/golang/go/issues/37436 it looks like the best solution is to upgrade the Kernel.

Greetings

**Comment by dunglas** [comment]
I'll tag a new release this week.
