### ISSUE TITLE
How to implement without using any PHP package or framework?

### ISSUE THREAD

**Issue by ljfreelancer88** [dunglas/mercure#299]
Most of the online resources that I've red uses PHP frameworks or packages. But I want to keep it all simple for me to understand the implementation without relying framework or package.

My question is, how to implement without using any package or framework? Should I still use while loop to POST/Publish updates? ~ Thank You in advance.

**Comment by dunglas** [comment]
Did you look at https://github.com/dunglas/mercure/blob/master/examples/publisher-php.php? There are example in other programming languages in the same directory.

**Comment by ljfreelancer88** [comment]
Yes, but It doesn't sent/publish automatically when there's new or update on the data that was encoded.

**Comment by dunglas** [comment]
API Platform has something like that: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
