### ISSUE TITLE
getting 20 "token is expired" messages per second

### ISSUE THREAD

**Issue by kaplandani** [dunglas/mercure#300]
we're running mercure with around 4000 connections. 
we've noticed that the log is filled very fast with these messages aprox 20 per second. 
Any ideas - what happening in the background ? currently everything is working. but looks like something is not right: 

time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34654" subscriber_id=a81c2a77-27ae-4eaa-be1c-1a0fc61a3563
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34692" subscriber_id=dbfafd46-f680-4234-9ba6-d345c14aa7a3
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34748" subscriber_id=872e4e4a-f9c3-4ae5-9159-0a2a93a6c7b7
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34802" subscriber_id=3d416fa1-30e7-4633-a1df-04f84ab54e30
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34830" subscriber_id=3ac5f729-226d-42c9-9d33-7e2fc101a2d4
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 12m9s" remote_addr="172.18.0.1:34900" subscriber_id=70bfb9aa-233f-4e73-ac42-aa9bb2c286d1
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34910" subscriber_id=83114b4f-f9d7-49f6-8c5b-e7ddf070e724
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34940" subscriber_id=f25cc811-e2de-4bb7-a4a7-f647d341e2b3
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 12m9s" remote_addr="172.18.0.1:34948" subscriber_id=1728a115-364d-45ff-b3d8-4497eb69e7e3
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:34952" subscriber_id=1d6a03a4-ef0a-481f-b8f3-40a20fd8c482
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 12m9s" remote_addr="172.18.0.1:34962" subscriber_id=d97573bb-e62d-425d-b9e3-789b30e64e07
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35050" subscriber_id=c7bb6794-6fa7-4b30-bd29-660a70d108c3
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35108" subscriber_id=63390710-aab1-4315-9f86-30c3a1b6a8f5
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35130" subscriber_id=f26a0132-89ba-48fc-a216-59c889652388
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35164" subscriber_id=5fd7df2c-a630-40ca-b6e7-9dde572ab32c
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35246" subscriber_id=ab886fe2-0eb9-4df8-8a45-bdf498d4c641
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35250" subscriber_id=6724183d-83a8-4171-b91b-726a3e8e7372
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35254" subscriber_id=aff11f95-6e26-439b-af11-13d1d7911c06
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35258" subscriber_id=69078021-d584-47f3-9689-9bbe3d29c6a5
time="2020-05-16T06:13:18Z" level=info msg="token is expired by 9m52s" remote_addr="172.18.0.1:35276" subscriber_id=7c19f340-3633-4b4a-bffd-a66db4161f73
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46126" subscriber_id=c4d70b46-9993-43f8-8c3c-598e3f0a8551
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46132" subscriber_id=eed66b54-d466-4e45-8e1a-fa82b96ee289
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46144" subscriber_id=7fcbcf86-a225-478f-b697-7f57f7b0e652
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46176" subscriber_id=4e287a5e-81b2-4f40-a0b1-1c4e763ffa1c
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46190" subscriber_id=207f40f9-1257-4897-a2ba-bbb2e0cd3565
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46206" subscriber_id=93e7f373-a6aa-4540-b5a2-3b015a6e5989
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46216" subscriber_id=cd2df564-f27c-408c-9ce2-9be297882819
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46254" subscriber_id=c9c2e9b5-6b82-440f-bc97-7c9bee91fb40
time="2020-05-16T06:13:31Z" level=info msg="token is expired by 3m59s" remote_addr="172.18.0.1:46272" subscriber_id=402e6a29-ed01-43bd-aa65-e9ba45933c1c

**Comment by dunglas** [comment]
Isn't the JWT presented by the client expired? This error is most likely generated here: https://github.com/dunglas/mercure/blob/2905dbea8ac9ff425e2fe350a5aa6b8f96b3a960/hub/authorization.go#L168
