### ISSUE TITLE
Subscribe using PHP(no package)

### ISSUE THREAD

**Issue by ljfreelancer88** [dunglas/mercure#315]
Hi, how can I subscribe without using PHP package? I did check the documentation but publish is the only available. In NChan(Nginx) I can easily implement PUB/SUB without PHP package, it's just a little bit overwhelming in mercure.

Thank you

**Comment by dunglas** [comment]
Currently you have to create a SSE client (https://html.spec.whatwg.org/multipage/server-sent-events.html). Many SSE clients exist as packages, but as you don't one to use one... :)
In a near future, I plan to add support for WebSub to the Mercure hub (see #100).

**Comment by soyuka** [comment]
I'm working on a php client (https://github.com/symfony/symfony/pull/36692) :) stay tuned

**Comment by ljfreelancer88** [comment]
> Currently you have to create a SSE client (https://html.spec.whatwg.org/multipage/server-sent-events.html). Many SSE clients exist as packages, but as you don't one to use one... :)
> In a near future, I plan to add support for WebSub to the Mercure hub (see #100).

That's awesome! You can take a look [https://nchan.io/](url) maybe an idea because it's so easy to implement. That's their selling point to me and it's asynchronous! All heavy lifting including async work done by the Hub and a little bit extra configuration on developers end.
