### ISSUE TITLE
A way to get new records in datatable

### ISSUE THREAD

**Issue by BenWaNH** [dunglas/mercure#316]
Hi,

anyone have an idea to implement Mercure to subscibe to new entity record and refresh automatically a datatable for example. (It works great if i subscribe at each topic for each record line in datatable, update is good, but how to get new ??!)

Thanks.

**Comment by dunglas** [comment]
You can use URI topics for that. Example : `/well-known/mercure?topic=https://example.com/my-entity/{id}`. Then any update matched by the template (including new IDs) will be received by the subscriber.

**Comment by BenWaNH** [comment]
Yes! Interesting feature indeed but i'm thinking something more sophisticated maybe... Like according to current filters or pagination. Get a resource list (the same when we ask GET action on API Platform (i use it) but automatically refreshed, not just one resource) But maybe it's not a Mercure concern... Maybe i've to think to a trick in my api platform project for this but i don't see either how Mercure could be respond to this
