### ISSUE TITLE
How to send private data with the new version of Mercure ?

### ISSUE THREAD

**Issue by GaylordP** [dunglas/mercure#317]
I use Mercure with Symfony thanks to the [Symfony Mercure bundle](https://github.com/symfony/mercure).

Previously, the `Update()` class had as third arguments `targets`, which allowed to select the recipients of a private publication.

Now, this argument is just `true` or `false` : [See Symfony Commit](https://github.com/symfony/mercure/commit/0a1a0da87e3256e79fadc9fa7ff40909bbfec4b4#diff-5ed7fafb46947ea5ec64434d9812664f).

In this context, how to define the recipients of a Mercure publication ? I searched for several hours and the documentation is no longer very easy.

I hesitated to post this question on Symfony issues, but I think it has more place here, sorry if I'm wrong.

**Comment by bycrea** [comment]
Hello everyone, 

Same problem here, I builded my all application based on the topics / targets implementation and everything disappeared after updating composer ^^

Is there anyway to go back in time and get the last Update class? 
Both "symfony/mercure-bundle": "^0.2.3" & symfony/messenger": "4.4.*" dont seem to have change... 
Or is there a simple way to adapt the same work follow with new "private" param ?

Thanks in advance.

**Comment by bycrea** [comment]
Ok, I finally managed to go back to the oldest version by changing the composer.lock symfony/mercure with version 0.3.0. 

I'll try to update my application with new mercure later on ;) 
Thanks

**Comment by anwarien** [comment]
hi Gaylord. i think for the private update you have to specify the id in the topic itself  exemple.com/chat/$id , true(private)  and the same thing in javascript eventsource
