### ISSUE TITLE
how can I get active subscribers?

### ISSUE THREAD

**Issue by mahsamnz** [dunglas/mercure#324]
I send this route with GET in postman
http://localhost:3000/.well-known/subscriptions
but It returns 404 page not found.

**Comment by soyuka** [comment]
According to the docs it looks like subscriptions are disabled by default on the hub [see here](https://mercure.rocks/docs/hub/config).

**Comment by dunglas** [comment]
@soyuka is right! You need to explicitly enable this feature.
