### ISSUE TITLE
Unable to see messages automatically to a particular subscribed topic.

### ISSUE THREAD

**Issue by ljfreelancer88** [dunglas/mercure#325]
I'm using MariaDB to store data from my form. The problem is I can only able to see those messages when I hit the form through AJAX POST method. What I want to achieve is as a subscriber to a particular topic I want to automatically see those messages.

For the sake of simplicity, this is my code. I'm not sure, if doing the correct approach using Mercure.
```
<script>
const subject = `{{ $topic }}`;

function createMenuItem(name) {
	let li = document.createElement('li');
	li.textContent = name;
	return li;
}
const url = new URL('http://localhost/sse');
url.searchParams.append('topic', subject); 
const eventSource = new EventSourcePolyfill(url);

eventSource.onmessage = (e) => {
    const datas = JSON.parse(e.data);
    html = '<div>';
    datas.forEach((v) => {
        html += '<div class="chat-body">' + v.message + '</div>';
    });
    html += '</div>';

    $("#content").html(html);
};
</script>
```

**Comment by dunglas** [comment]
I'm not sure to understand what's the problem. How to you send the `POST` request to the Mercure Hub? Using a MariaDB trigger?
