### ISSUE TITLE
Heartbeat seems to not be working

### ISSUE THREAD

**Issue by Vaggal** [dunglas/mercure#335]
Hello,

I have used Mercure 0.10.0 successfully with a client that expects a heartbeat every N seconds. After testing 0.10.1 and 0.10.2 versions of Mercure I noticed that the client disconnects after N seconds and reconnects again. Could this be caused by https://github.com/dunglas/mercure/commit/a8118ee78b551e4177d69ab0d4114df06d79811f?
I am using the default value of heartbeat_interval but I have also tried setting it to `2s` or `5s` but it doesn't fix the issue.

**Comment by dunglas** [comment]
Heartbeat are working (we have tests for this feature). However the default timeout has changed to 60s. You can increase it by changing the `write_timeout` config option (set it to 0s to totally disable this timeout). I plan to increase a bit this timeout in the next release.
