### ISSUE TITLE
a --jwt-key-file parameter?

### ISSUE THREAD

**Issue by CedCannes** [dunglas/mercure#337]
Is there a plan to add a --jwt-key-file parameter?

it would simplify our lives because: 
- we use the PLATFORM API docker which generates key files for each build
- we use AES 256 format for the JWT and we can't use `cat` with the mercure container (it does not contain a shell).
- for the moment we copy it by hand in docker-composes file :disappointed:

**Comment by CRKaraman** [comment]
i thinks in this way - for now i can not run mecrure on linux with file config^(

**Comment by dunglas** [comment]
Why not. PR welcome!

**Comment by monstrum** [comment]
I manage to make it work. don't ask me to improve it. I just read golang a hour ago and start using it with help from stackoverflow community. And I am also sure, It is not the right way.

Info:
I got no experience at all in go programming, I just did some trick.
- Check Key Prefix (if it is contains file://)
- Read the key from /public.key
so it is just working if the key file mounted as /public.key.

Feel free to check it out and improve it.
https://github.com/monstrum/mercure/commit/052e4e5d0feb9b4f82e96f8f3607e12e067d9dbd

**Comment by yannissgarra** [comment]
Same issue for me... @CedCannes : how do you copy it by hand in docker-composes file (I suppose in JWT_KEY env var) ? I'm struggling to do it, nothing works for me :(

**Comment by monstrum** [comment]
@yannissgarra

I tried it once, check this ticket. This is might what you looking for.
https://github.com/dunglas/mercure/issues/313

if you want to use file instead, i fork from dunglas/mercure and add file support in it. It might be not up to date.

**Comment by yannissgarra** [comment]
@monstrum 
Well yes ! I've just succeeded thanks to your help !

Here is my docker-compose config : 

`mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: |-
        -----BEGIN PUBLIC KEY-----
        ...
        -----END PUBLIC KEY-----
      JWT_ALGORITHM: RS512
      DEMO: 1
      CORS_ALLOWED_ORIGINS: '*'
      PUBLISH_ALLOWED_ORIGINS: '*'`

But I don't succeed to use public key as a file, I tried everything, but I gave up.

**Comment by monstrum** [comment]
@yannissgarra Great, glad it helps!

Well, like i said. Standard Docker image from Dunglas/mercure doesn't support JWT File as JWT Key. Therefore I fork it, and did some trick. and I build myown image, for using Public key as file. I recommended using dunglas/mercure, however if you still want to use file as jwt key. this is the setting i used. The key must be "file:///public.key" and it must mounted in root directory. Just like below. 

service:
  event-hub:
    image: monstrum/mercure:v0.10.3
    environment:
      JWT_KEY=file:///public.key
      JWT_ALGORITHM=RS512
    volumes:
      - ./mercure/public.key:/public.key
