### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by HellPat** [dunglas/mercure#338]
The link "https://mercure.rocks/ecosystem/awesome#examples" is broken (404)

**Comment by dunglas** [comment]
The good link is https://mercure.rocks/docs/ecosystem/awesome#examples.
Can you tell me where you find the original link (from which page?)? Thanks for reporting!

**Comment by psren** [comment]
Oh, sorry, I missed your comment and don't find the reportet link anymore. sorry for the bad report.

Here are two other broken links though:

- https://mercure.rocks/docs/hub/cookbooks
  - "the HA Version" which points to https://mercure.rocks/docs/cluster
  - "a load test" https://mercure.rocks/docs/load-test

**Comment by dunglas** [comment]
Thanks @HellPat, we're on it.

**Comment by dunglas** [comment]
Fixed!
