### ISSUE TITLE
Topic selectors not matched or not provided

### ISSUE THREAD

**Issue by AntistasII** [dunglas/mercure#340]
I am using mercure + symfony

I have problem when i invoke publisher update OR i go to http://localhost:3000/.well-known/mercure

HTTP/1.1 401 Unauthorized returned for "http://localhost:3000/.well-known/mercure". 

In terminal I have INFO[1067] topic selectors not matched or not provided   remote_addr="127.0.0.1:65137" 127.0.0.1 - - [24/Jun/2020:19:33:03 +0500] "POST /.well-known/mercure HTTP/1.1" 401 13 "" "Symfony HttpClient/Curl"

 I did not find any info about this error. Thank you in advance

**Comment by dunglas** [comment]
Double check your JWT, it probably doesn't contain the required `mercure.publish` key. For subscribing, you probably miss a `topic` query parameter.
