### ISSUE TITLE
Add namespacing support on claims

### ISSUE THREAD

**Issue by blaspix-tech** [dunglas/mercure#343]
Hello,

The aim being to allow the use of Mercure with access tokens generated by Auth0.

https://auth0.com/docs/tokens/guides/create-namespaced-custom-claims
_By default, Auth0 always enforces namespacing; any custom claims with non-namespaced identifiers will be silently excluded from tokens._

Here is an example of Auth0 rule :

```
function` (user, context, callback) {
 var namespace = 'https://example.com/';
 context.accessToken[namespace + 'mercure'] = { "subscribe": [ user.email ] };
 return callback(null, user, context);
}
```

Thanks for your feedback guys and cheers
cc @dunglas

**Comment by dunglas** [comment]
So the claim should be `https://mercure.rocks/` right? It looks good to me.

**Comment by dunglas** [comment]
I'm not sure if it's required because the spec itself registers a new reserved claim (`mercure`). Namespaced claims are for custom claims, not for claims reserved in specs (it's the same thing for the `rel` that the Mercure spec reserves for the `Link` header).

**Comment by blaspix-tech** [comment]
> I'm not sure if it's required because the spec itself registers a new reserved claim (`mercure`). Namespaced claims are for custom claims, not for claims reserved in specs (it's the same thing for the `rel` that the Mercure spec reserves for the `Link` header).


Auth0 trusts IANA JSON Web Token Claims Registry.
https://www.iana.org/assignments/jwt/jwt.xhtml#claims

> So the claim should be `https://mercure.rocks/` right? It looks good to me.

Let me try

**Comment by blaspix-tech** [comment]
I confirm, `https://mercure.rocks/` works and sounds good.

**Comment by blaspix-tech** [comment]
Related files are:
https://github.com/dunglas/mercure/search?q=claims.mercure&unscoped_q=claims.mercure&type=Code

I am a big quiche in Go language sorry.

**Comment by dunglas** [comment]
Ok thanks for the link, I'll register the claim to this registry.

**Comment by TamasSzigeti** [comment]
Any clue when IANA will register the mercure claim and auth0 will whitelist it? I'm wondering if we should wait or come up with a workaround until then…

TIA

**Comment by TamasSzigeti** [comment]
We still need this, any updates, @dunglas ? Either alternative url-formatted claim or whitelisted by auth0 (based on iana) would work…
TIA

**Comment by dunglas** [comment]
I don't know how much time it will take for the registration. I suggest to add support for a namespaces alias in the meantime.

**Comment by TamasSzigeti** [comment]
I agree! I'm not too proficient in go but will try myself and submit a PR if it's fine with you
