### ISSUE TITLE
Spec and Implementation difference: .well-known/mercure/subscriptions vs .well-known/subscriptions

### ISSUE THREAD

**Issue by skurfuerst** [dunglas/mercure#344]
Hey,

In the spec, the subscription URL at https://mercure.rocks/spec is most often listed as ` .well-known/subscriptions`  (as listed in https://mercure.rocks/spec#active-subscriptions ) - but in the source code and some other examples it is (correctly I believe) `.well-known/mercure/subscriptions`.

Thanks for your great product :) Hope this helps somebody :)

All the best,
Sebastian

**Comment by dunglas** [comment]
Thanks for the report! The spec was faulty. This has been fixed by #347.
