### ISSUE TITLE
Missed message when I have a heartbeat

### ISSUE THREAD

**Issue by mahsamnz** [dunglas/mercure#354]
I use Mercure for getting live data and subscription requests repeat each minutes. 
I wanted to increase the request duration more than 1 minute so I add "WRITE_TIMEOUT=1800s" in mercure command. is it correct and good solution?

Also when I have an published request exactly when subscriber request expires and new subscriber request send, I missed that message.

my code is like this. @dunglas would you please check to find out what is the problem?

`<script>

        let ul = null;
        let lastEventId = null;
        var mercureToken = "Bearer {{ token }}";
        const url = new URL("http://localhost:3000/.well-known/mercure");
        // All Review resources will match this pattern
        url.searchParams.append('topic', "{{ topic }}");
        if (lastEventId !== null)
            url.searchParams.append('Last-Event-ID', lastEventId);

        var es = new EventSourcePolyfill(url, {
            headers: {
                "Authorization": mercureToken
            }
        });
        es.onmessage = e => {
            lastEventId = e.lastEventId;

            const data = JSON.parse(e.data);
            console.log(data);
            }
        }
    </script>
`

**Comment by mahsamnz** [comment]
Hi @dunglas, Is there any solution for this problem?

**Comment by dunglas** [comment]
I don't manage to reproduce. Are you using the Bolt transport? Could you check what is the value of `Last-Event-ID` sent by the browser and the content in the DB (you can use this tool to see the content of the DB: https://github.com/evnix/boltdbweb).


Your configuration looks good.

**Comment by mahsamnz** [comment]
No I don't use bolt. is it necessary to use bolt to receive old messages?

**Comment by dunglas** [comment]
Yes it is necessary. If you use the local transport there is no history at all.

**Comment by dunglas** [comment]
That being said, we could implement an "in memory" history, but I'm not sure it is worth it, using Bolt will consume less memory and has more features. If persisting a file on disk is an issue, using tmpfs or ramfs should do the trick.
