### ISSUE TITLE
Move the Helm chart to this repo

### ISSUE THREAD

**Issue by sagikazarmark** [dunglas/mercure#357]
As of Nov 2020 the "official" (central) helm chart repository will be marked obsolete. The best practice now is to host charts next to the project (either in the same repo or in a dedicated chart repo).

It also makes easier to merge contributions/keep changes in a single PR.

The chart repository itself can be hosted in a github repo, using github pages and a custom domain (eg. `charts.mercure.rocks`)

I'd also drop Helm 2 support and focus on Helm 3.

The chart in the official Helm repository can be kept for a period of time so that people have time to transition to the new chart.

I'd be happy to provide a PR if you are interested.

**Comment by dunglas** [comment]
Hi @sagikazarmark, thanks for the detailed report. A PR will be very appreciated!

**Comment by sagikazarmark** [comment]
Sure. What are your options for running a Helm chart repository? It turned out the github repository as a helm repository thing is pretty dumb, I'm working on a github plugin now. Alternatively, you could setup a GCS or S3 bucket, or a ChartMuseum instance, but that last one is probably an overkill.

**Comment by dunglas** [comment]
I'll probably go for Chart Museum as I have a K8s cluster available for Mercure. I'll take a look.

**Comment by sagikazarmark** [comment]
Still valid

**Comment by sagikazarmark** [comment]
Still valid

**Comment by asimonf** [comment]
Hey guys, any chance we can get this up somewhere? It has been a pain to get a chart for this and I'm currently running the deprecated version. I think there's interest to help get this up, but without guidance on hosting this will probably remain unresolved.

**Comment by dunglas** [comment]
We'll host it directly in this repository. I've started something here: https://github.com/api-platform/api-platform/tree/main/helm/api-platform

Basically, what is left to do is to extract the Mercure part.

**Comment by sagikazarmark** [comment]
I'm working on a generic Caddy helm chart. It should work with mercure as well.

https://artifacthub.io/packages/helm/sagikazarmark/caddy
