### ISSUE TITLE
I will not change the domain name of cookie, how to solve it

### ISSUE THREAD

**Issue by shijunti19** [dunglas/mercure#36]
vue-cli3
vue
My local address：http://localhost:8080/#/chat/index
Server address：https://mercure.a031.com/
I use EventSource
```js
let jwt='***jwt_key*';
const u = new URL(hubUrl)
    topicList.forEach(topic => u.searchParams.append('topic', topic))
    u.searchParams.append('Last-Event-ID', 2)
    var eventSourceInitDict = {
      withCredentials: false,
      headers: {
        Authorization: 'Bearer ' + jwt,
        Cookie: 'mercureAuthorization=' + jwt,
        'Access-Control-Allow-Origin': '*'
      }
    }
    eventSource = new EventSource(u, eventSourceInitDict)
    eventSource.onmessage = function(e) {
      console.log(e)
    }
    eventSource.onerror = error
```
![image](https://user-images.githubusercontent.com/5392211/49498193-322e7d80-f8a5-11e8-8252-981886114afc.png)

Unauthorized

```js
JWT_KEY='pasword' ADDR=':4000' CORS_ALLOWED_ORIGINS='*' LOG_FORMAT='json' DEMO=1  ./mercure
```
I will not change the domain name of cookie, how to solve it

**Comment by shijunti19** [comment]
After studying for so long, I think EventSource is a very bad design. No wonder nobody uses it. Cook agent is a big problem and nginx agent can cause delays. There are too many things to set up.

**Comment by dunglas** [comment]
Did you looked at https://github.com/dunglas/mercure#401-unauthorized?

**Comment by shijunti19** [comment]
```js
vue.config.js
 devServer: {
    proxy: {
      '/api': {
        target: 'https://mercure.a031.com',
        secure: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': '' //需要rewrite的
        }
      }
    }
  },

let hubUrl = 'https://mercure.a031.com/hub'
    if (process.env.NODE_ENV === 'development') {
      hubUrl = 'http://localhost:8080/api/hub'这行是重点，我弄了3天，必须是域名http://localhost:8080/api/不然 new URL无效的出错的。
  const u = new URL(hubUrl)
    }
```

**Comment by shijunti19** [comment]
@dunglas How to empty all data！
```js
event: 2
retry: 2
id: fe9r
data: {
data:   "@id": "https://****/demo/books/1.jsonld",
data:   "availability": "https://schema.org/OutOfStock"
data: }

event: 2
retry: 2
id: fe9r
data: {
data:   "@id": "https://****/demo/books/1.jsonld",
data:   "availability": "https://schema.org/OutOfStock"
data: }

event: fe9r
retry: 2
id: fe9r
data: {
data:   "@id": "https://****/demo/books/1.jsonld",
data:   "availability": "https://schema.org/OutOfStock"
data: }

event: fe9r
retry: 2
```

**Comment by shijunti19** [comment]
@dunglas How to empty the pushed data

Instead of canceling the focus, he reappears every time he refreshes it

**Comment by dunglas** [comment]
You mean the history?

**Comment by shijunti19** [comment]
@dunglas yes!
![image](https://user-images.githubusercontent.com/5392211/49869604-ccfdfd80-fe4b-11e8-852b-0c93bff4b7c8.png)
Yes, I delete the database clearance now.

**Comment by shijunti19** [comment]
Cannot be used due to cross-domain issues

1.Repeat requests with nginx proxy
![image](https://user-images.githubusercontent.com/5392211/49909008-0409f880-feb8-11e8-917f-895bbb0584f5.png)
![image](https://user-images.githubusercontent.com/5392211/49909016-0f5d2400-feb8-11e8-800b-9a28c67076cb.png)
2.Can't solve cross-domain problems in Cordova

It's very unusable and incomprehensible.

It can only be used under the same domain name.

**Comment by dunglas** [comment]
Indeed if you want to flush the history, you just have to delete the db file `updates.db`. But what's the benefit of doing this?

**Comment by dunglas** [comment]
1. Can you explain exactly what issues you have so we can maybe improve the docs or the features of the hub?
2. I'm not sure to understand what you mean. The demo chat doesn't have a history, you should indeed handle it at the app layer
3. I'm not sure it will help, a better solution would be to (the internal db is only a kind of temporary persistence layer to retrieve missed events when EventSource reconnects after a network failure)
    * send the POST request to the Python app
    * store the message in an external DB
    * dispatch the update from the Python app to the Mercure Hub
    * when a new client connects to the chat, fetch the history from the external DB
4. Yes Android Browser does support SSE: https://caniuse.com/#feat=eventsource
