### ISSUE TITLE
Subscribe to ApiPlatform subresource

### ISSUE THREAD

**Issue by AymLaf** [dunglas/mercure#367]
Hello everyone,

I'm a begginer with Mercure and I have a question about the way to use Mercure with ApiPlatform (+ Symfony). I hope it will not be too dumb :/
Let's assume two entities : **_EntityA_** and **_EntityB_**.
Both are Symfony/Doctrine entities with "mercure=true" in @ApiResource annotation.
**_EntityB_** is a @ApiSubresource() of **_EntityA_**.

With Mercure + ApiPlatform i'm able to subscribe on "<my_domain>/api/entityb/{id}" to receive notifications about this collection.
But when i'm trying to do "<my_domain>/api/entitya/<entitya_identifier>/entityb/{id}" it fails.
Even with "<my_domain>/api/entityb/{id}?entitya=<entitya_identifier>" it fails.

Is there any way to subscribe to a SubResource ?
Or what I'm doing wrong ?

Thanks

**Comment by dunglas** [comment]
Hi, could you reopen this issue on the API Platform bug tracker? The API Platform integration isn't related with the hub or the protocol itself.
