### ISSUE TITLE
Subscribers receive private updates that are not in scope of their JWT 

### ISSUE THREAD

**Issue by tf-kevin** [dunglas/mercure#372]
When pushing a private update to the hub subscribers that don't have access to the topic as per their JWT token receive the messages. 

Example: 
The publisher pushes a private update to _event://123456/moderation_ and the subscriber listens on events for the same topic.
As per my understanding of the protocol the subscriber should not be able to get this message because the JWT does not allow it and it is a private update.  

**Subscriber JWT content**
```json
{
  "mercure": {
    "subscribe": [
      "NOT_A_VALID_TOPIC"
    ]
  },
  "iat": 1599960704,
  "exp": 1599961424
}
```

**Publisher JWT content**
```json
{
  "mercure": {
    "publish": [
      "*"
    ]
  }
}
```

**Sample from mercure hub log file**
```
time="2020-09-13T01:38:12Z" level=info msg="Update published" event_id=3a17ef46-7fb5-496e-99c4-41e1c12b4ae2 event_retry=0 event_type= remote_addr="xx.xx.xx.xx:64275" update_data="{...}" update_targets="[]" update_topics="[event://3ee6f221-f504-11ea-a1b2-0242ac160002/moderation]"
time="2020-09-13T01:38:12Z" level=info msg="Event sent" event_id=3a17ef46-7fb5-496e-99c4-41e1c12b4ae2 event_retry=0 event_type= last_event_id= remote_addr="xx.xx.xx.xx:60124" subscriber_targets="[NOT_A_VALID_TOPIC]" subscriber_topics="[event://3ee6f221-f504-11ea-a1b2-0242ac160002/moderation]" update_data="{...}" update_targets="[]" update_topics="[event://3ee6f221-f504-11ea-a1b2-0242ac160002/moderation]"
```

**Code snippet for pushing the update in Symfony 5**
<img width="508" alt="symfony-update" src="https://user-images.githubusercontent.com/60135953/93008280-30faac00-f573-11ea-9a7b-1da6d6ebc0b6.png">

**Docker configuration**
```
version: '2'
services:
  mercure:
    image: dunglas/mercure:latest
    restart: always
    environment:
      - JWT_KEY=xxxxxx
      - HEARTBEAT_INTERVAL=15s
      - ADDR=:https
      - CORS_ALLOWED_ORIGINS=https://xxxxxxxx
      - ALLOW_ANONYMOUS=false
      - CERT_FILE=/certs/live/xxxxxxx/fullchain.pem
      - KEY_FILE=/certs/live/xxxxxxx/privkey.pem
      - DEBUG=false
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/certs/
```

**Comment by dunglas** [comment]
I tried to reproduce on https://demo.mercure.rocks using the topic the JWT you provided and it works as expected. Can you check if you are able to reproduce using the demo, and if yes provide (if possible privately) the exact settings you use?
