### ISSUE TITLE
 net::ERR_HTTP2_PROTOCOL_ERROR 200 error with api platform and mercure

### ISSUE THREAD

**Issue by tonyellow** [dunglas/mercure#373]
I use mercure in combination with api platform. In front i have a Google Cloud load balancer. Every 30 seconds I see the following error popping up in console of frontend:

GET https://...../.well-known/mercure?topic=poep net::ERR_HTTP2_PROTOCOL_ERROR 200

I already tried setting the environg variable HEARTBEAT_INTERVAL='15s' but it does not fix the problem.

Does anyone know what is causing this error?

**Comment by dunglas** [comment]
Do you use the shell chart? It contains a special resource for that: https://github.com/helm/charts/blob/master/stable/mercure/templates/backend-config.yaml

Otherwise, you'll have to set the timeout of the GCP's load balancer by yourself.

**Comment by tonyellow** [comment]
Thanks for pointing me in the good direction and for creating this fantasic software. Increasing the timeout on the load balancer fixed it. Cheers!
