### ISSUE TITLE
Document what config params are automatically reloaded

### ISSUE THREAD

**Issue by NateEag** [dunglas/mercure#381]
The docs say that ["most" configuration parameters are hot reloaded](https://github.com/dunglas/mercure/blob/f8f3dc0a255b503043fa654070dffad666a7ebca/docs/hub/config.md).

The first two config params I tried hot reloading on my local Vagrant VM were not updated until I restarted the process, though. Those were `TRANSPORT_URL` and `JWT_KEY`.

It makes sense to me that `TRANSPORT_URL` is not hot reloaded, but I didn't guess that `JWT_KEY` would not be.

The docs really should list the config values that are not hot-reloadable.

Would someone who knows the codebase be willing to add that?

**Comment by NateEag** [comment]
I just tried adding the `USE_FORWARDED_HEADERS` param to my `/etc/mercure/mercure.env` file, and it also had no effect until I restarted the process.

Maybe that one's special too, but hitting three that aren't hot-reloadable in a row feels a bit unlikely.

Is something broken here?

**Comment by NateEag** [comment]
A quick poke through the code shows that Mercure uses [Viper](https://github.com/spf13/viper) to load configuration.

Viper's docs say you need to [opt-in to watching config files](https://github.com/spf13/viper/tree/v1.7.0#watching-and-re-reading-config-files) with `viper.WatchConfig()` .

A search in this repo for `WatchConfig` [produces no hits](https://github.com/dunglas/mercure/search?q=WatchConfig&type=).

Is configuration hot-reloading actually supported?

**Comment by dunglas** [comment]
Hi,

The Viper-based version is now deprecated and we recommend upgrading to the Caddy-based version. This version works differently, you must type `mercure reload`, use the REST API or send `SIGUSR1` to the process to reload the configuration: https://caddyserver.com/docs/command-line#caddy-reload

This should fix the issue.

**Comment by NateEag** [comment]
Okay, cool. Thanks for the update, @dunglas .

It looks like this change is only available in the `v0.11.0-beta.1` version. Are you recommending using that beta version in production?

**Comment by dunglas** [comment]
Not yet! But I'll tag a stable soon.

**Comment by NateEag** [comment]
Okay, thanks for the info!
