### ISSUE TITLE
Symfony 5 error: SSL peer certificate or SSH remote key was not OK for "https://domain.com:1337/.well-known/mercure

### ISSUE THREAD

**Issue by JocelynRAZAFY** [dunglas/mercure#382]
Hello,

I purchased an ssl certificate from Sectigo Limited. 

When I run $update = new Update(
            $topic,
            json_encode($data),
            $targets);
        $publisher($update);
      // $this->bus->dispatch($update);

I got this error:

Symfony\Component\Messenger\Exception\HandlerFailedException: "SSL peer certificate or SSH remote key was not OK for "https://domain.com:1337/.well-known/mercure"." at /var/www/varotra/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php line 80

Here are my configurations hub:
sudo ./mercure/mercure --jwt-key='passwordKey' --debug --allow-anonymous --cors-allowed-origins='https://domain.com' --publish-allowed-origins='https://domain.com:1337' --addr=':1337' --cert-file='/etc/ssl/comodo/domain_com.pem' --key-file='/etc/ssl/comodo/domain.key'

.env:
MERCURE_PUBLISH_URL=https://domain.com:1337/.well-known/mercure

mercure.yaml:
mercure:
    enable_profiler: '%kernel.debug%'
    hubs:
        default:
            url: '%env(MERCURE_PUBLISH_URL)%'
            jwt_provider: App\Mercure\JwtProvider

Could someone please help me ?
Thank you in advance

**Comment by latrach** [comment]
Hello,  
you use https with 1337,  use a proxy that redirects the https to 1337?

**Comment by JocelynRAZAFY** [comment]
Hello @latrach 

thank you for your answer
I followed your proposal but It's always the same message.

Here is my VirtualHost please:

`<IfModule mod_ssl.c>
<VirtualHost *:443>
  
    ServerAdmin admin@example.com
    ServerName domain.com
    ServerAlias domain.com
    DocumentRoot /var/www/domain/public
    DirectoryIndex index.php
    <Directory /var/www/domain/public>
        AllowOverride None
        Order Allow,Deny
        Allow from All

        FallbackResource /index.php
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{HTTP:Authorization} ^(.*)
            RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
        </IfModule>
    </Directory>

        ProxyPass /.well-known/mercure          http://domain.com:1337/.well-known/mercure
        ProxyPassReverse /.well-known/mercure   http://domain.com:1337/.well-known/mercure

	<Directory /var/www/domain/public/bundles>
        	FallbackResource disabled
    	</Directory>
    	ErrorLog ${APACHE_LOG_DIR}/domain_error.log
    	CustomLog ${APACHE_LOG_DIR}/access.log combined
 	SSLEngine on
 	SSLCertificateFile /etc/ssl/comodo/domain_com.pem
 	SSLCertificateKeyFile /etc/ssl/comodo/domain.key
</VirtualHost>
</IfModule>`
