### ISSUE TITLE
Log only level=error or higher

### ISSUE THREAD

**Issue by aurelijusrozenas** [dunglas/mercure#384]
Hi,

I cannot find any option to configure logging to log only `error` level and up. I see `level=info` in logs so I assume there are at least error level? I only want to log information when something is going wrong so I know that some action must be taken.
1. Is it possible to configure logging level?
2. Is there documentation what is being logged?
I am using docker image but I do not think it's relevant.

Thanks!

**Comment by dunglas** [comment]
This is now possible in 0.11 alpha using the Caddy-based version: https://caddyserver.com/docs/caddyfile/directives/log

**Comment by aurelijusrozenas** [comment]
Still having problems even with 0.11 version. I want to change default logging level to 'warn' it does not work and logger is still spamming with all debug and info level logs.

This is my Caddyfile.
```
# https://caddyserver.com/docs/caddyfile
{
    # HTTP/3 support
    experimental_http3
}

my-domain.tld {
    log {
        level warn
    }

    route {
        redir / /.well-known/mercure/ui/
        encode gzip

        # https://mercure.rocks/docs/hub/config
        mercure {
            # Publisher JWT key
            publisher_jwt !ChangeMe!
            # CORS
            cors_origins *
            # Allow anonymous subscribers
            anonymous
        }

        respond "Not Found" 404
    }
}
```

And I see that it is parsed to:
```
"logging": {
    "logs": {
        "default": {
            "level": "DEBUG"
        },
        "log0": {
            "include": [
                "http.log.access.log0"
            ],
            "level": "warn"
        }
    }
}
```

I found [this thread](https://caddy.community/t/how-to-set-the-default-log-level/9298/3]) that explains that you cannot change global logger and you should defined logging options to every domain server config. But even doing that as above it does not change the output. Any ideas?
