### ISSUE TITLE
Intent to Remove HTTP/2 server push in Chromium

### ISSUE THREAD

**Issue by jzecca** [dunglas/mercure#391]
Not a "real" issue per se, but I just stumbled upon this while browsing Twitter (via [@intenttoship](https://twitter.com/intenttoship/status/1326652757739180033)):
https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ

I don't know anything about the decision making process of the Blink project, but I guess this could have major consequences on Mercure and Vulcain.

The post was made just a few hours ago, but I thought it would be a good idea to share it here and gather your thoughts about it.

**Comment by jzecca** [comment]
Closing since it looks like I'm kinda late to the party 😉 
https://twitter.com/dunglas/status/1326552735404060672

**Comment by dunglas** [comment]
For the record, it changes nothing for Mercure. But it does impact Vulcain: https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/4iaeRolCAQAJ

**Comment by jzecca** [comment]
Thanks for the clarification and the very interesting post 👍
