### ISSUE TITLE
High severity issue in github.com/dgrijalva/jwt-go

### ISSUE THREAD

**Issue by sagikazarmark** [dunglas/mercure#394]
There is an unpatched, high severity issue in the aforementioned JWT package: dgrijalva/jwt-go#428

Unfortunately, it looks like the author completely abandoned the package.

There is a maintained fork that fixes the issue, but a lot of users seem to prefer gopkg.in/square/go-jose.v2 now.

**Comment by dunglas** [comment]
AFAIU, we aren't affected by the security issue because we don't rely on audiences.

**Comment by dunglas** [comment]
I would like to migrate to `https://github.com/square/go-jose`. This should also fix #404.

**Comment by divine** [comment]
> I would like to migrate to `https://github.com/square/go-jose`. This should also fix #404.

@dunglas 👋,

I think there are some conflicts with maintenance and it doesn't look good that main contributor left the company and it isn't being taken care https://github.com/square/go-jose/issues/342#issuecomment-736735190

Maybe as suggested this one is better https://github.com/lestrrat-go/jwx?

Thanks!

**Comment by dunglas** [comment]
Related:

* https://github.com/auth0/go-jwt-middleware/issues/73
* https://github.com/dgrijalva/jwt-go/issues/457

Currently, there is no clear winner between all the proposed replacements.
I proposed a patch to form3tech's to fix #404: https://github.com/form3tech-oss/jwt-go/pull/11

I'll use my own fork until it is merged, and we'll switch either to form3tech's fork, JWX or Square's lib (but this one looks unmaintained too) when a clear winner will emerge.

**Comment by sagikazarmark** [comment]
Looks like go-jose v3 is just around the corner: https://github.com/go-jose/go-jose/releases

**Comment by townsymush** [comment]
I think this might be the option going forward https://github.com/golang-jwt/jwt

**Comment by townsymush** [comment]
I think this might be the option going forward https://github.com/golang-jwt/jwt. It's a direct form from the dgrijalva/jwt-go and is now being maintained. It would probably involve a lot less commitment to switch too
