### ISSUE TITLE
How to use alternate topic with Api Platform?

### ISSUE THREAD

**Issue by GrandOurs35** [dunglas/mercure#396]
Hi,
first of all, thanks a lot for your amazing work.

I have, surely a stupid question, but i don't see how to solve my problem. Following the Mercure docs which show how to use alternate topics for private updates:

> topic=https://example.com/books/1&topic=https://example.com/users/foo/?topic=https%3A%2F%2Fexample.com%2Fbooks%2F1&private=on

i don't see how to apply it into an Api Platform environment. I see that in the Api Platform docs, we can use the "topic" option:

> In addition to private, the following options are available:
> 
>     topics: the list of topics of this update, if not the resource IRI is used

So in my Doctrine entity, i can set-up this topics variable but i don't see how to fill it because i need some services to create my alternate topic.

And i would like to know how to "customize" the topic by keeping the iri for the canonical one and adding an alternate topic with my user information?
Do i need an event listener? but i don't see at which moment to use it.
Is there another way?

Thanks a lot for your help :)

**Comment by soyuka** [comment]
Hi,

Please take a look at https://github.com/symfony/mercure, topics in API Platform are the resources IRIs and updates are published with a doctrine event listener: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php. 
If you want more control you should implement this file yourself.
