### ISSUE TITLE
Docker tags for 0.11 beta

### ISSUE THREAD

**Issue by aurelijusrozenas** [dunglas/mercure#407]
Hey.
I wanted to ask couple of questions about mercure docker tags.
1. I see `legacy-v0.11` . Why is it legacy? It seems normal beta release in github.
2. I do not know how much automation is going on for docker tags but it seems to me that beta release should not be released as `v0`, `v0.11`, `latest` tags because I would assume it is save to upgrade when in reality it would be a beta release.

**Comment by dunglas** [comment]
Hi!

1. For the 0.11 version there are two flavors of the hub: the one using Caddy server, and the one using the old home made web server.  `legacy-v0.11` corresponds to the legacy server, `v0.11` to the Caddy based version. See for more information https://dunglas.fr/2020/11/the-mercure-rocks-hub-is-now-based-on-caddy-web-server/
2. You're right we need to tweak the GoReleaser config to not tag prereleases on Docker. I don't know if it's supported by GoReleaser (any help on this welcome).

**Comment by aurelijusrozenas** [comment]
1. You should include this link in release description in this repo, it's all I wanted to know about release and more! :) I never knew I could find this info on your web.

**Comment by dunglas** [comment]
Done!
