### ISSUE TITLE
Problems with CORS and private flag

### ISSUE THREAD

**Issue by CreaDEV** [dunglas/mercure#412]
Hello!

I have a web app with symfony provided by an normal apache2 server. Now I want to add SSE support (with docker).

First Problem: The new caddy auto cert wants to be on port 443...but there is my symfony app/apache2...
Possible solution: proxying the /.well-known/* to the port x of mercure instance (-p x:443)
Don't get this working: Workaround: I give my certificates from the symfony instance to the caddy server by configuration and disable auto certs by this

Second problem: If I change the CORS: * to the domain of my symfony instance plus port it is ignored by mercure
Possible solution: going on using the * wirdcard
But is this save?

Third problem: If I switch the publishing from private false to true no message arrive anymore at the client
No Solution.

Can anybody help with one of this problems? Perhaps this proxying will help with all problems but I dont know the exact apache directives to do this in a reliable and secure way.

Best Regards!

**Comment by CreaDEV** [comment]
I solved this issue with an proxy pass:
=============================

enable modules with apache2 (a2enmod):
* proxy
* proxy_html

In VHost:
=======

<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>

SSLEngine on
SSLProxyEngine On
SSLCertificateFile /etc/letsencrypt/live/<your site>/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/<your site>/privkey.pem

ProxyRequests Off
ProxyPreserveHost On
ProxyPass /.well-known https://localhost:19100/.well-known
ProxyPassReverse /.well-known https://localhost:19100/.well-known

**Comment by dunglas** [comment]
Using a reverse proxy is indeed a good solution! The other solution is to host the hub on a subdomain such as `hub.mysite.com`.
