### ISSUE TITLE
401 unable to parse JWT: key is of invalid type

### ISSUE THREAD

**Issue by alexislefebvre** [dunglas/mercure#414]
I'm trying to [authenticate](https://mercure.rocks/spec#authorization) with an header.

What I tried:

1. use https://github.com/Yaffle/EventSource/blob/master/src/eventsource.min.js to provide `EventSourcePolyfill` (it was suggested [here](https://github.com/whatwg/html/issues/2177#issuecomment-479016493))
2. and use it:

```js
const token = 'eyJ0eX…'

const url = new URL('http://localhost:8020/.well-known/mercure');
url.searchParams.append('topic', '*');

const eventSource = new EventSourcePolyfill(url, {
    headers: {
        'Authorization': 'Bearer ' + token
    }
});

eventSource.onmessage = function ({data}) {
    console.log(data);
};
```

The mercure hub returns a 401 status code.

Here is the corresponding error in logs:

> {"level":"info","ts":1607462490.1899827,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"urn:uuid:141f4c98-c48a-4fa6-a65e-00600366101f","last_event_id":"","remote_addr":"172.21.0.1:49934"},"error":"unable to parse JWT: key is of invalid type"}

I didn't tried the solution based on cookie yet.

---

https://github.com/api-platform/docs/issues/1050 may help to understand this mechanism

See also https://stackoverflow.com/questions/60786283/symfony-mercure-eventsource-dont-send-cookie

---

Previous description was about the documentation:

The [current documentation](https://mercure.rocks/spec#authorization) explains:

> To ensure that they are authorized, both publishers and subscribers must present a valid JWS ([RFC7515](https://tools.ietf.org/html/rfc7515)) in compact serialization to the hub.

~As a developer I'm reluctant to read 59 pages in order to understand what JWS is and how it works.~

I would appreciate if the documentation explained briefly what a JWS is, showed how to create one and pass it to the Mercure hub.

**Comment by dunglas** [comment]
Could you copy logs emitted by the Mercure hub please? It should detail why authorization failed.

**Comment by alexislefebvre** [comment]
> {"level":"info","ts":1607462490.1899827,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"urn:uuid:141f4c98-c48a-4fa6-a65e-00600366101f","last_event_id":"","remote_addr":"172.21.0.1:49934"},"error":"unable to parse JWT: key is of invalid type"}

**Comment by alexislefebvre** [comment]
The [example key](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.z5YrkHwtkz3O_nOnhC_FP7_bmeISe3eykAkGbAl5K7c) work, it's not rejected by the hub.

**Comment by dunglas** [comment]
I improved support for RSA keys, and added some docs: #425.
This should fix your issue, if it's not the case feel free to re-open!

**Comment by alexislefebvre** [comment]
Wow, thanks a lot! :clap:
