### ISSUE TITLE
Can't get RS256 to work

### ISSUE THREAD

**Issue by TamasSzigeti** [dunglas/mercure#419]
Hi, I wanted to try out the new release with the namespace fallback addition and can't get RS256 to work.
My suspicion was that I'm not passing in the multiline key properly, but I've tried multiple ways… 

My key and token is valid according to jwt.io. I also checked out the jwt-go repo and used my key and token in the tests and they pass OK.

I've read all the docs and can't get it right – This is what I think should work as caddy doc says everything between quotes is preserved:

```
        subscriber_jwt "
-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwI…
-----END CERTIFICATE-----
" RS256

```

And with legacy-v11 (docker-compose):
```
    environment:
            SUBSCRIBER_JWT_ALGORITHM: RS256
            SUBSCRIBER_JWT_KEY: |
                -----BEGIN CERTIFICATE-----
                MIIDETCCAfmgAwI…
                -----END CERTIFICATE-----
```

Both result in the same error:

```
unable to parse JWT: unable to parse PKIX public key: asn1: structure error: tags don't match (6 vs {class:2 tag:0 length:3 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ObjectIdentifier @2
```

When I go back to v10, it complains about passing array in aud claim, maybe that happens _after_ public key is already parsed?

I'm using HS256 for publishing and that works without a problem.

Any help appreciated 🙇‍♂️

**Comment by dunglas** [comment]
I improved supports for public/private keys and added some docs for this: #425
I hope this help.

**Comment by TamasSzigeti** [comment]
Sorry, it doesn't. Same:

```
mercure_1   | {"level":"info","ts":1608231224.554831,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"urn:uuid:cc360275-eafc-4e10-b122-45c92b443afe","last_event_id":"","remote_addr":"172.19.0.1:59738"},"error":"unable to parse JWT: unable to parse PKIX public key: asn1: structure error: tags don't match (6 vs {class:2 tag:0 length:3 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ObjectIdentifier @2"}
```

**Comment by TamasSzigeti** [comment]
Same error when I feed my keys into the new TestJWTPlaceholders

**Comment by TamasSzigeti** [comment]
I have the fix, will submit a PR soon
