### ISSUE TITLE
Multi-domain set Hub Url problem

### ISSUE THREAD

**Issue by darienicolae** [dunglas/mercure#431]
Hello, 

I have the followingi issue, i have a multi-tenant application in which the domain of the website is changing dynamically for each client. How is it posssible to set the mercure.hubs_default_url dynamically in order to have it to match for each tenant individually?

I tried something like: url: 'https://%router.request_context.base_url%:3000/.well-known/mercure', but this didnt work.

I see that in the __construct of symfony/mercure/Publisher.php, there is as an argument the hubUrls: public function __construct(string $hubUrl, callable $jwtProvider, HttpClientInterface $httpClient = null), however i dont find where this is called.

Also the mercure binary finaly has to have one address/hostname for running...how can that be set for multiple domains?
./mercure --jwt-key='Key' --addr='127.0.0.1:3000'

Is there any solution to load this dynamically somehow?

Thank you very much

**Comment by dunglas** [comment]
Hi @darienicolae, this should be reported in the issue tracker of the Symfony MercureBundle: https://github.com/symfony/mercure-bundle. This repo is only about the specification and the reference implementation. Could you reopen on this repo please?

Currently, parameters aren't resolved in this config entry. Maybe should we do it, this should fix your issue.

**Comment by darienicolae** [comment]
I will post the ticket in the Mercure Bundle. I found a workaround in the
meantime:
This way i can call the Publisher having the hubURL

$jwtProvider = new StaticJwtProvider($_ENV['MERCURE_JWT_TOKEN']);
$publisher = new Publisher($hubURL, $jwtProvider);
