### ISSUE TITLE
/.well-known/mercure/subscriptions 404 Not found

### ISSUE THREAD

**Issue by yurik94** [dunglas/mercure#435]
Hello, thanks for this awesome project.
I'm trying to use the docker image (currently 0.11 or 0.10) but even if I use the `Caddyfile.dev` with `subscriptions` enabled I always get a 404 Not found on:
`https://localhost/.well-known/mercure/subscriptions`

The Caddyfile.dev is untouched and the docker ps command launched is:
`"caddy run -config /etc/caddy/Caddyfile.dev"`

What's wrong?

**Comment by ip512** [comment]
Hi, I have the same issue with version 0.11 only. With same base code, subscription API works fine. If I change the version to 0.11, with the following config in a caddyfile, subscriptions api return a "404 Not found".
```
route {
    mercure {
        publisher_jwt *****
        subscriber_jwt *****
        cors_origins *
        subscriptions
    }
    respond "Not Found" 404
}
```
Any other features works fine (publish, subscribe)

I tested on v0.11.0-beta.2 and v0.11.0-rc.2

**Comment by dunglas** [comment]
I reproduced the issue. I'm working on a fix.

**Comment by yurik94** [comment]
@dunglas Thank you very much Kevin, awesome work!

**Comment by ip512** [comment]
Many thanks for the fix, I confirm it works perfectly with rc3
