### ISSUE TITLE
Load Issues

### ISSUE THREAD

**Issue by josephmiller2000** [dunglas/mercure#438]
For some reason, i can't figure it out, but mercure is not being stable.

**My server config:**

```
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-126-generic x86_64)
Ram: 16GB
CPU(s):              8
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) D-2123IT CPU @ 2.20GHz
Stepping:            4
CPU MHz:             2700.005
BogoMIPS:            4400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            8448K
NUMA node0 CPU(s):   0-7
````

Does mercure need parodic reboot or restart to keep it stable with all new subscriptions? 

Here is my live chat application, https://socket.chatzozo.com/ (NSFW) Which is now in a production mode, people reporting, there is a lag at certain period of time, which is causing message delay, or all messages from particular users shoot up at once in the room.

Could not figure out why mercure is acting strange, or it is related to something else?

**Comment by josephmiller2000** [comment]
Looks like it is related to https://github.com/dunglas/mercure/issues/388

Because i had high cpu usage and ram memory is almost eaten up.

**Comment by dunglas** [comment]
Hi, which version do you use?

**Comment by josephmiller2000** [comment]
v0.10.4

**Comment by dunglas** [comment]
Ok, coup you try to update to 0.11 RC 2? This issue has been fixed in this version.

**Comment by josephmiller2000** [comment]
Alright thanks, planning to do so, then i will update more info later.

**Comment by josephmiller2000** [comment]
Ok, now using 0.11 RC 2 version. And check the screenshot, is this normal? does it takes these much of memory to run?

![Snap_Shot_01621](https://user-images.githubusercontent.com/24210340/105612030-1bc64180-5ddf-11eb-93cd-42dad6ed3db5.png)
![Snap_Shot_01622](https://user-images.githubusercontent.com/24210340/105612034-1cf76e80-5ddf-11eb-873b-c858bd613d3f.png)

**Comment by dunglas** [comment]
This issue has been fixed in the rc3 (and in the stable version).

**Comment by josephmiller2000** [comment]
After digging more for the cause of this issue, i have found that mercure is reconnecting itself, and sending all subscriber users all the pending and old messages, if there is a drop in connection or some other issue, which slow downs the process of mercure, and it is being tooo laggy for chatters who use our production application.

**Comment by dunglas** [comment]
You can switch to the local transport to disable history totally.
However it looks like a bug in the client you use, because by the spec the client must pas the event of the last of it received when reconnecting, and Mercure will only send messages broadcasted since this message.

Do you have some logs to provide (especially the URLs and HTTP headers used when reconnecting)? I would like to see what happens exactly.

**Comment by josephmiller2000** [comment]
Ok sure, let me send you the link of the application directly to your twitter DM ? or through email. So you can check and confirm it. Thanks.
