### ISSUE TITLE
Intermittently error 502 - nginx

### ISSUE THREAD

**Issue by tebaly** [dunglas/mercure#445]
Hello. Intermittently error 502 - nginx
```
no live upstreams while connecting to upstream, client: ...
and
connect() to [::1]:1337 failed (101: Network is unreachable) while connecting to upstream, client:
```
Runs through the supervisor in a single process. No error in logs.
Configured according to: https://mercure.rocks/docs/hub/cookbooks

```
server {

	server_name
		some-site.com;

    location / {
        proxy_pass http://localhost:1337/.well-known/mercure;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
#        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificates ...

} 
```

**Comment by dunglas** [comment]
Which version of Mercure are you using?

**Comment by tebaly** [comment]
Last stable https://github.com/dunglas/mercure/releases/download/v0.10.4/mercure_0.10.4_Linux_x86_64.tar.gz

**Comment by tebaly** [comment]
All 502 from mercure. No errors in mercure log
![image](https://user-images.githubusercontent.com/9466814/104508502-5f5bc700-55f9-11eb-87a1-ad5b38ff86f4.png)
![image](https://user-images.githubusercontent.com/9466814/104508630-929e5600-55f9-11eb-944a-ef9751807f23.png)
![image](https://user-images.githubusercontent.com/9466814/104508719-b366ab80-55f9-11eb-97a2-40c57fd32fa4.png)
![image](https://user-images.githubusercontent.com/9466814/104508769-c4172180-55f9-11eb-88ab-7b685e290074.png)

**Comment by dunglas** [comment]
Could you try the latest RC? We fixed some bugs that may be related.

**Comment by tebaly** [comment]
Good. Thanks. I'll try

**Comment by tebaly** [comment]
I tried https://github.com/dunglas/mercure/releases/download/v0.11.0-rc.3/mercure-legacy_0.11.0-rc.3_Linux_x86_64.tar.gz
It did not help. 

How can i catch the error process? No errors in mercure log

**Comment by dunglas** [comment]
You can try to enable the debug mode, but I wonder if it's a problem with Mercure or with NGINX.

To enable the debug mode with the RC, simply set the `DEBUG` env var to 1.

**Comment by tebaly** [comment]
`DEBUG	mercure/subscriber.go:177	Subscriber has not subscribed to this update`

The log does not contain any ERROR or CRITICAL - even when debugging is enabled

I use Symfony (and api-Platform https://api-platform.com/docs/core/mercure/ - But sending messages manually)

```php
use Symfony\Component\Mercure\PublisherInterface;
use Symfony\Component\Mercure\Update;

class EventPuplisher
{
    public function __construct($subscribeUrl, PublisherInterface $publisher)
    {
        $this->subscribeUrl = $subscribeUrl;
        $this->publisher = $publisher;
    }

    public function publish($resource, $data = [])
    {
        $update = new Update("{$this->subscribeUrl}/$resource", json_encode($data));
        call_user_func($this->publisher, $update);
    }
}
```

**Comment by tebaly** [comment]
Perhaps the some global NGINX settings are not suitable for proxying Mercure? 
Timeouts?.. Something from this

```
    sendfile    on;
    tcp_nopush  on;
    tcp_nodelay on;

    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;

    keepalive_timeout  15;
    keepalive_requests 1000;

    send_timeout 30;

    client_body_timeout  30;
    client_max_body_size 16M;

    reset_timedout_connection on;

**Comment by tebaly** [comment]
https://stackoverflow.com/questions/49767001/how-to-solve-nginx-no-live-upstreams-while-connecting-to-upstream-client/49783716

> This caused the upstream request to use the IP4 localhost IP or the IP6 localhost IP, but every now and again, it would use the localhost DNS without the port number resulting in the upstream error as seen in the logs below.

![image](https://user-images.githubusercontent.com/9466814/104658928-ce5a1e00-56d4-11eb-9e2a-b1e1e69636f0.png)
