### ISSUE TITLE
Weird error while installing Mercure : invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined

### ISSUE THREAD

**Issue by ValentinJD-Pro** [dunglas/mercure#450]
But the command that i used to run it is the right one 
from https://mercure.rocks/docs/hub/install 

(I'm trying to run it on windows)

So when i run  : $env:MERCURE_PUBLISHER_JWT_KEY='!ChangeMe!'; $env:MERCURE_SUBSCRIBER_JWT_KEY='!ChangeMe!'; .\mercure.exe run -config Caddyfile.dev

I just get : invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined

**Comment by dunglas** [comment]
Area you using version 0.11? It looks like you have a binary supporting the old configuration format.

**Comment by saifgo** [comment]
you could execute this command instead it worked for me
`./mercure --jwt-key=’!ChangeMe!’ --addr=’localhost:3000’ --allow-anonymous --cors-allowed-origins=’*’`

**Comment by develth** [comment]
Same for me when using [this version](﻿https://github.com/dunglas/mercure/releases/download/v0.14.1/mercure-legacy_0.14.1_Linux_x86_64.tar.gz) and want to go through the docs

**Comment by dunglas** [comment]
Are you using the legacy build?

**Comment by develth** [comment]
i had a fresh ubuntu 22.04, installed caddy via apt, then removed it with purge and gone through the [docs](https://mercure.rocks/docs/hub/install) that mentioned to go to release page
