### ISSUE TITLE
Is there any idle time out?

### ISSUE THREAD

**Issue by josephmiller2000** [dunglas/mercure#454]
For some reason, people in my chat application keep reporting the application is not responding or not able to see any new messages until they refresh the chat page.

After looking logs, there is no issue or error. After concluding, there could be some timeout happening after people switch to other tabs or idle for more than 30 minutes or so.

So just want to make sure is there any idle timeout for subscribers? 

Version : v0.11.0-rc.2

**Comment by dunglas** [comment]
Browsers usually close the connection after some idle time, but they reconnect automatically. Do you see something in the console of the browsers?

**Comment by josephmiller2000** [comment]
No i don't see any console errors in the browsers.

**Comment by josephmiller2000** [comment]
Closing this, there was some timout limit enabled with mercure starup program. Increased the time, planning to set it as 0s
