### ISSUE TITLE
How to pin caddy build on particular version?

### ISSUE THREAD

**Issue by lars-feyerabend** [dunglas/mercure#455]
Hey there,

I'm trying to include Mercure in a project similar to api-platform/api-platform or dunglas/symfony-docker, i.e. with a custom-built Caddy as main web server.

However, unlike the examples above, I would really like to pin Mercure to a specific version because we've been bitten by an unintended upgrade before (the breaking changes in 0.10).

My Dockerfile looks like this:

```Dockerfile
FROM caddy:2-builder-alpine AS symfony_caddy_builder

RUN xcaddy build \
    --with github.com/dunglas/mercure/caddy@v0.11.0
```

However, when running `docker-compose build`, I get the following error.

```
2021/01/20 07:22:14 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/dunglas/mercure/caddy@v0.11.0
go: downloading github.com/dunglas/mercure v0.11.0
go get github.com/dunglas/mercure/caddy@v0.11.0: module github.com/dunglas/mercure@v0.11.0 found, but does not contain package github.com/dunglas/mercure/caddy
2021/01/20 07:22:15 [FATAL] exit status 1
```

Adding `--with github.com/dunglas/mercure@v0.11.0` before or after does not help either. Using simply `--with github.com/dunglas/mercure/caddy@main` will result in a successful build however. But there's only a slight doc change between main branch and the v0.11.0 tag?! Am I missing something about how to define a version? Should this be possible at all?

**Comment by ngrie** [comment]
I am experiencing the same issue with v0.11.0. However, pinning the current v0.11.3 works. Looks like a problem with this specific version I assume.
