### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by viccvanco** [dunglas/mercure#459]
Hi, 

I try Mercure latest release, I extracted mercure_0.11.0_Linux_x86_64.tar.gz on a subdirectory mercure/ in my project directory on Debian 10 with apache 2, then when I launch the command ./mercure run -config Caddyfile.dev I've got this message:

2021/01/29 14:08:22.734 INFO    using provided configuration    {"config_file": "Caddyfile.dev", "config_adapter": ""}
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use

How can I solve that?

Thank you.

**Comment by dunglas** [comment]
Hi,

You have a process already using the port `2019`. You must kill it to start Mercure or change the admin port of Mercure using the `admin.listen` option: https://caddyserver.com/docs/json/admin/
