### ISSUE TITLE
Can we subscribe all topics allowed by the JWT?

### ISSUE THREAD

**Issue by Savageman** [dunglas/mercure#46]
Hi,

Is there a way to subscribe to all topics? (within the limitation of what the JWT allows, of course)
Essentially, I'd like the topic parameter to be optional or being able to use the wildcard when listening:

    let url = new URL('http://localhost/hub');
    url.searchParams.append('topic', '*');
    let eventSource = new EventSource(url.toString(), {withCredentials: true});

Right now, my page load generates the mercureAuthorization JWT with a few topics (this is how I restrict the clients), but I looks like I also need to append all the topics I have listed in my JWT to the Event source URL, which feels like duplicating.

**Comment by dunglas** [comment]
As should be able to use a templated URI that match all the paths to achieve this.

**Comment by dunglas** [comment]
So the following should do the trick.

```javascript
const url = new URL('http://localhost/hub');
url.searchParams.append('topic', 'http://{domain}/{+anything}');
const eventSource = new EventSource(url.toString(), {withCredentials: true});
```

**Comment by Savageman** [comment]
So if I use URI as topics, it will work? I'll definitely try it tonight (right now my topic names are just words)

**Comment by dunglas** [comment]
Topics must be URI (as described in the spec).

**Comment by Savageman** [comment]
I definitely overlooked that, thanks.
