### ISSUE TITLE
Invalid JWT signature

### ISSUE THREAD

**Issue by Julienblc** [dunglas/mercure#462]
Hello all,

I try my first mercure server, but I have a problem very soon.

Here I launch the mercure server : 

<img width="1305" alt="Capture d’écran 2021-02-05 à 19 18 04" src="https://user-images.githubusercontent.com/7222986/107073131-40f77e80-67e7-11eb-9ef0-8bd85316b34a.png">

The server is launched, good. Then I create a JWT : 

<img width="1191" alt="Capture d’écran 2021-02-05 à 19 21 21" src="https://user-images.githubusercontent.com/7222986/107073208-5b315c80-67e7-11eb-9a81-b9bd4befd927.png">

Ok, then I user Postman to send a POST : 

<img width="1150" alt="Capture d’écran 2021-02-05 à 19 18 48" src="https://user-images.githubusercontent.com/7222986/107073361-95026300-67e7-11eb-974f-eb336ae27394.png">

<img width="1066" alt="Capture d’écran 2021-02-05 à 19 22 44" src="https://user-images.githubusercontent.com/7222986/107073335-87e57400-67e7-11eb-904d-8595060c53cb.png">

<img width="1078" alt="Capture d’écran 2021-02-05 à 19 19 04" src="https://user-images.githubusercontent.com/7222986/107073380-99c71700-67e7-11eb-89cb-1471bb17b518.png">

BUT I have a problem, the server send me back `Unauthorized`

Here a screenshot of the logs : 

<img width="1434" alt="Capture d’écran 2021-02-05 à 19 19 16" src="https://user-images.githubusercontent.com/7222986/107073442-ac415080-67e7-11eb-855a-ddf50d52f4c5.png">

I can see the error `unable to parse JWT: signature is invalid` . What have I done wrong ?

Thank Dunglas btw for mercure 👍

**Comment by Xusifob** [comment]
How is your configuration ? 

Have yo usigned your JWT Token with your "publishKey" as well ?

**Comment by AlexandreCln** [comment]
Hello ! I have the same problem, did anyone solve it?
