### ISSUE TITLE
0.11 introduced a timeout issue

### ISSUE THREAD

**Issue by bpolaszek** [dunglas/mercure#464]
Hello there,

It seems that the Caddy-flavoured 0.11 introduced a regression regarding timeouts. Even if I set `write_timeout ` and `dispatch_timeout ` to 0 (by env var or directive), a listener gets disconnected [precisely 9:30 || precisely 10 minutes]* after subscribing:

```javascript
eventSource.addEventListener('open', evt => {
  const now = new Date();
  console.log(`Connection open at: ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`);
});

eventSource.addEventListener('error', evt => {
  const now = new Date();
  console.log(`Connection error at: ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`);
});
```
<img width="742" alt="Capture d’écran 2021-02-11 à 17 32 34" src="https://user-images.githubusercontent.com/5569077/107666812-33cb0b80-6c8f-11eb-94d6-15f83fe970dd.png">

Even if reconnection is automatic, it messes with the subscription API, because the hub keeps sending disconnection/reconnection events.

One could think that the browser is responsible for those disconnections, but they did not happen with 0.10, and I can reproduce with a similar PHP listener:

<img width="283" alt="Capture d’écran 2021-02-11 à 17 32 48" src="https://user-images.githubusercontent.com/5569077/107666836-3a598300-6c8f-11eb-9f25-0edfdf677dc0.png">

I tried serving the [mercure PHP hub](https://github.com/bpolaszek/mercure-php-hub) with Caddy as reverse proxy and did not observe a timeout after more than 10min, so I'm not sure it's caddy-related.

Any ideas?

_* Yeah, that's pretty weird, but I observed both periods._

**Comment by CreaDEV** [comment]
Same here with following setup:
- docker image dunglas/mercure:v0.11

Subscribers get disconnected automatically after 10 minutes. Setting `write_timeout` to 0 seems to have no effect.

**Comment by dunglas** [comment]
I reproduced the issue, I'm working on a fix.

**Comment by dunglas** [comment]
Did you set `write_timeout` to `0` or to `0s`?

**Comment by bpolaszek** [comment]
I actually tried both, none helped 😕

**Comment by dunglas** [comment]
#469 should fix the issue! Could you give it a try? Thanks!

**Comment by bpolaszek** [comment]
Tested and approved! 🙏

**Comment by bpolaszek** [comment]
Thank you @dunglas.

**Comment by mm-motork** [comment]
I have a similar issue with `dunglas/mercure:v0.14.5`. The subscriber reconnects frequently and I see a lot of disconnection logs with empty `last_event_id`. Any suggestion? Setting custom `heartbeat` and `write_timeout` or disabling them with `0s` makes no difference.
