### ISSUE TITLE
Json Web Token clarification needed

### ISSUE THREAD

**Issue by Spomky** [dunglas/mercure#47]
According to the specification, the authentication [is based on JWT](https://tools.ietf.org/html/draft-dunglas-mercure-03#section-5.1).

In [the PHP implementation](https://github.com/symfony/mercure/blob/master/src/Publisher.php#L117), the encrypted tokens (JWE) are always rejected.

In their compact form, [JWE have 5 base64url parts separated by dots](https://tools.ietf.org/html/rfc7516#section-7.1). Signed tokens (JWS) [have 3 parts](https://tools.ietf.org/html/rfc7515#section-7.1).

The specification should clarify if only JWS are accepted or if both JWS/JWE (i.e. [Nested tokens](https://tools.ietf.org/html/rfc7519#section-2)) can be used.

**Comment by dunglas** [comment]
Currently, only JWS can be used. This is explicitly stated in the spec:

>    To ensure that they are authorized, both publishers and subscribers
   must present a valid JWS [RFC7515] in compact serialization to the
   hub.  This JWS SHOULD be short-lived, especially if the subscriber is
   a web browser.  A different key MAY be used to sign subscribers' and
   publishers' tokens.

However, if there is a use case, we can update the spec to support JWE.
