### ISSUE TITLE
Expected behavior for tokens with `exp` claim?

### ISSUE THREAD

**Issue by ssi-anik** [dunglas/mercure#472]
I generated a subscriber token setting the `exp` claim. It correctly throws 401. But when it gets connected, even after expiry, events get streamed thru the connection. Should it be expected behavior?

**Comment by dunglas** [comment]
Currently, it is. The token is checked only at connection time. But maybe could we change that.
If you need to disconnect the user when the token expires, you can set a short `write_timeout` value.

**Comment by ssi-anik** [comment]
I was experimenting the mercure and I came across the scenario. Thanks anyway.
