### ISSUE TITLE
MIME type ("text/html") that is not "text/event-stream"

### ISSUE THREAD

**Issue by drychlik76** [dunglas/mercure#478]
Experiencing an odd issue with the mercure hub.  I am using EventSource js object to receive the updates from the mercure hub that are published by a symfony controller.  I have not found a solution for this issue.  

`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`

```
        const url = new URL('http://localhost:4000/.well-known/mercure/ui/');
        url.searchParams.append('topic', 'http://127.0.0.1:8000/admin/attributes/addNew/');

        const eventSource = new EventSource(url);
        eventSource.onmessage = event => {
            console.log(JSON.parse(event.data));
        }
```

mercure hub version _11

This is the response headers coming from the HUB.  It doesn't make sense to me.  I read the specification and understand that the headers sent from the go source code is appropriate.  Not sure what's going on here.  Its confusing.  

![Screen Shot 2021-03-04 at 2 04 04 PM](https://user-images.githubusercontent.com/20803057/110023238-904fa280-7cf2-11eb-9592-7299a97ffc55.png)

**Comment by drychlik76** [comment]
I'm assuming its coming from the mercure hub.

**Comment by dunglas** [comment]
`const url = new URL('http://localhost:4000/.well-known/mercure/ui/');` should `const url = new URL('http://localhost:4000/.well-known/mercure');`.

With current snippet the browser tries to load the debugger (an HTML page) instead of the SSE endpoint.

**Comment by drychlik76** [comment]
:slaps-head:  Thank you Dunglas.  That did it.  It's always something simple.
