### ISSUE TITLE
How to publish to a group of non-specific targets ?

### ISSUE THREAD

**Issue by Ilshidur** [dunglas/mercure#48]
This is more a question about the protocol itself than about this implementation.

**Here's a use case I ran into :**

A specific user (using a Browser) subscribes to this topic : `http://example.com/books/{id}`.
I want this user to get notifications about **all** books.

**Question :**

What do I have to store inside the claims of his JWT to say they should receive notifications about **all** the books ? My (theoretical) workaround is this :

```json
{
  "mercure": {
    "subscribe": [
      "http://example.com/books/*"
    ]
  }
}
```

Then I dispatch an event to the topic `http://example.com/books/ID_OF_BOOK` and these targets : 
- `http://example.com/books/*` : so this particular user can get the notification
- `http://example.com/books/ID_OF_BOOK` : so the other users can also receive the notification, as their allowed targets are : `["http://example.com/books/ID_OF_BOOK"]`.

Maybe should I find an other way and use targets specifying the users instead of specifying the books ?

**Comment by dunglas** [comment]
Hi,

Topics and targets aren't directly related. You have several solutions:

* set something like `books_admin` in `mercure.subscribe`, and include this target (with others if you want to) in all books you POST.
* set `*` in `mercure.subscribe`, then the subscriber will be a sort of superadmin and will have access to all updates, for all topics

**Comment by Ilshidur** [comment]
Thank you for the answer. I figured the 1st solution and it worked nicely.
