### ISSUE TITLE
SSL problems with own certificate 

### ISSUE THREAD

**Issue by adares2** [dunglas/mercure#481]
I have a Docker Symfony Nginx Php Mercure Stack. I updated the Mercure Image to the new Caddyserver.  
I want to use my own certificate for Mercure.
I configured the Server with the following settings:

The docker-compose file:
```  

mercure:
    container_name: mercure
    image: dunglas/mercure
    environment:
        DEBUG: debug
        SERVER_NAME: example.com
        MERCURE_PUBLISHER_JWT_ALG: HS256
        MERCURE_PUBLISHER_JWT_KEY: secret
        MERCURE_SUBSCRIBER_JWT_ALG: HS256
        MERCURE_SUBSCRIBER_JWT_KEY: secret
        PUBLISH_ALLOWED_ORIGINS: https://example.com
        CORS_ALLOWED_ORIGINS: https://exemple.com
    ports:
      - "4001:443"

    volumes:
       - ./hub/Caddyfile:/etc/caddy/Caddyfile
       - ./ssl:/ssl
       - caddy_data:/data
       - caddy_config:/config
 ```

and the Caddyfile
```{

 {$DEBUG}
    # HTTP/3 support
    servers {
        protocol {
            experimental_http3
        }
    }
}

{$SERVER_NAME}

tls /ssl/example.pem   /ssl/example.com.key

route {
    encode zstd gzip

    mercure {
        log
        demo
        # Transport to use (default to Bolt)
        transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
        # Publisher JWT key
        publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
        # Subscriber JWT key
        subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
        # Extra directives
        {$MERCURE_EXTRA_DIRECTIVES}
         # CORS
        cors_origins {$CORS_ALLOWED_ORIGINS}
        publish_origins {$PUBLISH_ALLOWED_ORIGINS}
    }
    respond /healthz 200

    respond "Not Found" 404
}
```
The Caddyserver is reachable under https://example.com:4001/.well-known/mercure. The SSL seams to work.
But when Symony tries to connect with mercure - Php throws following error

`
PHP message: [critical] Uncaught PHP Exception Symfony\Component\HttpClient\Exception\TransportException: "SSL peer certificate or SSH remote key was not OK for "https://example.com:4001/.well-known/mercure"." at /var/www/site/vendor/symfony/http-client/Chunk/ErrorChunk.php
`

And Mercure logged
`
{"level":"debug","ts":1615292880.9723547,"logger":"http.stdlib","msg":"http: TLS handshake error from 172.30.0.1:52318: local error: tls: bad record MAC"}
`

The Browser also failed to subscribe because there is no autorization:
Mercure logged
`
 {"level":"info","ts":1615292822.5305266,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"urn:uuid:c76d0bb7-3ae9-4e6b-81fc-ef8b9121eeab","last_event_id":"","remote_addr":"95.90.245.182:39058"}}
`

I don't know where the problem is. Perhaps i forgot a Symfony or PHP enviroment variable?

**Comment by dunglas** [comment]
It's because the self-generated certificate isn't trusted by PHP.

You have several options:

* use the native Mercure hub provided shipped by Symfony CLI (`https://localhost:8000/.well-known/mercure`)
* add the self-signed certificate to the PHP bundle: [extract the local authority generated by Caddy](https://caddyserver.com/docs/automatic-https#local-https) and add it to the bundle use by curl in your `php.ini` (`curl.cainfo = /your/custom/cacert.pem`)
* disable HTTPS locally (don't do that in production) using the `SERVER_NAME` environment variable (https://mercure.rocks/docs/hub/install).
