### ISSUE TITLE
OPTIONS - 405 Method Not Allowed

### ISSUE THREAD

**Issue by nuvolapl** [dunglas/mercure#482]
When I subscribe a topic via js [EventSource](https://www.npmjs.com/package/eventsource) I have an issue with OPTIONS method request. Specifically - "405 Method Not Allowed".

**Comment by dunglas** [comment]
Do you have a reproducer? Can you share the domains you use for the app and for the hub (are they on the same top domain)? Can you also share your JS code?

**Comment by nuvolapl** [comment]
There are different subdomain for app and mercure hub but yes, they have the same top domain.

### sample code
```js
// https://app.foo.com/

const url = new URL('https://events.foo.com/.well-known/mercure');

url.searchParams.append('topic', 'https://api.foo.com/resources/resource');

const sse = new EventSource(url.toString(), {
    headers: {
        Authorization: `Bearer FooBar`,
    },
});
```

https://events.foo.com - is the "dunglas/mercure:v0.11" docker image running on AWS ECS behind the AWS ELB.
There is also "CORS_ALLOWED_ORIGINS" environment variable set up with "https://app.foo.com" value.

**Comment by dunglas** [comment]
This is most likely related to your ELB or reverse proxy configuration. I created a repository to try to reproduce the problem, but everything looks ok Mercure-side: https://github.com/dunglas/mercure-reproducer-cors (see also the `nginx` branch for a NGINX-based config).

Could you try to open a PR to this repository with a reproducer?

**Comment by nuvolapl** [comment]
@dunglas https://github.com/dunglas/mercure-reproducer-cors/pull/1 - here you go ;-)

**Comment by dunglas** [comment]
Hi @nuvolapl, thanks for the reproducer! It was a config issue. I opened a PR on your fork: https://github.com/nuvolapl/mercure-reproducer-cors/pull/1/files

Cheers

**Comment by nuvolapl** [comment]
@dunglas Thanks a lot!

Ps. Consider to mention about deprecated / removed "CORS_ALLOWED_ORIGINS" environment variable in docs.

**Comment by dunglas** [comment]
AFAIK, this environment variable is only mentioned in the "legacy build" section and in the upgrade guide.
