### ISSUE TITLE
Distinct cookies for a single application from the same browser session

### ISSUE THREAD

**Issue by MatthiasDesrumaux** [dunglas/mercure#483]
I have a question about multi-client apps.

I have a setup like this one:
- A single API/Front Platform with a reverse proxy who handle multiple host for this application. They share the same domain.
- a single Mercure hub, which is on the same domain.

I want to make the mercure cookie distinct for each host.
Today the cookie is send like this:
`ApiA.domain.com -> FrontA.domain.com -> mercure.domain.com`
But if we stay like this, the cookie could be used by another Front than the wanted one.

**Comment by dunglas** [comment]
It's not supported currently. What you could do however is to use CNAMEs to associate multiple domains to the same hub fo you can have `api-a.domain.com` -> `mercure-a.domain.com` and `api-b.domain.com` -> `mercure-b.domain.com` (but under the hood both domain point to the same hub).

**Comment by MatthiasDesrumaux** [comment]
Okey. Thank you i think i gonna create a reverse proxy with nginx to do that. This way i am using two cname by app (I have a restriction on cname count).

**Comment by dunglas** [comment]
This is now supported: #563
