### ISSUE TITLE
How to use Symfony Mercure with http ?

### ISSUE THREAD

**Issue by GaylordP** [dunglas/mercure#485]
Hello and thanks you for your library.

I want to use Mercure in my Symfony 5.2 project, I installed it with `composer require mercure`.
I can access my project thanks to `192.168.0.24:8080` ; no `localhost` and no `https`.

I'm trying to get Mercure to work locally over HTTP but I can't. I searched a lot on google and even asked on Stackoverflow and a French forum, without finding an answer. :/

On my project, I created a quick test page but i have this error when I try to access it from a browser _(but http://192.168.24:3000/.well-known/mercure` works well, the page is accessible)_ :

    > HTTP/1.1 401 Unauthorized returned for "http://192.168.0.24:3000/.well-known/mercure".

    /**
     * @Route(
     *     "/test",
     *      name="test",
     *     methods="GET"
     * )
     */
    public function index(PublisherInterface $publisher): Response
    {
        $update = new Update(
            'http://example.com/books/1',
            json_encode(['status' => 'OutOfStock'])
        );

[The documentation mentions that SSL is enabled by default](https://mercure.rocks/docs/hub/config), which I don't want in dev.

So here is my `CaddyFile.dev` :

    # Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
    {
        # Debug mode (disable it in production!)
        {$DEBUG:debug}
        # HTTP/3 support
        servers {
            protocol {
                experimental_http3
            }
        }
    }

    {$SERVER_NAME:192.168.0.24:8080} # I added this (original : "{$SERVER_NAME:localhost}")

    log

    route {
        redir / /.well-known/mercure/ui/
        encode zstd gzip

        mercure {
            # Transport to use (default to Bolt)
            transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
            # Publisher JWT key
            publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
            # Subscriber JWT key
            subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
            # Permissive configuration for the development environment
            cors_origins * # same error with "cors_origins http://192.168.0.24:8080"
            publish_origins *
            demo
            anonymous
            subscriptions
            # Extra directives
            {$MERCURE_EXTRA_DIRECTIVES}
        }

        respond /healthz 200

        respond "Not Found" 404
    }

This is my `.env.dev.local` file (`env=dev` is mentioned in `.env` file)` :

    MERCURE_PUBLISH_URL=http://192.168.0.24:3000/.well-known/mercure
    MERCURE_JWT_TOKEN=xxxx (Generated with http://jwt.io)

The line I run for starting mercury :

    SERVER_NAME=:3000 MERCURE_PUBLISHER_JWT_KEY=myphrase MERCURE_SUBSCRIBER_JWT_KEY=myphrase ./mercure/mercure run -config ./mercure/Caddyfile.dev

Many thanks in advance for your help

**Comment by dunglas** [comment]
Are you using Symfony CLI? If yes, it's a known issue with Symfony CLI and you should use another web server (like `php -S localhost:8000` in the meantime.

See https://github.com/symfony/cli/issues/424.

**Comment by GaylordP** [comment]
Thanks for your reply :)

No, I don't use Symfony CLI (no `symfony server:start`)

I use local virtual host with Apache on Apple Mac M1.

Thanks in advance if you have any other suggestions

**Comment by dunglas** [comment]
It looks like the ports in your config and in the Caddyfile don't match `3000` and `8080`. Is it intended?

**Comment by momo998-max** [comment]
Environment variable not found: "MERCURE_PUBLIC_URL".
