### ISSUE TITLE
How to send an event to a specific user?

### ISSUE THREAD

**Issue by flug** [dunglas/mercure#49]
an element may be missing or I'm doing it wrong: 
I have a topic: ```?topic=notifications```
I have a token creation with these parameters: 
```
{
  "mercure": {
    "subscribe": [
      "ff9c12f4-35f5-4b0d-b005-048fa029c285"
    ]
  }
}
```
I have a command that will give me notifications to this user, so my token looks like this: 
```
{
  "mercure": {
    "publish": [
      "ff9c12f4-35f5-4b0d-b005-048fa029c285"
    ]
  }
}
```

out even if I put another target my user still receives the notifications.

How can I make sure that several users with topic notification can have this notification and not the neighbor's?

**Comment by dunglas** [comment]
It's a very weird behavior, that shouldn't happen. Can you paste the `POST` request you send to the hub please?

**Comment by dunglas** [comment]
Closing as inactive. Feel free to reopen if you get more details.
