### ISSUE TITLE
How to change the log level

### ISSUE THREAD

**Issue by JoergSommer** [dunglas/mercure#494]
Hello!

I try to change the log level of the mercure server (I'm using docker dunglas/mercure:v0.11.1). Can not find any solutions:
* debug and demo from mercure itself seem to be false by default
* caddy log directive set to:
   log {
       level WARN
   }

Howevery, all log msg are still displayed. Debug and Info too.

What can I do?

Best regards
Sommer

**Comment by JoergSommer** [comment]
Updating to v0.11.2 does not help

**Comment by JoergSommer** [comment]
Problem seems to be uber.zap. NewProduction is by default INFO, NewDevelopment is by default DEBUG. You should use BasicConfiguration, I guess.

https://pkg.go.dev/go.uber.org/zap#hdr-Choosing_a_Logger

**Comment by divine** [comment]
Hello,

Related https://github.com/dunglas/mercure/issues/384 https://github.com/dunglas/mercure/issues/384

Basically, the reason is that currently, Caddy doesn't support defining global error level - the configuration file needs to be modified manually.

The good news is that the new version of Caddy which is in a beta already has it: https://github.com/caddyserver/caddy/pull/4028

Thanks!

**Comment by divine** [comment]
Caddy's new version (2.4.0) was released, you can now define the global default logging option:

```
{
    # Debug
    {$DEBUG}
    # HTTP/3 support
    servers {
        protocol {
            experimental_http3
        }
    }
    log {
       level WARN
    }
}
```

This issue might be closed now.

Thanks!

**Comment by si14** [comment]
@dunglas the latest Mercure release (0.12.0) is still based on pre-2.4.0 Caddy. Do you think it might be updated at some point?

**Comment by dunglas** [comment]
Yes it will when I'll tag a new version. In the meantime you can build from sources using `xcaddy` if needed.

**Comment by melroy89** [comment]
Is the log level still in the global section??

Please document this better on your official docs site.
