### ISSUE TITLE
Run Symfony with Mercure and apache on production;

### ISSUE THREAD

**Issue by AmsiVolv** [dunglas/mercure#495]
Hi, i have a symfony app and i'm using Mercure. 

To run Mercure i use this command 

`SERVER_NAME=:3000 MERCURE_PUBLISHER_JWT_KEY='something' MERCURE_SUBSCRIBER_JWT_KEY='something' CORS_ALLOWED_ORIGINS=https://my-domain.cz ALLOW_ANONYMOUS=1 ./mercure run -config Caddyfile`

- I have installed SSL certificate from Let's encrypt authority.
- My apache: 
                                                                              
<VirtualHost *:80>
....    
ProxyRequests off
    <LocationMatch /mercure>
      ProxyPass http://localhost:3000
      ProxyPassReverse http://localhost:3000
    </LocationMatch>
...
RewriteCond %{SERVER_NAME} =my-domain.cz
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

</VirtualHost>

Issue. When i'm trying to subscribe some topic a receive this error
GET https://my-domain.cz:3000/.well-known/mercure?topic=someGoodTopic net::ERR_SSL_PROTOCOL_ERROR
If i will try to get this URL from browser i will get the same issue, but if i will try to use http:// everything will be OK, but unfortunately i can't make request for http from my https domain. 
(Mixed Content: The page at 'https://my-domain.cz/' was loaded over HTTPS, but requested an insecure EventSource endpoint 'http://my-domain.cz:3000/.well-known/mercure?topic=someGoodTopic'. This request has been blocked; the content must be served over HTTPS.)

I will be glad if someone can help me =)

**Comment by gbrle** [comment]
Même problème :(

**Comment by dunglas** [comment]
It looks like your Apache server isn't configured to proxy Mercure when using HTTPS (the `*:80` part).

Be sure that:

1. The Mercure hub uses HTTP (not HTTPS)
2. The Apache proxy uses HTTPS (not HTTP)

**Comment by gbrle** [comment]
Merci pour votre réponse @dunglas :),
Mais je ne suis pas sur de bien comprendre.
Je dois désactiver mon port :80 (http) pour l'assigner à l'adress du hub mercure ?

Auriez vous un exemple de configuration apache ?

Merci beaucoup, vous me feriez gagner un temps énorme :)

**Comment by dunglas** [comment]
Non, il faut configurer Apache en mode proxy pour "forwarder" les requêtes au hub Mercure (qui doit écouter sur un autre port).

Je n'ai pas de config Apache sous la main (je n'utilise que rarement ce serveur web) mais j'essaierai d'ajouter un exemple au site avec Apache dès que j'aurai un peu de temps.

**Comment by aniskasmi** [comment]
Bonjour, 

J'ai toujours le même problème sur un machine debian 11 voici ma condig docker-compose 

```
 mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.81G1cMmtFMhvHG0LxQdJ51JxjMu0mYcu1zf5gvC3mnQ'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyIqIl19fQ.xUZYCpafRKMmsd3KycHRxBX_4hjpwMvWj9O3vOumOpg'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://mds-solutions.dev:8890
        cors_origins https://new.mdsolutions.app
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - 8001:80
    volumes:
      - mercure_data:/data
      - mercure_config:/config
