### ISSUE TITLE
[Question] QUIC Protocol / HTTP3

### ISSUE THREAD

**Issue by rogeriolino** [dunglas/mercure#497]
hey @dunglas,

I'm testing mercure and I'm getting QUIC ERR messages on console after a while, and after that the client stops to receive messages.

I've fixed it enabling QUIC support in my Chrome, but I'm curious about the experimental HTTP3 usage in CaddyFile:
https://github.com/dunglas/mercure/blob/main/Caddyfile#L7-L9

Is that mandatory for mercure works properly or I can switch to HTTP2?

Regards

**Comment by dunglas** [comment]
You can (and should in production) switch to HTTP/2. HTTP/1.1 is supported as well.

QUIC support is experimental and enabled only for browsers supporting it.
