### ISSUE TITLE
Cannot make it works locally :/ ?

### ISSUE THREAD

**Issue by thomasmoreaumaster** [dunglas/mercure#50]
Hi everyone,

I am sorry to open an issue but i have tried for a couple days by now to make it work locally, but i did not succeed :/

First of all i have downloaded a binary and start it with : 

`
JWT_KEY='myJwtKey' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure
`

It works and i can access on localhost:3000 GREAT :) 

Then with Postman i subscribe with this call : 

GET http://localhost:3000/hub?topic=http://localhost:3000/demo/books/1.jsonld
I don't put a token on subscribe because if i do it, i will get an Unauthorized Error

Without token i can see on the console output :
`
INFO[0000] Mercure started                               protocol=http
::1 - - [20/Feb/2019:19:10:16 +0100] "GET /hub?topic=http://localhost:3000/demo/books/1.jsonld HTTP/1.1" 401 37 "" "PostmanRuntime/7.6.0"
INFO[0047] New subscriber                                remote_addr="[::1]:57706"
`

And then i try to push some modifications with this call :

POST http://localhost:3000/hub
With this body :
topic: http://localhost:3000/demo/books/1.jsonld
data: { foo: 'updated value' }

With these headers 
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOltdfX0.473isprbLWLjXmAaVZj6FIVkCdjn37SQpGjzWws-xa0

This token has this structure : 
{
  "mercure": {
    "publish": []
  }
}

And i got an Unauthorized Error as well :/

What am i missing ?

Thanks in advance for the help,
I appreciate your work this is why i try to implement it at work
Thanks,
Thomas.

**Comment by Ilshidur** [comment]
Hello. I'm no expert, but :

**1)**

You may be using the wrong JWT key. As you said, you ran the Hub using this JWT key : `myJwtKey`.
But after a quick validation on `https://jwt.io`, I saw you're using this key to sign your JWT : `your-256-bit-secret`.

Just in case, I think there is a mispatch. Make sure they are the same, so the Hub can validate the JWT you POST.

**2)**

I think you need to insert the proper "rights" in the payload of your JWT. I guess this one can fit your needs : `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.WIXDUTZJqkR-3PjPjHGrOtUAi3T5cmjpZC72cmgwcEE` (signed with this key : `myJwtKey`).

<hr />

Therefore your POST request should succeed and return an ID.

**Comment by thomasmoreaumaster** [comment]
Thanks @Ilshidur for your response,

I have created a token with the same body
```
{
  "mercure": {
    "publish": [
      "*"
    ]
  }
}
```
 and  `myJwtKey` as key to signed it and i find the same token as yours 
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.WIXDUTZJqkR-3PjPjHGrOtUAi3T5cmjpZC72cmgwcEE`

So i tried to

POST http://localhost:3000/hub
With this body :
topic: http://localhost:3000/demo/books/1.jsonld
data: { foo: 'updated value' }

With these headers
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.WIXDUTZJqkR-3PjPjHGrOtUAi3T5cmjpZC72cmgwcEE

But i still got an Unauthorized Response.

Any ideas ?

Still Thanks a lot for your help and taking times on it,
Thomas.

**Comment by Ilshidur** [comment]
I tried on my side and it worked perfectly. I really don't know what is making this error happen.

The only reasons that you face an "Unauthorized" error as a publisher (according to the source code) are :
- invalid JWT (wrong key, invalid payload)
- when `target`ing subscribers, using a unauthorized `target` (not relevant in this case)

Maybe try using cURL :

**GET request :**
```bash
curl http://localhost:3000/hub?topic=http://localhost:3000/demo/books/1.jsonld
```

**POST request :** (in an other terminal)
```bash
curl -X POST \
  http://localhost:3000/hub \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.WIXDUTZJqkR-3PjPjHGrOtUAi3T5cmjpZC72cmgwcEE' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'topic=http%3A%2F%2Flocalhost%3A3000%2Fdemo%2Fbooks%2F1.jsonld&data=HelloKevin'
```

**Comment by thomasmoreaumaster** [comment]
Thanks a lot @Ilshidur but i still got an Unauthorized

tmorea05@tmorea05:~/Bureau/mercure/mercure2$ curl -X POST \
>   http://localhost:3000/hub \
>   -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.WIXDUTZJqkR-3PjPjHGrOtUAi3T5cmjpZC72cmgwcEE' \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -d 'topic=http%3A%2F%2Flocalhost%3A3000%2Fdemo%2Fbooks%2F1.jsonld&data=HelloKevin'
Unauthorized


I am going to change the version of the binary

Still thanks

**Comment by thomasmoreaumaster** [comment]
Thnaks for the help but i think my last option is to upgrade my project from 1.1 to the 2.4 Beta :) 

ありがとうございました
