### ISSUE TITLE
Question: JWT based application, how to manage tokens and subscribers

### ISSUE THREAD

**Issue by syntaxgirl** [dunglas/mercure#501]
This is more a question if someone have some similar experience.
I have an app based on API's and angular for the frontend, while ionic is on mobile side. API is not based on the api-platform, it's just regular api based on symfony custom controllers. Authentication is based on the lexik bundle.

Now the question. My app is based on reports, but also have a chat. Right now chat is done with old ajax, but I wan't to use mercure, as we are already using mercure for notifications. Since mercure works based on the token and what is inside the token, how I am supposed to update token each time user talks to some specific user and then switching to another? Right now I should change the token on the fly, but I don't think this is a good idea, as I will have to send a lot of request for getting new jwt token.

Same thing goes for ecommerce. We want to display the users how many people are checking that same product, but if a users switch from one product to another, he also would have to change it's jwt token. Which I think is too much. Basically checking 10 products would mean 10 different tokens just to add each product id into the jwt token subscriber.

Is there some other way?

**Comment by cvergne** [comment]
Hi,

From my point of view, you shouldn't have to change the token.
Please take a look at the "Subscribers" part of the "Authorization" section of the spec : https://mercure.rocks/spec#authorization

The topic selector in jwt claim should be enough with canonical/alternate topic.

But that is what I'm trying to implement too, and it doesn't work. So if a project member read this, I've [opened a discussion](https://github.com/dunglas/mercure/discussions/502) about that but I'm thinking about opening an issue.

**Comment by syntaxgirl** [comment]
> Hi,
> 
> From my point of view, you shouldn't have to change the token.
> Please take a look at the "Subscribers" part of the "Authorization" section of the spec : https://mercure.rocks/spec#authorization
> 
> The topic selector in jwt claim should be enough with canonical/alternate topic.
> 
> But that is what I'm trying to implement too, and it doesn't work. So if a project member read this, I've [opened a discussion](https://github.com/dunglas/mercure/discussions/502) about that but I'm thinking about opening an issue.

Yeah, but same as you, I was not able to get it to work. Maybe someone have some example?

**Comment by divine** [comment]
Hello,

I'm suggesting generate token once for the user:

```
{
  "mercure": {
    "subscribe": [
      "/users/6076c28589afa72def4b1d56"
    ]
  }
}
```

After that, if you have a personal message between two users you just post to two topics:

```
topic: /users/6062f4795af9b711ef1a9b98
topic: /users/607b03d901dcaf04834ee482
```

with data (just example):

```
{
	"@context": "/contexts/Users",
	"@id": "/users/6062f4795af9b711ef1a9b98",
	"@type": "User",
	"message": "Hello",
	"createdAt": "2021-04-28T07:49:07+01:00",
	"updatedAt": "2021-04-28T09:09:03+02:00"
}
```

That way both users would be able to access the private update that was sent for two users.

> Same thing goes for e-commerce.

For e-commerce this would be a bit easier since public information wouldn't need to include path in JWT token.

Chat example would be best example of this type of integration: https://github.com/dunglas/mercure/tree/main/examples/chat

Let me know if you need any more clarifications/help.

Thanks!
