### ISSUE TITLE
Memory leak still an issue

### ISSUE THREAD

**Issue by divine** [dunglas/mercure#507]
Hello,

After applying the patch https://github.com/dunglas/mercure/pull/503 Caddy again crashed in one just day.

I will report back with profiles.

Thanks!

**Comment by divine** [comment]
Hello,

I've added a script that dumps debug profiles every 15 minutes.

Here is debug profiles:

[debug_profiles.zip](https://github.com/dunglas/mercure/files/6388809/debug_profiles.zip)

This is just in 30 minutes and memory-filled up with high CPU usage, I will add another batch of debug profiles when it will crash.

This is the Caddy version. The legacy version works fine except memory increasing over time also.

Storage transport is local ( `transport_url "local://local"` )

I'm not sure if there is another issue not related to metrics this time at all or maybe this is related to logging which doesn't get cleaned up correctly.


```
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0613365,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0613573,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0613775,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.061397,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.061419,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0614383,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0614588,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0614805,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.061501,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
Apr 28 05:13:52 mercure-1 caddy[1282]: {"level":"debug","ts":1619579632.0615208,"logger":"http.handlers.mercure","msg":"Subscriber has not subscribed to this update"
lines 1-20/20 (END)
```

As I have already said, this logging "Subscriber has not subscribed to this update" does make CPU usage at max because it includes a "data" field that contains a lot of actual data that was sent to Mercure as an update.

Thanks!

**Comment by dunglas** [comment]
Thanks for the new profiles! The leak related to Prometheus doesn't appear anymore. The current leak looks indeed related to the logger. I'm on it.

**Comment by dunglas** [comment]
@divine could you contact me by mail (kevin - dunglas - fr) or on Slack (symfony.com/slack) please? I think that I've found something.

**Comment by divine** [comment]
The problem was due to debug mode enabled, everything looks great, no crash for 4 days.

Thanks!
