### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by Per0x** [dunglas/mercure#51]
Hello, It's a great project and promising. However, the lack of use cases/examples discourages a bit the beginner that I am. In particular PHP resources (without need of Symfony). Do you think I can easily build a simple php collaborative text editor (real-time typing) with the mercure hub and mysql persistence ?

**Comment by dunglas** [comment]
@Per0x What do you think about these docs?

* https://github.com/symfony/symfony-docs/pull/11084
* https://api-platform.com/docs/core/mercure/

**Comment by Per0x** [comment]
@dunglas I think it lacks examples xD
Joking aside, if I understood correctly, I need to use symfony to add real-time collaborative text to my existing php app?

**Comment by dunglas** [comment]
No, you have several alternatives:

* implement the protocol directly using CURL or `file_get_contents` (it's easy, publishing part of the protocol is small, it's basically a POST request)
* use the Symfony Component (it's a standalone library that works with any PHP project, it doesn't require the full stack framework)
* use the Symfony bundle (it integrates the component deeper into Symfony)
* use API Platform (it provided the highest level integration)

**Comment by Per0x** [comment]
Thank you. It helps me, I'll look into it.

**Comment by soyuka** [comment]
don't forget to add yours there https://github.com/dunglas/mercure#other-examples :D

**Comment by dunglas** [comment]
I forgot about this basic example: https://github.com/dunglas/mercure/blob/master/examples/publisher-php.php

**Comment by Grafikart** [comment]
If you work with PHP you can use the Mercure Component even if you are not using Symfony. https://symfony.com/doc/current/components/mercure.html (this component
This component works as a stand alone library.
