### ISSUE TITLE
REACT issue 

### ISSUE THREAD

**Issue by gia-tcm** [dunglas/mercure#510]
Hello guys,

I am using react js / symfony.
And I am having a "401 issue" subscribing from my "front" even when I pass the JWT Token hard encoded.
Hope I'm not the only one, but i looked on internet and I think my code is quite similar to what others do.

```
const url = new URL(process.env.REACT_APP_MERCURE_SUBCRIBE_URL);
const headers = {'Authorization': "Bearer process.env.REACT_APP_MERCURE_SUBCRIPTION_TOKEN"};
url.searchParams.append('topic', 'myTopicTitle');
const eventSource = new EventSource(url, {headers});
eventSource.onmessage = (event) => {
         console.log("The event =>", event)
 }
 ```

I really have no idea on how to solve this. 
Maybe its not an issue of yours, but any hint would be greatly appreciated.

Regards,

**Comment by divine** [comment]
Hello,

Are you using polyfill (https://github.com/Yaffle/EventSource) or just plain EventSource?

Thanks!

**Comment by gia-tcm** [comment]
Thx for asking, 

Just plain eventSource, but even with polyfill, i do have the same issue

**Comment by divine** [comment]
> Thx for asking,
> 
> Just plain eventSource, but even with polyfill, i do have the same issue

If you'd like to use native EventSource then you need to use cookie authorization because native EventSource doesn't support it sending additional headers.

See https://mercure.rocks/docs/spec/faq#how-to-send-the-authorization-cookie-to-the-hub-

Otherwise, using polyfill which supports defining additional headers will resolve your issue.

```javascript
import { EventSourcePolyfill } from 'event-source-polyfill'
const url = new URL(process.env.REACT_APP_MERCURE_SUBCRIBE_URL);
const headers = {'Authorization': "Bearer process.env.REACT_APP_MERCURE_SUBCRIPTION_TOKEN"};
url.searchParams.append('topic', 'myTopicTitle');
const eventSource = new EventSourcePolyfill(url, {headers});
eventSource.onmessage = (event) => {
         console.log("The event =>", event)
 }
```

Also there is a react one https://github.com/jordanbyron/react-native-event-source

Thanks!

**Comment by gia-tcm** [comment]
Perfect !!!

it's now working fine with the polyfill.

Thank you so much!

**Comment by divine** [comment]
You're welcome, you can lose this issue if everything is fine :)

Thanks!
