### ISSUE TITLE
Bug with canonical/alternate topics ?

### ISSUE THREAD

**Issue by cvergne** [dunglas/mercure#516]
Hi,

I've previously opened [a discussion](https://github.com/dunglas/mercure/discussions/502) about that subjet,_ but as #501 also tried to make it work without success, I'm thinking about a bug or something wrong in the documentation.

As mentioned in discussion : I was trying to implements private updates with alternate topics as explained in the documentation, but without success.
So I tried exactly what is in the documentation (_to check if it was from my code_), but I can't make it work.

I'm trying to do the "Subscribers" part of the "Authorization" documentation ( mercure.rocks/spec#authorization )

When I do, with mercure in debug mode, I receive no update and in logs I have the following statement :

```json
{
    "level": "debug",
    "ts": 1619447991.06735,
    "logger": "http.handlers.mercure",
    "msg": "Subscriber not authorized to receive this update",
    "subscriber": {
        "id": "urn:uuid:41b12f2d-1d92-438f-be5e-43a534158caf",
        "last_event_id": "",
        "remote_addr": "172.22.0.1:33614",
        "topic_selectors": [
            "https://example.com/users/foo/{?topic}"
        ],
        "topics": [
            "https://example.com/books/{id}"
        ]
    },
    "update": {
        "id": "urn:uuid:82b6cc3a-c202-491b-845a-041a1b29955d",
        "type": "",
        "retry": 0,
        "topics": [
            "https://example.com/books/1",
            "https://example.com/users/foo/?topic=https://example.com/books/1"
        ],
        "private": true,
        "data": ""
    }
}
```
(Note: done with mercure 0.11.2)

So is there a bug ? Or am I doing something wrong ? Or a mistake in documentation ?

Thanks for your help !

**Comment by divine** [comment]
Hello,

We're running fine with ~2M private updates each day.

Could you please share the snippet that is being sent to Mercure?

`"https://example.com/users/foo/?topic=https://example.com/books/1"`

^^ I think this doesn't look good, you might subscribing or sending updates incorrectly.

Also, have you seen my reply https://github.com/dunglas/mercure/issues/501#issuecomment-827931113?

Thanks!

**Comment by cvergne** [comment]
Hi, thanks for your reply !

Well that's embarrassing, I've tried again everything to share snippet to you, and it works.
I think I got tangled with all my tests and URLs, and I think one of the topics had one missing `/`.

So I'm closing this issue, sorry for the disturbance :/

**Comment by divine** [comment]
@cvergne you're welcome, let me know if you'll need anything else!

It took me some time to understand this too so no worries!

Thanks!
