### ISSUE TITLE
Immutable infrastructure; how to host mercure on them ?

### ISSUE THREAD

**Issue by tristanbes** [dunglas/mercure#52]
Hello,

I just asked a cloud provider if they have any plans to offer Mercure on their PaaS. They said that they cannot because they have an immutable architecture, each time we deploy, it's on a new container so data are not kept.

Reference tweet: https://twitter.com/Soulou/status/1102933346215231488

They pointed out issues discussed in #10, but we're not interested in redundancy, just host mercure on an immutable infrastructure :)

Is this possible ? Thanks

**Comment by dunglas** [comment]
Hi,

Indeed the current boltdb requires write access to the disk. However this behavior would be easy to change. (The database is only use as a temporary history, it's not true persistent data).
If the disk is read only, and it's not possible to use a tmpfs or something similar (it would be the best solution), it's still possible to:

* implement a in-memory history (here is the interface, providing such implementation would be very easy: https://github.com/dunglas/mercure/blob/master/hub/history.go#L13)
* disable the history (the implementation is already provided: https://github.com/dunglas/mercure/blob/master/hub/history.go#L24, but not exposed as a configuration option for now)

A patch is very welcome, or I'll try to add this when I'll have a bit more free time. Thanks for reporting!

**Comment by tristanbes** [comment]
I can't speak for them, but I think the disk is not read only, It's "just" lost on each deployments.

So basically you're saying we don't care loosing this file between each mercure hub deployments since it's only temporary history ? It doens't compromise the data ?

**Comment by dunglas** [comment]
Exactly. It's only used for by the client after a network issue, when it tries to fetch lost updates: https://github.com/dunglas/mercure/blob/master/spec/mercure.md#reconnection-and-state-reconciliation

**Comment by tristanbes** [comment]
Thanks for the clarification ! 🎉

**Comment by Soulou** [comment]
Perfect, thanks @tristanbes  and @dunglas  for those specifications.
