### ISSUE TITLE
always return Status Code: 401 Unauthorized

### ISSUE THREAD

**Issue by grekpg** [dunglas/mercure#520]
docker-compose

```
    mercure:
      image: dunglas/mercure
      environment:
        - MERCURE_PUBLISHER_JWT_KEY=sdfsd345V&(%tovyv3ver
        - MERCURE_SUBSCRIBER_JWT_KEY=sdfsd345V&(%tovyv3ver
        - DEBUG=debug # Enable the debug mode. You should not enable it in production!
        - SERVER_NAME=:80 # Allow Mercure to run in HTTP, for PHP container to call it. Should not be set in production!
        - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
      ports:
        - "1337:80"
```

start 
`
    docker-compose up --build`

open 

`http://localhost:1337/.well-known/mercure`

```
    Request URL: http://localhost:1337/.well-known/mercure
    Request Method: GET
    Status Code: 401 Unauthorized
    Remote Address: [::1]:1337
    Referrer Policy: strict-origin-when-cross-origin

```

Response

```
    Content-Length: 13
    Content-Security-Policy: default-src 'self'
    Content-Type: text/plain; charset=utf-8
    Date: Mon, 10 May 2021 15:14:26 GMT
    Server: Caddy
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-Xss-Protection: 1; mode=block
```

Same situation from app - 
.env.local 
```

    MERCURE_PUBLISH_URL=http://localhost:1337/.well-known/mercure
    MERCURE_JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.NRMv3lmIndeEbm8ylyrhhx7Y0v9EthWdaXaGLQ6-bf0
```

JWT test give Signature Verified

`    https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.NRMv3lmIndeEbm8ylyrhhx7Y0v9EthWdaXaGLQ6-bf0
`

when i add debug: 

`     - MERCURE_EXTRA_DIRECTIVES=subscriptions debug allow_anonymous cors_allowed_origins *`

and go to http://localhost:1337/.well-known/mercure/ui/

`    404 page not found`

log from console: 

`    {"level":"error","ts":1620660042.5866034,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"172.20.0.1:45918","proto":"HTTP/1.1","method":"GET","host":"localhost:1337","uri":"/.well-known/mercure","headers":{"Sec-Fetch-Dest":["document"],"Cookie":["_ga=GA1.1.295525162.1619510783; SL_G_WPT_TO=en; SL_GWPT_Show_Hide_tmp=undefined; SL_wptGlobTipTmp=undefined; _gid=GA1.1.1112427149.1620627495"],"Cache-Control":["no-cache"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Sec-Fetch-User":["?1"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"],"Accept-Encoding":["gzip, deflate, br"],"Pragma":["no-cache"],"Sec-Fetch-Mode":["navigate"],"Accept-Language":["pl-PL,pl;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6"],"Connection":["keep-alive"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Site":["none"]}},"common_log":"172.20.0.1 - - [10/May/2021:15:20:42 +0000] \"GET /.well-known/mercure HTTP/1.1\" 401 13","duration":0.000187384,"size":13,"status":401,"resp_headers":{"X-Xss-Protection":["1; mode=block"],"Content-Security-Policy":["default-src 'self'"],"X-Frame-Options":["DENY"],"X-Content-Type-Options":["nosniff"],"Content-Type":["text/plain; charset=utf-8"],"Server":["Caddy"]}}`

**Comment by GRUXXKi** [comment]
Exaclty the same here, no way to be authorized with the last version.

**Comment by ekkode** [comment]
In v0.11.3 everything is ok, but we had the same issue in v0.12, the MERCURE_PUBLISHER_JWT_KEY and MERCURE_SUBSCRIBER_JWT_KEY are changed in this version?

**Comment by 7system7** [comment]
Same error here. It is impossible to get an answer other than 401. 
:D :+1:

**Comment by plamenh** [comment]
Same here

**Comment by pjuraszekergoproxy** [comment]
same here, someone fixed it?

**Comment by nfacha** [comment]
Also having this issue

**Comment by DevWebWill** [comment]
mismo error

**Comment by dunglas** [comment]
Did you follow https://mercure.rocks/docs/hub/troubleshooting?
