### ISSUE TITLE
How to deploy Mercure Hub on Heroku?

### ISSUE THREAD

**Issue by DhiaDjobbi** [dunglas/mercure#524]
Hello guys , I am really struggling to deploy Mercure Hub on Heroku!
I made some research and I found Dunglas [Answer on StackOverflow](https://stackoverflow.com/a/57424347/12771208)
But its not clear :( !
Do I create an empty Go Project and then Copy and Paste the Binary inside it and push it to Heroku ?
and what Procfile Should I use on this case? 
The go lang Default  Procfile `web: bin/go-getting-started`  ?
or Mercure Procfile ? `web: ADDR=":${PORT}" mercure` ?
In case Mercure Procfile , Which Port should I use ? 

Can Anyone please Provide clear steps on deploying Mercure on Heroku!
Thank you

**Comment by ging-dev** [comment]
Hey man, i think this will help you:
https://github.com/ging-dev/mercure-heroku
You need use this buildpack to run it: https://github.com/ph3nx/heroku-binary-buildpack

**Comment by ging-dev** [comment]
> Hello guys , I am really struggling to deploy Mercure Hub on Heroku!
> I made some research and I found Dunglas [Answer on StackOverflow](https://stackoverflow.com/a/57424347/12771208)
> But its not clear :( !
> Do I create an empty Go Project and then Copy and Paste the Binary inside it and push it to Heroku ?
> and what Procfile Should I use on this case?
> The go lang Default Procfile `web: bin/go-getting-started` ?
> or Mercure Procfile ? `web: ADDR=":${PORT}" mercure` ?
> In case Mercure Procfile , Which Port should I use ?
> 
> Can Anyone please Provide clear steps on deploying Mercure on Heroku!
> Thank you

Hey man, i think this will help you:
https://github.com/ging-dev/mercure-heroku
You need use this buildpack to run it: https://github.com/ph3nx/heroku-binary-buildpack

**Comment by DhiaDjobbi** [comment]
Thank you  @ging-dev  for your answer!
I created a heroku project and used that binary buildpack using:
`heroku create mercure-dhia --buildpack https://github.com/ph3nx/heroku-binary-buildpack.git`
The content of my procfile is:
 `web: ./mercure -k "test" -c '*' -p '*' -a :$PORT -D -X `
I added Mercure files (I am using version 0.9.0) and I `git add. ` `git commit` and then `git push heroku master`
I also pushed it to a repository on github: https://github.com/DhiaDjobbi/mercure-heroku.git
when I open https://mercure-dhia.herokuapp.com/
I get **Application error**
This are my logs :
![image](https://user-images.githubusercontent.com/40583006/121751381-e8721e00-cb05-11eb-86cd-5b68a5e0c03f.png)
What I am doing wrong ?

**Comment by ging-dev** [comment]
> Thank you @ging-dev for your answer!
> I created a heroku project and used that binary buildpack using:
> `heroku create mercure-dhia --buildpack https://github.com/ph3nx/heroku-binary-buildpack.git`
> 
> I added Mercure files (I am using version 0.9.0) and I `git add. ` `git commit` and then `git push heroku master`
> when I open https://mercure-dhia.herokuapp.com/
> I get a **Permission Denied** Error on my logs.
> 
> This are my logs :
> ![image](https://user-images.githubusercontent.com/40583006/121751381-e8721e00-cb05-11eb-86cd-5b68a5e0c03f.png)
> 
> I solved this error by Changing my Procfile content from :
> `web: ./mercure -k "test" -c '*' -p '*' -a :$PORT -D -X `
> to :
> `web: chmod a+x ./mercure ; ./mercure -k "test" -c '*' -p '*' -a :$PORT -D -X`
> (I added `**chmod a+x ./mercure ;** ` )

Ya, exactly I gave the file permission before adding it to git, I don't have that problem 😳

**Comment by samijnih** [comment]
@ging-dev @DhiaDjobbi Hi guys

Which version of mercure bin do you use?
I'm using the latest one and there's no way to specify options. I can only do "mercure run -config <caddyfile>".

So I assume that Mercure must be run with Caddy on Heroku now?

Thanks for your help

**Comment by ging-dev** [comment]
> @ging-dev @DhiaDjobbi Hi guys
> 
> Which version of mercure bin do you use? I'm using the latest one and there's no way to specify options. I can only do "mercure run -config" specifying a caddy file.
> 
> So I assume that Mercure must be run with Caddy on Heroku now?
> 
> Thanks for your help

Hi, you can choose `legacy linux x86_64` version to run on Heroku, they don't need Candy server

https://github.com/dunglas/mercure/releases

**Comment by samijnih** [comment]
> > @ging-dev @DhiaDjobbi Hi guys
> > Which version of mercure bin do you use? I'm using the latest one and there's no way to specify options. I can only do "mercure run -config" specifying a caddy file.
> > So I assume that Mercure must be run with Caddy on Heroku now?
> > Thanks for your help
> 
> Hi, you can choose `legacy linux x86_64` version to run on Heroku, they don't need Candy server
> 
> https://github.com/dunglas/mercure/releases

Thank you!
