### ISSUE TITLE
Helm lint check CI workflow doesn't seem to be working

### ISSUE THREAD

**Issue by sagikazarmark** [dunglas/mercure#528]
The latest master [build](https://github.com/dunglas/mercure/actions/runs/914531593) is currently broken, because the chart version was not increased in #527.

After looking at the commits in #527 it looks like the chart linter check never ran. (It would have complained about the missing chart version increase)

As a result, the latest chart fix was never released.

I can't tell whether it's intentional though, because the chart version seems to match the application version at the moment.

**Comment by dunglas** [comment]
Yes it's intentional. I wanted the chart to be released at the same time as the hub. But it's maybe a bad idea.

**Comment by sagikazarmark** [comment]
Well, a chart release would be nice because a recent patch fixes a problem that currently makes mercure installation fail on most clusters where the default storage class is non-existent or doesn't work.

**Comment by sagikazarmark** [comment]
Any plans to release a patch version with the latest chart fix? Currently it cannot be installed with custom storage classes.

**Comment by dunglas** [comment]
Yes I plan to do a release at the end of the week.

**Comment by sagikazarmark** [comment]
Cool, thanks

**Comment by dunglas** [comment]
done!

**Comment by dunglas** [comment]
Reopening: the chart release doesn't seem to work.

**Comment by dunglas** [comment]
Fixed!
