### ISSUE TITLE
Feature Request: config option to customize cookie name

### ISSUE THREAD

**Issue by dominicbvm** [dunglas/mercure#532]
In our dev environment, we customize our hosts file so we can use the same parent domain and wildcard SSL cert that we use in production. This causes problems if we are jumping between dev and prod because they both set a wildcard cookie for the same parent domain to auth to mercure but different mercure instances. It would be nice to be able to customize the cookie name in a scenario like this so that it could be something other than mercureAuthorization.

**Comment by dunglas** [comment]
This will also allow to create different security contexts on the same domain.

I plan to add this feature to the spec and to implement it in the hub.

**Comment by dunglas** [comment]
I opened a proposal to add support for this feature to the spec. Could you review it to check if it fixes this issue please? https://github.com/dunglas/mercure/pull/562

**Comment by dominicbvm** [comment]
Yeah, reading through the spec changes around the cookie name, this should definitely solve the scenario we are running into. Thanks!
