### ISSUE TITLE
Cannot use the Helm repo ("error: failed to download")

### ISSUE THREAD

**Issue by v0ctor** [dunglas/mercure#536]
When I run the `helm install` command, I get an error:

```Shell
helm repo add mercure https://charts.mercure.rocks
helm repo update
helm install my-release mercure/mercure
```

> Error: failed to download "mercure/mercure" (hint: running `helm repo update` may help)

I've done it several times before from the same machine (with the same configuration and network). Is it possible that there is a service misconfiguration? It happens since yesterday.

Thank you very much.

Note: I've previously checked #531.

**Comment by aurelijusrozenas** [comment]
It seems the `https://charts.mercure.rocks/` url points to 404
![paveikslas](https://user-images.githubusercontent.com/3273544/126078290-144de109-7b29-40ec-8da6-f2acda59c305.png)

**Comment by ghostika** [comment]
I've just tried to install it, helm wants to fetch this URL:
https://github.com/dunglas/mercure/releases/download/mercure-0.12.0/mercure-0.12.0.tgz

A valid path for the release is:
https://github.com/dunglas/mercure/releases/download/helm-chart-0.12.0/mercure-0.12.0.tgz

I didn't found a way to go around this error.

**Comment by dunglas** [comment]
Thanks for reporting. I think they this can only be fixed on my side. I'm in vacation until the first week of August. I'll fix this when I'll be back. In the meantime, as a temporary workaround, you can clone this repository and use the chart provided in the `charts` repository. This should work.

**Comment by dunglas** [comment]
Fixed!

**Comment by v0ctor** [comment]
Thank you very much! 🙂
