### ISSUE TITLE
Unable to deploy Mercure on production, using API Platform and Apache

### ISSUE THREAD

**Issue by vt-gianni** [dunglas/mercure#539]
Hello,

I created an API on Symfony 4.4 via API Platform. In order to send notifications to my users on my mobile application made in react native, I want to use Mercure.

I already have my API in production under the following domain name: https://api.mywebsite.fr

So now I would like to configure Mercure in production but I cannot manage it despite a lot of research.

Here is my configuration in the .env file:

```
MERCURE_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLIC_URL=https://hub.mywebsite.fr:3000/.well-known/mercure
 
MERCURE_JWT_SECRET=mykeyp
MERCURE_PUBLISHER_JWT_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.Gvmkhs_Nx9S7yNyNs_TUghfcruiNrNKQBA0D36cGQSA
MERCURE_SUBSCRIBER_JWT_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.Mzezd1YtkgCmlEDQg4qwNCFql1JXCXk1Vg-tB8UHgSk
```

Here is the command I run to launch Mercure:

```
SERVER_NAME=:3000 MERCURE_PUBLISHER_JWT_KEY="mykeyp" MERCURE_SUBSCRIBER_JWT_KEY="mykeys" CORS_ALLOWED_ORIGINS="*" ALLOW_ANONYMOUS=1 ./mercure/mercure run -config mercure/Caddyfile
```

Here is the content of my mercure/Caddyfile file:

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
    # Debug mode (disable it in production!)
    {$DEBUG}
    # HTTP/3 support
    servers {
        protocol {
            experimental_http3
        }
    }
}

{$SERVER_NAME:localhost}

log

route {
    encode zstd gzip

    mercure {
        # Transport to use (default to Bolt)
        transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
        # Publisher JWT key
        publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
        # Subscriber JWT key
        subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
        # Extra directives
        {$MERCURE_EXTRA_DIRECTIVES}
    }

    respond /healthz 200

    respond "Not Found" 404
}
```

And finally my VirtualHost:

```
<VirtualHost *:443>
    ServerName hub.mywebsite.fr
    ServerAlias www.hub.mywebsite.fr
    ProxyRequests Off
    SSLCertificateFile /etc/ssl/certs/mywebsite.fr_ssl_certificate.cer
    SSLCACertificateFile /etc/ssl/certs/mywebsite.fr_ssl_certificate_INTERMEDIATE.cer
    SSLCertificateKeyFile /etc/ssl/private/mywebsite.fr_private_key.key
    SSLUseStapling on

   <LocationMatch /.well-known/mercure>
      ProxyPass http://localhost:3000
      ProxyPassReverse https://hub.mywebsite.fr:3000
   </LocationMatch>
</VirtualHost>
```

The problem is that by going to the address https://hub.mywebsite.fr/.well-known/mercure, the browser displays "Not Found".

Can you tell me what I misconfigured please?

Thanks in advance.

**Comment by dunglas** [comment]
Do you also get a 404 when trying to query the hub directly (form the server, by running something like `curl -v http://localhost:300/.well-known/mercure`?

If it's not the case, it's probably Apache that is misconfigured.

What do you have in the logs (both Mercure and Apache logs)?

**Comment by vt-gianni** [comment]
Hello Dunglas and thank you very much for your response.

I started a curl from the server on http://localhost:3000/.well-known/mercure and indeed I don't have the same error, I get a 401 Unauthorized error:

```
ERROR   http.log.access handled request {"request": {"remote_addr": "127.0.0.1:37108", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:3000", "uri": "/.well-known/mercure", "headers": {"User-Agent": ["curl/7.68.0"], "Accept": ["*/*"]}}, "common_log": "127.0.0.1 - - [28/Jul/2021:07:56:43 +0000] \"GET /.well-known/mercure HTTP/1.1\" 401 13", "duration": 0.000205833, "size": 13, "status": 401, "resp_headers": {"Server": ["Caddy"], "X-Frame-Options": ["DENY"], "X-Content-Type-Options": ["nosniff"], "X-Xss-Protection": ["1; mode=block"], "Content-Security-Policy": ["default-src 'self'"], "Content-Type": ["text/plain; charset=utf-8"]}}
```

I looked in my apache logs and the only traces I have when I try to contact the server from my browser are in the /var/log/apache2/other_vhosts_access.log file and I get simple 404 logs.

```
hub.mywebsite.fr:443 10.255.255.255 - - [28/Jul/2021:08:02:00 +0000] "GET /.well-known/mercure HTTP/1.1" 404 715 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
hub.mywebsite.fr:443 10.255.255.255 - - [28/Jul/2021:08:02:00 +0000] "GET /favicon.ico HTTP/1.1" 404 514 "https://hub.website.fr/.well-known/mercure" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
hub.mywebsite.fr:443 10.255.255.255 - - [28/Jul/2021:08:02:18 +0000] "GET /.well-known/mercure HTTP/1.1" 404 715 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
hub.mywebsite.fr:443 10.255.255.255 - - [28/Jul/2021:08:02:18 +0000] "GET /favicon.ico HTTP/1.1" 404 514 "https://hub.website.fr/.well-known/mercure" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
```

Regarding mercure logs, it's the same thing:

```
2021/07/28 08:02:18.150 ERROR   http.log.access handled request {"request": {"remote_addr": "127.0.0.1:37212", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:3000", "uri": "/", "headers": {"Sec-Fetch-Dest": ["document"], "X-Forwarded-For": ["10.255.255.255"], "Sec-Fetch-Mode": ["navigate"], "Connection": ["Keep-Alive"], "X-Forwarded-Host": ["hub.website.fr"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Sec-Fetch-User": ["?1"], "Upgrade-Insecure-Requests": ["1"], "Sec-Fetch-Site": ["none"], "X-Forwarded-Server": ["hub.website.fr"], "Accept-Language": ["fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"], "Accept-Encoding": ["gzip, deflate, br"]}}, "common_log": "127.0.0.1 - - [28/Jul/2021:08:02:18 +0000] \"GET / HTTP/1.1\" 404 9", "duration": 0.000202435, "size": 9, "status": 404, "resp_headers": {"Server": ["Caddy"], "Content-Type": []}}
```

**Comment by dunglas** [comment]
According to your logs, the hub is working properly (the authentication error is expected) but Apache forwards the URL `/.well -known/mercure` to `/` (instead of `/.well -known/mercure`). It's the problem, you should fix your Apache config).

**Comment by vt-gianni** [comment]
It was indeed an apache configuration problem, thanks.
I can now listen from postman at: https://hub.mywebsite.fr/.well-known/mercure?topic=https://api.mywebsite.fr/users/1

Unfortunately I am not receiving anything when I perform a PUT on https://api.mywebsite.fr/users/1 while Mercure is still listening. Here are my mercury logs:
```
http.handlers.mercure   New subscriber  {"subscriber": {"id": "urn:uuid:b9b630a4-fedf-4b97-91e0-28fa3f362ff0", "last_event_id": "", "remote_addr": "127.0.0.1:43946", "topics": ["https://api.mywebsite.fr/api/users/1"]}}
```

Here is my Caddyfile:

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
    # Debug mode (disable it in production!)
    #{$DEBUG:debug}
    # HTTP/3 support


    servers {
        protocol {
            experimental_http3
        }
    }
}

{$SERVER_NAME:localhost}

log

route {
    redir / /.well-known/mercure/ui/
    encode zstd gzip

    mercure {
        # Transport to use (default to Bolt)
        transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
        # Publisher JWT key
        publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
        # Subscriber JWT key
        subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
        # Permissive configuration for the development environment
        cors_origins *
        publish_origins *
        #demo
        anonymous
        subscriptions
        # Extra directives
        {$MERCURE_EXTRA_DIRECTIVES}
    }

    respond /healthz 200

    respond "Not Found" 404
}
```

**Comment by vt-gianni** [comment]
Very strange, in the mercure logs I can see that the Bearer Token is not the one I specified. By copying it and testing it on https://jwt.io, it looks like it added an "exp" field with a float number, invalidating the signature. How to remove it or force an integer cast?

**Comment by zspine** [comment]
@vt-gianni I had the same issue with an older version of mercure, ensure you're running the latest version of mercure (mercure:v0.12)

**Comment by vt-gianni** [comment]
Thank you @zspine  but I have the current version. :\

![screen_jwt](https://user-images.githubusercontent.com/64596139/127627642-1ef22911-557f-4f45-a79f-b7bf87df8d72.png)


By directly pasting the jwt token in https://jwt.io, I have an invalid signature.

But when I remove the last digit after the comma from the "exp" field, and put it back, I no longer have the invalid signature error on the site and the token generated is not the same at all.

So it's not a floating point number problem I guess. Perhaps the "-" following in the token?

**Comment by zspine** [comment]
@vt-gianni I see... It took some time for me to get it to work on the production and development setups. I followed this pure PHP example to make debugging easier.  

https://github.com/dunglas/mercure/blob/main/examples/publish/php.php

**Comment by divine** [comment]
I'm still unsure why somebody would still use ancient Apache which doesn't perform well.

**Comment by vt-gianni** [comment]
Hello, thank you all for your help. I was able to solve the problem.

I had misunderstood and thought that MERCURE_JWT_SECRET could replace MERCURE_PUBLISHER_JWT_KEY and MERCURE_SUBSCRIBER_JWT_KEY to only use one secret key for both the subscriber and the publisher.

By adding these two environment variables with different keys, I was finally able to make mercure work.
