### ISSUE TITLE
[Symfony] Can't get mercure to work

### ISSUE THREAD

**Issue by alexander-schoch-linuxdays** [dunglas/mercure#548]
I am trying to set up mercure with symfony, but no matter what i change, it always results in "Failed to send an update." ("MERCUR Topic selectors not matched, not provided or authorization error" in the Server logs). 

I installed mercure via "composer req mercure" and start the server via "symfony server:run --allow-http", as dunglas/mercure#485 states that https will lead to problems. I also tried with "php -S localhost:8000" and starting the mercury binary manually, but no working results.

Environment Variables:

```
MERCURE_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLIC_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLISH_URL=http://localhost:3000/.well-known/mercure
MERCURE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.oIy5_VUByd4lbCh6IcntwdiM2oyZ2gbrSp1jhcWz3tU
```

The secret was generated with https://jwt.io/, using "aaaaaaaa" as a key.

Interestingly, mercure seems to start on port 8000, as I'm getting "Missing "topic" parameter." if i visit localhost:8000/.well-known/mercure

I tried setting the port to 8000, but this doesn't work either. Also, changing http to https doesn't work.

Call in Symfony Controller:
```
$update = new Update(
  '/entries',
  json_encode(['message' => 'heyo']),
);
$hub->publish($update);
```

**Comment by dunglas** [comment]
The key used to sign the JWT must be `!ChangeMe!` if you use the Symfony binary. That's probably the issue.
And using https is totally supported now.

**Comment by alexander-schoch-linuxdays** [comment]
@dunglas Thanks for your fast answer!

This did fix the problem, however only for localhost itself. If I now try to visit this route from a machine in the same network, I still get the "failed to send an update" error, while the server logs don't even show the "started mercure" line.

Ennvironment variables now:

```
MERCURE_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLIC_URL=http://192.168.1.142:3000/.well-known/mercure
MERCURE_PUBLISH_URL=http://192.168.1.142:3000/.well-known/mercure
MERCURE_JWT_SECRET=!ChangeMe!
```

**Comment by alexander-schoch-linuxdays** [comment]
Update: If I enter the signed key via 

```
MERCURE_JWT_SECRET="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.obDjwCgqtPuIvwBlTxUEmibbBf0zypKCNzNKP7Op2UM
```

it does not work. I get a 401, which is an indication that the key does not work. What do i do wrong? The only thing i did is to go to https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.iHLdpAEjX4BqCsHJEegxRmO-Y6sMxXwNATrQyRNt3GY (linked by symfony mercure wiki page) and enter `!ChangeMe!` as a secret.

**Comment by zspine** [comment]
@alexander-schoch-linuxdays can you try this [pure php example](https://github.com/dunglas/mercure/blob/main/examples/publish/php.php) without any symfony dependencies and configuration?

I had similar problems until I figured out how to handle everything. So if we can confirm that 'mercure hub' configuration is correct  without relying on any other dependencies, it will be a little easier to debug.

**Comment by alexander-schoch-linuxdays** [comment]
@zspine After running the following commands

```
symfony new mercure
cd symfony
composer req mercure
symfony server:start
```

,putting this minimal file into `public/php.php` and calling `localhost:8000/php.php`, I get

`PHP Warning:  file_get_contents(https://localhost/.well-known/mercure): failed to open stream: Connection refused in /home/alexander_schoch/Documents/php/Symfony/mercure/public/php.php on line 13`

**Comment by zspine** [comment]
@alexander-schoch-linuxdays Okay, so it works ok with localhost but not with another machine on the same network. I'm guessing it has something to do with cors_origins or one of the other options. Unfortunately, I am unfamiliar with the Mercure Symfony binary version and am unsure whether or not the settings can be checked. 

Sorry for not being more helpful.

**Comment by cybervoid** [comment]
@alexander-schoch-linuxdays I have it running with `symfony 5.3` both local and in a server, my local copy runs under https with symfony's binary.
During my setup I got a lot of "Failed to send an update.", you have to find in mercure's logs the reason why it failed, in my case, I had some issues with the env variables on symfony, and then later when deployed to a server got the same error and this time it was CORS.

I see you variables

```
MERCURE_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLIC_URL=http://192.168.1.142:3000/.well-known/mercure
MERCURE_PUBLISH_URL=http://192.168.1.142:3000/.well-known/mercure
MERCURE_JWT_SECRET=!ChangeMe!
```

They are correct, I think, based on previous  messages you got it working locally but you can't get it work from another computer? That definitely could be CORS issues, but again, it'll show up in the logs.

**Comment by alexander-schoch-linuxdays** [comment]
@cybervoid By "mercure logs", you do mean the output of `symfony server:start` with the very minimal output you get from mercure, right? There, I just see `MERCUR Topic selectors not matched, not provided or authorization error`.

It is well possible that this is a CORS problem. However, when trying to start mercure via the mercure.rocks binary and `JWT_KEY=!ChangeMe! ADDR=http://localhost:3000 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=http://localhost:8000 ./bin/mercure run`, it can't even connect to the hub.

**Comment by cybervoid** [comment]
@alexander-schoch-linuxdays  for development I run mercure, the binary downloaded locally and I run it with the following parameters:

```
MERCURE_PUBLISHER_JWT_KEY='changeme' \
MERCURE_SUBSCRIBER_JWT_KEY='changeme' \
./mercure run -config Caddyfile.dev
```
Once you do that from the console, you'll be able to see mercure logs within the same console window you used to run it.

To rule out CORS issues, maybe check from chrome dev tools directly, it will complain about it too if that's the actual problem, I replicated that problem in the attached screenshot, I hope this helps.

![image](https://user-images.githubusercontent.com/3310256/130274249-5dd516fc-f9bb-433d-b2af-1b5ce224b7e2.png)

**Comment by dunglas** [comment]
It looks like you use both `https://127.0.0.1` and `https://localhost`. They aren't the same domain! Be sure to use the same domaine everywhere.

**Comment by alexander-schoch-linuxdays** [comment]
Because literally nothing was working, I tried to push the project onto another machine, and it did work out of the box. Thus, something with the configuration of my operating system was wrong, but I have no idea what i could be.

Thanks everyone for helping me.

**Comment by redflasher** [comment]
May be you set SERVER_NAME in .env without "candy:80":
```
SERVER_NAME="your_domain"
```
but correct:
```
SERVER_NAME="memes-lol.your_domain, caddy:80"
```
