### ISSUE TITLE
Add warning about CORS_ALLOWED_ORIGINS

### ISSUE THREAD

**Issue by althaus** [dunglas/mercure#56]
Hi,

it'd be great if you could add a warning about CORS_ALLOWED_ORIGINS. It took my some time and trial-and-error to come to the final conlusion that I have to set CORS_ALLOWED_ORIGIN=* on my localhost to get this started.

I followed the Symfony doc and could only figure this our switching from Firefox to Chrome. I also proposed the change for the doc: https://github.com/symfony/symfony-docs/pull/11116

Cheers
Matthias

**Comment by dunglas** [comment]
Good catch thanks! Would you mind updating the README if appropriate?

**Comment by alamirault** [comment]
Thanks, I had this problem without details about it in doc
