### ISSUE TITLE
One sse per session

### ISSUE THREAD

**Issue by lauretCoding** [dunglas/mercure#564]
Hello,
Is there a way to have just one eventsource if we have multiple tabs?

**Comment by dunglas** [comment]
It's possible to use JS tricks to achieve this, like this one: https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel

You can also use use localStorage, postMessage, and all other ways allowing to synchronize data structures between tabs.

**Comment by lauretCoding** [comment]
> It's possible to use JS tricks to achieve this, like this one: https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel
> 
> You can also use use localStorage, postMessage, and all other ways allowing to synchronize data structures between tabs.

Ok thanks. I will try that
