### ISSUE TITLE
Mercure publishes to topic JWT token should not be allowed to

### ISSUE THREAD

**Issue by mariuseliassen** [dunglas/mercure#579]
### Mercure version: `0.13`

Without the "private" flag on messages are being sent to subscriber even if topic is not in subscriber or publish allowed whitelist.

![image](https://user-images.githubusercontent.com/1819272/139858288-6213ceb0-43dd-499f-bdff-86cc2c7b0dc2.png)

Token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiL3dvcmtzcGFjZXMvMTIzIl0sInN1YnNjcmliZSI6WyIvd29ya3NwYWNlcy8xMjMiXX19.bxyELLWxI60AUT1xC3OR0cU_62vRUV0WVyuj00EDWjs`

Unauthorized is only thrown if "Private" is ticked. 
This does not work well for client-to-client mercure applications as this can be overwritten by any client.

**Comment by dunglas** [comment]
This is the intended behavior (as described in the spec). It's why there is the `private` flag: to distinguish between public and private updates.

**Comment by mariuseliassen** [comment]
@dunglas Ok thanks for your quick reply.

Can you suggest how to implement private publishing topics for client-to-client behavior or if this has to be done through a backend proxy service?

**Comment by dunglas** [comment]
I'm not sure to follow. Clients' code can set the `publish` flag to true too.

**Comment by mariuseliassen** [comment]
@dunglas We are generating the JWT tokens server side with a passphrase. My understanding is that this JWT token is validated inside mercure and thus the client's are not able to modify the JWT to set publish to whatever they want.

Is it possible to request that we can control this private behavior with configuration?

https://github.com/dunglas/mercure/blob/main/publish.go#L49

We would like to enforce this value to true always for our usecase, so that client-to-client can only publish to the topics that are encoded in the `publish` array. Is it possible to achieve?

**Comment by dunglas** [comment]
Good idea to add a configuration option to only allow private updates. +1 on my side. This would also prevent mistake from programmers forgetting to set the flag. 

Still, I fail to understand the use case. Nothing can prevent a client to share the data it owns with another user (using another channel than Mercure if necessary). And in could any harm himself by doing so, as it already has the data.

**Comment by mariuseliassen** [comment]
Our use case is pretty simple.

We have a mercure we use as a ping service to show online state. A logged in account can send pings to other accounts on the same workspace through javascript (frontend). JWT's for mercure are produced by backend on page load. As such we would produce a jwt for the account `A` as follows:

```
{
  "mercure": {
    "publish": [
      "/workspaces/1"
    ],
    "subscribe": [
      "/workspaces/1"
    ]
  }
}
```

Now assume that a we have another account `B` with the following JWT

```
{
  "mercure": {
    "publish": [
      "/workspaces/2"
    ],
    "subscribe": [
      "/workspaces/2"
    ]
  }
}
```

By design Account `B` should not be able to send any pings to `/workspace/1`, but without this `private` flag set (by the client) he actually is able to send a message to topic `/workspaces/1`. 

Now in OUR frontend code we can set `private: true` - this is not a problem. The problem comes in when a rogue account just takes the JWT token, takes the mercure url and uses like Postman to construct a ping to a workspace he/she really should not be allowed to post to.

**Comment by dunglas** [comment]
@mariuseliassen sorry for the long delay, but could you check if https://github.com/dunglas/mercure/pull/620 fixes your issue, please?
