### ISSUE TITLE
Updates only work via Debugger UI

### ISSUE THREAD

**Issue by velreine** [dunglas/mercure#590]
I cannot figure out why my events made from API Platform does not show up in the Debugger UI, even though the listening topic is set to star (*)

I'm running the prebuilt binary for Linux on Ubuntu 20.04, as I wanted to eliminate error sources by not running docker.

This is my .env configuration in the Symfony API Platform project:

```
MERCURE_URL=https://localhost/.well-known/mercure
MERCURE_PUBLIC_URL=https://localhost/.well-known/mercure
MERCURE_JWT_SECRET="!ChangeMe!"
```

And this is my Caddyfile.dev:

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
	{$GLOBAL_OPTIONS}
}

{$SERVER_NAME:localhost}

log

header Access-Control-Allow-Origin *
header Access-Control-Allow-Credentials true

route {
	redir / /.well-known/mercure/ui/
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt !ChangeMe! {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt !ChangeMe! {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Permissive configuration for the development environment
		cors_origins *
		publish_origins *
		demo
		anonymous
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	respond /healthz 200

	respond "Not Found" 404
}
```

Since i tried hardcoding the values in the Caddyfile.dev, the command to run the server is simply:

`sudo ./mercure run -config Caddyfile.dev`

I can subscribe to star (*) in the Debugger UI, then publish an update through the debugger UI also, and the event shows up.
But if i perform an action on the API that triggers a Mercure Hub update there, then the event does not show up in the debugger UI. And from the Symfony WebProfiler it does look like the Update gets sent properly to the Hub.

![image](https://user-images.githubusercontent.com/1397886/142994789-0c0aa4bc-995b-4c3b-878d-522c0acc996d.png)

![image](https://user-images.githubusercontent.com/1397886/142994997-78de37c2-2e50-413d-9154-d7f6083bfdbe.png)

Any help would be greatly appreciated. 
Later on would like to deploy this to AWS.

**Comment by velreine** [comment]
Turns out that when it tries to notify the "hub" it instead POSTS to the Symfony API Server (port 8000) which for some reason also implements the Mercure protocol?

This is because the applied environment variables overrides my environment variables set in ".env" so even though i set MERCURE_URL=https://127.0.0.1:443/.well-known/mercure
 and 
MERCURE_PUBLIC_URL =https://127.0.0.1:443/.well-known/mercure

The env variable is overriden to be https://127.0.0.1:8000 (the symfony server).

This happens when running the CLI version of Symfony.

So i suppose that the Server tries to set these environment variables itself even though they are already defined in the file ".env"

**Comment by dunglas** [comment]
Are you running an old version of Symfony CLI? This feature have been removed from this tool.

**Comment by dunglas** [comment]
Can you also check if you aren't using Docker Compose? If so, indeed Symfony CLI will use the Mercure service defined in `docker-compose.yml` automatically. Removing this service should be enough to disable this behavior.

**Comment by velreine** [comment]
Sorry for the late reply, i was not in the office.

The Symfony CLI version is v4.25.9

And I was not running Mercure via the docker-compose I downloaded a pre-built binary for Linux (Debian) x86_64. And I was fiddling around with the Caddyfile etc, manually.

I'm on Ubuntu 20.04.
