### ISSUE TITLE
Subscribers Cloudflare issue

### ISSUE THREAD

**Issue by kokojar** [dunglas/mercure#593]
I am using mercure with symfony docker integration. When I query the endpoint /subscribers everything is fine until I enable the cloud icon in the Cloudflare dns settings.

MERCURE_PUBLISH_URL=https://kokojar.co.uk/.well-known/mercure

When I enable the orange cloud icon, and query /subscribers it shows me some subscribers that shouldn't be there because the browser active session windows have been closed. Something is caching for 2-3 minutes.

I've tried setting a Baypass cache  in cf page rules for the entire domain, but that doesn't do anything. Only after disabling the cloud icon everything starts working as it should - no lag in the subscribers list.

**Comment by dunglas** [comment]
It looks like an issue on Cloudflare-side. AFAIK we send all headers preventing reverse proxies to cache. Did you try to contact Cloudflare's support?
