### ISSUE TITLE
Binary (or how to build)

### ISSUE THREAD

**Issue by pdiveris** [dunglas/mercure#60]
Apologies, I am editing/changing the issue.
I've cloned the repo on my mac (rather than debian). I then ran:
```
go get github.com/dunglas/mercure/hub
go get github.com/joho/godotenv/autoload
go get github.com/joonix/log
```
to install the dependencies. Now when I do a `go run main.go` I get the following:

```
# github.com/dunglas/mercure/hub
../github.com/dunglas/mercure/hub/demo.go:40:11: unknown field 'SameSite' in struct literal of type http.Cookie
```
Any ideas?

**Comment by pdiveris** [comment]
I don't seem to be able to close this issue. I've managed to compile/build mercure by commenting the line out. The binary seems working - I will test the client side pf things tomorrow. I am note sure as to what impact this commenting out may have.

**Comment by dunglas** [comment]
This project use the new GO module system, to build it it's easier that that:

```
$ git clone https://github.com/dunglas/mercure
$ cd mercure
$ GO111MODULE=on go get
$ GO111MODULE=on go build
```

You're all set!

**Comment by drychlik76** [comment]
I attempted to GO111MODULE however I am seeing the same error reported by pdiveris.
`GO111MODULE=on go get`
[# github.com/dunglas/mercure/hub
../github.com/dunglas/mercure/hub/demo.go:40:11: unknown field 'SameSite' in struct literal of type http.Cookie
../github.com/dunglas/mercure/hub/event.go:26:8: undefined: strings.Builder
](url)

**Comment by drychlik76** [comment]
Ok. I found the problem.  On my centos 7 system, it appears that the Cookie struct is missing SameSite from the struct.  I am assuming that this system has an old version of the golang.

**Comment by dunglas** [comment]
Yes you need the latest stable version of Go.
