### ISSUE TITLE
how to get it work in production !!!!

### ISSUE THREAD

**Issue by xorgxx** [dunglas/mercure#606]
HI i'm trying to get it work on production !!!! for 4 weeks !!!

it work find on dev mode "anonymous" but as soon you try in production IT NEVER STOP TO SAIS "Unauthorized"

working in prod only form demo "/.well-known/mercure/ui/" then it send recieve ....

Maybe there is some where one tuto "up to date" how explain how to user in PRODUCTION !!

**Comment by xorgxx** [comment]
what are they    
# Publisher JWT key
        publisher_jwt "I8M59BUx0NM8SYi"   -> it must be what ?? pass OR JWT KEY ????

        # Subscriber JWT key
        subscriber_jwt "I8M59BUx0NM8SYi"   -> it must be what ?? pass OR JWT KEY ????

**Comment by xorgxx** [comment]
so i have find the major probleme ssl apache !!!
```
            return $this->httpClient->request('POST', $this->getUrl(), [
                'auth_bearer' => $jwt,
                'verify_peer' => false,       ------->>>>> here, them all working find
                'body' => Internal\QueryBuilder::build($postData),
            ])->getContent();
```

my probleme is that i dont have any root access to change apache to make him "proxy" !!!
so then what can be may solution ? 
 -  'verify_peer' => false,  
 - not to use mercure !

thank for help

**Comment by T-Nagui** [comment]
@xorgxx i just figurat out the JWT is the secret key used in symfony config
