### ISSUE TITLE
Use lastEvendID instead of Last-Event-ID as query parameter

### ISSUE THREAD

**Issue by dunglas** [dunglas/mercure#613]
To be in sync with the default parameter supported by the most popular EventSource polyfill: https://github.com/Yaffle/EventSource#custom-query-parameter-name-for-the-last-event-id

**Comment by divine** [comment]
Hello,

1. I think that the library instead should change that header to follow up standards.
2. Also, when `authorization query parameter` will be merged https://github.com/dunglas/mercure/pull/562 I'd gladly drop it as well. 

Just my 2 cents.

Thanks!

**Comment by dunglas** [comment]
@divine the header is standardized but not the query parameter. As this polyfill is widely used and is the library having introduced this query parameter, it's the de-facto standard. Also, this is more consistent with popular conventions used for query parameters. This will also make the polyfill work "out of the box", while it currently requires custom configuration to be compatible with Mercure, which is frequently forgotten by users. 

Regarding #562, I don't see how it relates to this issue.

**Comment by divine** [comment]
> @divine the header is standardized but not the query parameter. As this polyfill is widely used and is the library having introduced this query parameter, it's the de-facto standard. Also, this is more consistent with popular conventions used for query parameters. This will also make the polyfill work "out of the box", while it currently requires custom configuration to be compatible with Mercure, which is frequently forgotten by users.
> 

Oh, I see it now, thank you for detailed explanation!

> Regarding #562, I don't see how it relates to this issue.

The main reason that most of us are using polyfill is because "authorization headers" aren't supported in native SSE.

Thanks!
