### ISSUE TITLE
CORS policy Issue : No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by James02200** [dunglas/mercure#618]
Hi All,

Hope you are well ? :)

I have some CORS issue  integrating  a Nginx container reverse proxy with a mercure-caddy container on AWS behind an Application load balancer (ALB) with an Auto-Signed ssl on it (no ssl on Nginx side). 
For your information, i am using : 

1. Fargate AWS for all containers staff
2. dunglas/mercure:latest  of mercure image.
3. nginx:alpine image

My issue detail is the following :
_Access to resource at 'https://mercure-alb-xxxxxx.elb.amazonaws.com/.well-known/mercure?topic=%2Fusers%2F06bf2eb9-044a-4fca-855b-9d356a48952e%2Fnotifications' 
from origin 'https://front-alb-xxxxxx.elb.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

Log detail in mercure :

```
_{"level":"info","ts":1645523182.4035444,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"127.0.0.1:60062","proto":"HTTP/1.1","method":"GET","host":"back-mercure","uri":"/.well-known/mercure?topic=%2Fusers%2F06bf2eb9-044a-4fca-855b-9d356a48952e%2Fnotifications","headers":{"X-Forwarded-Host":["mercure-alb-xxxxxx.elb.amazonaws.com"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Google Chrome\";v=\"98\""],"Cache-Control":["no-cache"],"Accept-Language":["en-GB,en-US;q=0.9,en;q=0.8"],"Sec-Fetch-Dest":["empty"],"Referer":["https://front-alb-xxxxxx.elb.amazonaws.com/"],"Accept-Encoding":["gzip, deflate, br"],"X-Forwarded-For":["90.24.162.120, ::ffff:10.1.1.126"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Origin":["https://front-albxxxxxx.elb.amazonaws.com"],"Sec-Fetch-Site":["cross-site"],"Sec-Fetch-Mode":["cors"],"X-Forwarded-Proto":["http"],"X-Amzn-Trace-Id":["Root=1-6214b0ee-2b6a0826276c3e21497370a3"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"],"X-Forwarded-Port":["443"],"Accept":["text/event-stream"],"Sec-Ch-Ua-Mobile":["?0"]}},"common_log":"127.0.0.1 - - [22/Feb/2022:09:46:22 +0000] \"GET /.well-known/mercure?topic=%2Fusers%2F06bf2eb9-044a-4fca-855b-9d356a48952e%2Fnotifications HTTP/1.1\" 0 0","duration":0.000003481,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}_
```

What is strange is that on my Caddyfile i have the following conf allowing  specific cross-origin URL:

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
  {$DEBUG}
  # servers :3001 {
  # protocol {
  #   allow_h2c
  # } 
  #}
  http_port 3000
  }
  
   # {
   #    auto_https off
   # }
   #{
   #	{$GLOBAL_OPTIONS}
   #}

   {$SERVER_NAME:localhost:3000}
   
   log {
       output file /var/log/caddyfile.log
   }
   
   route {
       redir / /.well-known/mercure/ui/
       encode gzip

        mercure {
           # Transport to use (default to Bolt)
        transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
           # Publisher JWT key
        publisher_jwt xxxxxxx
           # Subscriber JWT key
        subscriber_jwt xxxxxx 
        
        {$MERCURE_EXTRA_DIRECTIVES}
        publish_origins https://back-alb-xxxxxx.elb.amazonaws.com   
        cors_origins    https://front-alb-xxxxxx.elb.amazonaws.com  
        subscriptions
       }
   
       respond /healthz 200
   
       respond "Not Found" 404
   }
```

My Nginx reverse proxy conf is the following :

```
 upstream back-mercure {
  server localhost:3000;
}

 server {
    
    listen [::]:80 default_server ipv6only=off;
    server_name localhost;
    server_tokens off;

    location /elb-status {
     access_log off;
     return 200;
    }

    location / {

        proxy_pass http://back-mercure;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
```

Thanks for you help and support.
Best Regards,
Jamel

**Comment by dunglas** [comment]
Are you using the AWS WAF? It is known to cause issues: https://github.com/dunglas/mercure/issues/487

**Comment by James02200** [comment]
Hi Kévin,

No WAF. 

Thanks.
Jamel

**Comment by naxo8628** [comment]
I have the similiar problem when i request using **chart helm** 

Access to resource at **'..../.well-known/mercure?topic=....'** from origin 'https://mydomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If i check the response's header in Postman, the Access-Control-Allow-Origin is not present, any ideas?

this is the full values apply on helm chart:

`
globalOptions: ""
dev: false
transportUrl: bolt:///data/mercure.db?size=100&cleanup_frequency=0.4
extraDirectives: "anonymous publish_origins * write_timeout 0 ui cors_origins *"

publisherJwtKey: "MYJwtPassword"
publisherJwtAlg: HS256

subscriberJwtKey: "MYJwtSubcriberPassword"
subscriberJwtAlg: HS256

# -- The license key for [the High Availability version](https://mercure.rocks/docs/hub/cluster) (not necessary is you use the FOSS version).
license: ""

# -- The number of replicas (pods) to launch, must be 1 unless you are using [the High Availability version](https://mercure.rocks/docs/hub/cluster).
replicaCount: 1

image:
  repository: dunglas/mercure
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Annotations to be added to pods.
podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations:
    cloud.google.com/backend-config: '{"default": "mercure-config"}'
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: ""
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  hosts:
    - host: mydomain.site
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - secretName: google-tls-cert
      hosts:
        - mydomain.site

resources:
  requests:
    cpu: 1
    memory: 2Gi

# -- Autoscaling must not be enabled unless you are using [the High Availability version](https://mercure.rocks/docs/hub/cluster) (see [values.yaml](values.yaml) for details).
# @default -- Disabled by default.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
affinity: {}

# -- Enable persistence using [Persistent Volume Claims](http://kubernetes.io/docs/user-guide/persistent-volumes/), only useful if you the BoltDB transport.
persistence:
  enabled: false
  # -- Mercure Data Persistent Volume Storage Class.
  # If defined, `storageClassName: <storageClass>`
  # If set to `"-"``, `storageClassName: ""``, which disables dynamic provisioning.
  # If undefined (the default) or set to `null`, no `storageClassName` spec is set, choosing the default provisioner.
  storageClass: ""

  # -- A manually managed Persistent Volume and Claim.
  # Requires `persistence.enabled: true`
  # If defined, PVC must be created manually before volume will be bound.
  accessMode: ReadWriteOnce
  size: 1Gi

  # -- a manually managed Persistent Volume Claim
  # -- Requires `persistence.enabled: true`
  # -- If defined, PVC must be created manually before volume will be bound
  existingClaim: ""`
