### ISSUE TITLE
How to close a SSE connection immediately

### ISSUE THREAD

**Issue by JoergSommer** [dunglas/mercure#624]
I Have tesed a bit around Mercure SSE connections and closing.

If you close a connected event source from your Mercure server it is not closed on the server side. Instead of closing the connection you can see in your log that nothing happens for approx. 1 min and THEN the connection times out.

If you go from site to site of your webapp you will close the old event source and open a new one. If you do this often you ends up with so many open connections that you can not connect the server anymore. Connected with the Mercure server directly the limit is 150 (and that is no problem) but using a apache2 proxy to the Mercure server lowers the limit of open connections to 6 (and that is a problem)

Any idear how I can close the connections on server side faster? Or how I can get more concurrent connections over a apache proxy?

**Comment by dunglas** [comment]
This looks like a bug. The connection should be stopped as soon as the client disconnects: https://github.com/dunglas/mercure/blob/main/subscribe.go#L42=

Could you provide a reproducer?

**Comment by wedel220** [comment]
@dunglas Hi! I have the same issue.

Starting server with 

`MERCURE_PUBLISHER_JWT_KEY='...' MERCURE_SUBSCRIBER_JWT_KEY='...' MERCURE_EXTRA_DIRECTIVES='cors_origins ...' SERVER_NAME=:3002 ./mercure run
`

And it sits behind Apache reverse proxy

`
ProxyPass "/"  "http://localhost:3002/"
ProxyPassReverse "/"  "http://localhost:3002/" 
`

But when i close the page, socket doesn't disconnect. Logs for disconnecting appear about 10 mins later.
Was wondering if maybe Apache's reverse proxy keeps the connection alive for a longer time then it should
