### ISSUE TITLE
Deploy mercure with docker on an Apache server

### ISSUE THREAD

**Issue by tsiatka** [dunglas/mercure#627]
Hello,

I'm having trouble to deploy mercure with docker on my apache server where I already have a symfony app running on a custom domain.

Here is my docker-compose.yml file 

```
version: "3"

services:
  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: always
    ports:
      - 1337:1337
    environment:
      SERVER_NAME: ":1337"
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    # Comment the following line to disable the development mode
    #command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
```

My Apache directive
```
ProxyRequests off

<LocationMatch>
      ProxyPass http://localhost:1337
      ProxyPassReverse http://localhost:1337
</LocationMatch>
```

Here are my environment variables
```
MERCURE_URL=http://localhost:1337/.well-known/mercure
MERCURE_PUBLIC_URL=http://localhost:1337/.well-known/mercure
```

I get a `Failed to load resource: net::ERR_CONNECTION_REFUSED` in my console.
When I try to replace localhost by my domain in the mercure url and public_url, I get a 404 error.

I think I do not understand how my symfony app is supposed to communicate with the hub in production.

The docker seems to be running fine : 
```
docker port web_mercure_1
1337/tcp -> 0.0.0.0:1337
1337/tcp -> :::1337
```

Thanks in advance !

**Comment by dunglas** [comment]
HTTPS doesn't look disabled, it's probably the issue. Can you try to set this environment variable: `GLOBAL_OPTIONS=auto_https off`

Try to connect directly to the hub (using `curl` for instance) to check if is working properly and if HTTPS is disabled.
