### ISSUE TITLE
Offer more debug on infamous 401

### ISSUE THREAD

**Issue by althaus** [dunglas/mercure#63]
Hey,

after sorting out the CORS issue with anonymous request, I'm trying to use authorized ones, but the 401 is driving me nuts. I'm running on a my.test domain and mercure is running on my.test:3000. It somehow seems that the browser doesn't want to send the cookie along with the EventSource. At least it cannot be found in the Request Headers section in the dev tools.

The cookie is created through a Symfony action:

>Set-Cookie: mercureAuthorization=...; path=/hub; httponly; samesite=strict

and I can verify it on jwt.io.

1) I tried to use `withCredentials: true` on the EventSource, but than the browser complains that `*` is not allowed in the CORS_ALLOWED_ORIGINS.

2) I then tried to use CORS_ALLOWED_ORIGINS=http://localhost, but then Chrome complains that "No 'Access-Control-Allow-Origin' header is present" and the network tab shows no response headers at all.

3) I then set CORS_ALLOWED_ORIGINS=http://my.test. This way I get a proper `Access-Control-Allow-Origin: http://my.test` response header, but along with the 401 and no cookie in the request headers.

4) If I access http://my.test:3000/hub?topic=... directly the cookie is properly sent.

So... what setup **should**? Should the same-site cookie be send with EventSource w/o credentials? Should it work with CORS_ALLOWED_ORIGINS=*?

And pleeease add a reason for the 401 when running with DEBUG=1. There are so many different things which can go wrong and mercure has to know what it doesn't like.

Cheers
Matthias

**Comment by dunglas** [comment]
Could you provide a repo with a minimal reproducer. It's hard to tell without access to your setup. But indeed it's a good idea to add more logs in case of 401. I'll add it.

**Comment by althaus** [comment]
I just dropped mercure in a current project, so nothing to share easily. I'll see if I can spare some time to setup a MVP. What about the EventSource-Cookie-thing? Should it work with or without the  `withCredentials` option?

> But indeed it's a good idea to add more logs in case of 401. I'll add it.

Cheers! Being used to the web profiler just getting a 401 is such a pity. Would be happy to even got more debug or a verboose debug level. 👍

**Comment by dunglas** [comment]
> What about the EventSource-Cookie-thing? Should it work with or without the withCredentials option?

To use the authorization mechanism, the hub and the app **must** use the same domain. If they share the same domain, but have a different subdomain, you must set `withCredentials`.

**Comment by althaus** [comment]
Ok... so running my.test my.test:3000 shouldn't require the `withCredentials`. Then I don't understand why it looks like the cookie isn't sent. Will wait for the next update.

**Comment by Fragles** [comment]
Hey guys,
I am testing Mercure and I encountered the same problem.
I have a docker container with mercure on port 3000 and Symfony web app at port 80.

The problem is that EventSource don't send Cookie header and don't get any messages from Symfony. 
When I enter the url **symfony.test:3000/hub?topic=TOPIC** and I set cookie with JWT token I can see all the messages which I am sending.

I also tried the EventSource with withCredentials option but then is problem with CORS.
`The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

Maybe have you got any example how to send JWT token with EventSource polyfill and Authorization header?

Thank You!

**Comment by dunglas** [comment]
@Fragles `*` is not allowed in this case, you must list explicitly the domain of your Symfony app as an allowed origin.

**Comment by Ilshidur** [comment]
I guess setting `CORS_ALLOWED_ORIGINS` to `'*'` won't be possible because Mercure needs to access the `Cookie` header of the `GET` request, hence `withCredentials` is required.

However, browsers won't allow a CORS requests with credentials if the server provides `'*'` in the `Access-Control-Allow-Origin` header. See [this StackOverflow post](https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i) that will explain why.

**Comment by Fragles** [comment]
@dunglas  yeah I tried to set env CORS_ALLOWED_ORIGINS and PUBLISH_ALLOWED_ORIGINS to symfony.test:3000 and symfony.test:80 but with no effect.

Now I switched to method with header 'Authorization' and I continue testing.

**Comment by althaus** [comment]
@Fragles Be sure to check the format. `CORS_ALLOWED_ORIGINS` must be proper "http://your.domain" value including protocol and missing ports: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Examples

@dunglas Would be great if mercure could validate the parameters.

**Comment by Fragles** [comment]
@althaus I will check once again but I am pretty sure that I tried something like this.

To be sure, I need to specify both ports 80 for web and 3000 for Mercure hub with http protocol right?
For example:
`http://symfony.test:80,http://symfony.test:3000`

Am I right?

**Comment by althaus** [comment]
You don't need to set the hub and that one is sending the header, so just `CORS_ALLOWED_ORIGINS=http://symfony.test` **should** be the way to go.

**Comment by Fragles** [comment]
Ok, so when creating new EventSource I added  `withCredentials: true` and in enviroments I set `CORS_ALLOWED_ORIGINS=http://symfony.test` and now I get 401 Unauthorized.

![image](https://user-images.githubusercontent.com/816162/54759382-42692f00-4bee-11e9-985a-ec0600b3e5b2.png)

No cookie is sent to the hub :/

**Comment by dunglas** [comment]
What's the full URL of your Symfony, and the full URL of your hub please?

**Comment by Fragles** [comment]
Hello,
URL to hub: http://symfonytests.lh:3000/hub?topic={topic}
URL to Symfony app: 
http://symfonytests.lh/test/publish - action to publish message
http://symfonytests.lh/test/receive - html with EventSource connection

**Comment by dunglas** [comment]
The topic you use isn't valid. Can you also copy the cookie value and attributes?

**Comment by Fragles** [comment]
Here is cookie which works on the hub:

![image](https://user-images.githubusercontent.com/816162/54810893-85c3ac00-4c87-11e9-9bab-9629b1cb7572.png)

And I am setting cookie from Symfony:
```php
$response->headers->set(
    'set-cookie',
    sprintf('mercureAuthorization=%s; path=/hub; SameSite=strict', $token) //secure; httponly;
);

```

And when I enter the url: 
http://symfonytests.lh:3000/hub?topic=http://example.com/books/1

Everything works, but no cookie is sent from EventSource when I try to inject received messages into html div.

**Comment by dunglas** [comment]
@Fragles do you think you can give me access to the repository to debug?

**Comment by Fragles** [comment]
Yeah, I can give you access but I need some time to move it from one repo to another.
Thanks.

**Comment by Fragles** [comment]
@dunglas please take a look here:
https://github.com/Fragles/symfony-mercure-test

I haven't changed the configuration because maybe the nginx proxy is a problem?

All info is in readme.md.

**Comment by dunglas** [comment]
Unfortunately it doesn't work on Mac.

**Comment by BowlOfSoup** [comment]
> Unfortunately it doesn't work on Mac.

Do you mean that on a Mac I'll always get a 401 (when ALLOW_ANONYMOUS=0) ?

**Comment by dunglas** [comment]
@BowlOfSoup no :), @Fragles doesn't work on Mac!

**Comment by gdalyy** [comment]
set the cookie this way , you must include the domain : 
>Symfony app : yourdomaine.com
>Mercure Hub: chat.yourdomaine.com

```
"mercureAuthorization={$token}; Path=/hub; domain=.yourdomain.com; HttpOnly";
```
Don't forget the **.** before yourdomaine

**Comment by bycrea** [comment]
Hello, 

Has someone find a solution for this issue? 

I'm facing the same problem, I can't see the "meruceAutorisation" cookie inside the "http://localhost:3000/.well-known/mercure?topic=..." headers. 
I've tried to add "domain=.mydomain.com", but still. 

Thanks a lot.

**Comment by gdalyy** [comment]
In your JS , did you set `withCredentials` to `true` ? 

This way : 
```
const url = new URL('http://your_hub/.well-known/mercure');
url.searchParams.append('topic', 'your_topic');

const eventSource = new EventSource(url, {withCredentials: true});
```

**Comment by bycrea** [comment]
Hi gdalyy, 
Yes I did, like this: 

```
const url = new URL('http://localhost:3000/.well-known/mercure');
url.searchParams.append('topic', 'http://notify.com/');

const eventSource = new EventSource(url, {withCredentials: true});
console.log(eventSource);
eventSource.onmessage = e => {
    const data = JSON.parse(e.data);
    console.log(data);
    let $title = document.querySelector('#main');
    $title.innerHTML = data;
}
```

I can even console.log my eventSource and get : 
`EventSource {url: "http://localhost:3000/.well-known/mercure?topic=http://notify.com/", withCredentials: true, readyState: 0, onopen: null, onmessage: null, …}`

Here is my homePage cookie : 
`Set-Cookie: mercureAuthorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJodHRwOlwvXC9ub3RpZnkuY29tXC9wYXJhbmdvblwvdGVhbSJdfX0.e5YOGcOx-s-8nn2lbseqcVlk18dVEvgZIoKrDCEureA; path=/.well-known/mercure; domain=.domain.local; httponly; samesite=strict`

My event source Request
`Request URL: http://localhost:3000/.well-known/mercure?topic=http://notify.com/` 
No Set-Coockie indside.

**Comment by gdalyy** [comment]
You don't new the `domain` param in a local installation , just use : 
`mercureAuthorization={$token}; Path=/.well-known/mercure; HttpOnly;`

**Comment by bycrea** [comment]
Well thanks for this advice, but it's not working without it anyway :))

**Comment by bycrea** [comment]
Sorry to ask again but I don't find a solution...

Here is what I get, As soon as I use {withCredentials: true} **firefox** is kicking out the request
(every thing is fine on Chrome)  

`
'same origin' policy don't allow consulting 'http://localhost:3000/.well-known/mercure ... '
Reason: CORS header 'Access-Control-Allow-Origin' missing
`

Mercure --debug mode print this
```
INFO[0008] New subscriber  remote_addr="127.0.0.1:55992" subscriber_topics="[http://notify.com/]"
INFO[0008] Subscriber disconnected remote_addr="127.0.0.1:55992" subscriber_topics="[http://notify.com/]"
127.0.0.1 - - [31/Jan/2020:12:48:02 +0100] "GET /.well-known/mercure?topic=http%3A%2F%2Fnotify.com%2F HTTP/1.1" 200 2 "http://parangon-creations.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0"
```
(anyone knows where the logs are?) 

A part from that, I can't manage to get the 'mercureAuthorization' cookie inside the eventSource request. 

Thanks, sorry to bother you :(

**Comment by gdalyy** [comment]
Hello when lauching mercure server try to add this parameter : 
`CORS_ALLOWED_ORIGINS="*"` 

PS: in prod , set the correct origins.

**Comment by vico-gs** [comment]
> @Fragles `*` is not allowed in this case, you must list explicitly the domain of your Symfony app as an allowed origin.

Thank you for confirming that. @dunglas 
Regex are not allowed as well, is there a way to allow more domains ?
