### ISSUE TITLE
Multiple questions concerning Mercure security and Caddyfile

### ISSUE THREAD

**Issue by geoffroyp** [dunglas/mercure#630]
Greetings to you all,

I would like to implement Mercure in one of my symfony project, but I haven't been able to find any answer to a bunch of questions, either in documentation or internet in general.

### Privacy/Security:

Imagine that I would like to implement a private messages system on my website, which would use topics such as `https://chat.mysite.com/{userId}`
From what I understand, only a server which has a JWT token signed by the same secret key than the on Mercure Hub can publish in the private topic dedicated to a user (let's say `https://chat.mysite.com/42` ), and only a client which also has this same secret key and the same topic (`https://chat.mysite.com/42`) can subscribe to the Hub and get the datas sent by server. 

Ok. 

But if I include this secret key used to sign the JWT token in my frontend client, any other user with a bit of code knowledge could easily retrieve this "not-so-secret" key, then generate a valid JWT token which would contains a subscription to the topic of another user (for instance, `https://chat.mysite.com/1664` ) and read its private message. 
Even worse: the victim wouldn't even know that someone is reading its private message, since the message would be sent to both the "real" user and the "hacker".
A solution would then consist about not providing the frontend client with the JWT secret key used to sign tokens, but to directly send the token to the front -let's say during login- so it can store it somewhere (localstorage, cookie...). This JWT token would contain all topics to which front user could subscribe to. 
This way, it would be way harder to "forge" a JWT token containing 'forbidden" topics.
However, this solution now has another problem. It cannot work with topics that includes IDs which are not fix values. For instance, imagine a topic sending details about movies. we would then get a topic like https://chat.mysite.com/movie/{id} but there are millions of movies, and we cannot send all these generated topics in the JWT token payload, otherwise it would be a MASSIVE token. So we have to let the frontend client "build" its own topics, then generate its own JWT token everytime it add/remove a topic. But then we are back to the first solution, which is not secure...
Am I right? Am I missing something? is there a way to fix this, or a "best practice" that would not generate such problems?

### Caddy configuration

I've read your documentation and the one from caddy, but there's something I quite don't understand. Let's say I would like to have my hub on `https://mercure.mysite.com`.
I'm starting it by using the following command: 
`MERCURE_PUBLISHER_JWT_KEY='!ChangeMe!' MERCURE_SUBSCRIBER_JWT_KEY='!ChangeMe!' SERVER_NAME='mercure.mysite.com' ./mercure run -config Caddyfile.dev`

- If I do this, mercure hub can't start telling me that port 443 is already in use (yes, it's used by apache)

- If I set `SERVER_NAME` to `mercure.mysite.com:8443`, mercure hub can't start telling me that port 80 (wtf?) is already in use (yes, it's used by apache)

- if I set `SERVER_NAME` to `:8443`, it starts, on port 8443, but then my domain is not set and I have to type my VM IP to access it (= 192.168.1.43:8443)

- I've tried to modify my Caddyfile.dev to achieve this but no success either. I've read caddyserver's documentation and from what I understand, I should be able to write "mercure.mysite.com:8443" instead of `{$SERVER_NAME:localhost}` , but doing so only result in mercure refusing to start due to port 80 (again, wtf?! ) already being in use (yes, apache does use it)

Sooo...how can I configure Mercure(caddy) in order to make it available on mercure.mysite.com:8443 ?

**Comment by alexmao1024** [comment]
I have the same question, hope someone will answer it.

**Comment by dunglas** [comment]
> But if I include this secret key used to sign the JWT token in my frontend client, any other user with a bit of code knowledge could easily retrieve this "not-so-secret" key

Indeed, your key must not leak to the client. The JWT must be generated server-side, then transmitted to the client. The cookie can also be set directly by your server. See https://symfony.com/doc/current/mercure.html for an example.

> However, this solution now has another problem. It cannot work with topics that includes IDs which are not fix values. 

A trick that could be used here is using ["alternate topic IRIs"](https://mercure.rocks/spec#publication) in conjunction with URI template topic selectors.

For instance, to send the following update:

```
topic=https://chat.mysite.com/movie/1235
topic=https://chat.mysite.com/user/5678/movie/1235 <--- alternate topic
```

You could also use something like `https://chat.mysite.com/group/foobar/movie/1235` to prevent alternate topics proliferation in case you have many users having access to a movie.

Then, users can subscribe using the following topic selector to receive all updates they are allowed to `https://chat.mysite.com/user/5678/movie/{id}`.

Does this work for your use case?

> Caddy configuration

Caddy automatically enable TLS and setup a redirect from HTTP to HTTPS resources. You can tweak or disable this feature using the `auto_https` directive: https://caddyserver.com/docs/caddyfile/options#auto-https

For instance, to entirely disable TLS, you can set the following environment variable:  `GLOBAL_OPTIONS=auto_https off`.

**Comment by geoffroyp** [comment]
Concerning IDs, I'm not sure. When you say that my user could subscribe to `https://chat.mysite.com/user/5678/movie/{id}`, does it means that `{id}` is actually a valid value that is interpreted by mercure as a variable? 
If yes, then that was the info I was missing, because then it mean I could indeed only send this to my client and it would subscribe to any movie ID

About the TLS part, I don't think we're talking about the same thing. To make it short, I was asking you how to start my server in HTTPS mode on port 8443, and with the address set to https://mercure.mysite.com ? I've tried many things but none works. 
It doesn't matter what I write in `SERVER_NAME` parameter, it always tries to start on port 443 or 80, while I'm asking for 8443 since they both are already used by apache.
The only time it works is when I start it with `SERVER_NAME=':8443'`, but in this case it starts as localhost:8443, not mercure.mysite.com:8443

alternatively: is there a (rather easy) way to use mercure with apache?

Thank you for your answer!

**Comment by frizquierdo** [comment]
@geoffroyp, first sorry for my english. 
Concerning to IDs: The idea is to create a valid url on the server side identifies the topic, and that can in this case, differentiate from one movie or another, which is why it is suggested to include the id of the movie stored in the database in the topic , in such a way that all the clients that subscribe to the topic can generate its url obtaining the id of the movie from database.

About mercure hub url: 
From what i can see, you work with private subscriptions, so your mercure hub must run over https (mandatory). The hub URL must be on the same domain or subdomain of your web application, ok! In this case, the solution is to create a reverse proxy rule on your apache server (or nginx), so that all requests containing for example the /.mercure/well-known fragment are redirected to the url and port of your Mercure hub server (Caddy server). 

This is an example of Mercure with the variable` MERCURE_PUBLIC_URL = 'https://mysite.com/.well-known/mercure'` and the web application running at https://mysite.com

Caddy fragment:
```
{
	http_port 8081
	https_port 8443
	auto_https disable_redirects #it grant that caddy don't work over HTTP
	#{$GLOBAL_OPTIONS}
}
{$SERVER_NAME:mysite.com:8443}
tls C:\wamp64\bin\apache\apache2.4.51\conf\ssl\mysite.com.crt C:\wamp64\bin\apache\apache2.4.51\conf\ssl\mysite.com.key
```
And, the Apache SSL virtual host:
```
<VirtualHost ip_interface:443>
   ServerName mysite.com
   ServerAlias wwww.mysite.com
  
   DocumentRoot "/var/www/mysite.com/public"
   DirectoryIndex index.php
    
   <Directory "/var/www/mysite.com/public/"> 
    AllowOverride All
    Order Allow,Deny
    Allow from All
    #Require local
    Require all granted
   
    <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ index.php [QSA,L]
    </IfModule>   
   </Directory>
  
   SSLEngine on
   SSLProtocol all -SSLv3 -SSLv2  
   SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL 
   SSLCertificateFile "/etc/apache2/conf/ssl/mysite.com.crt" 
   SSLCertificateKeyFile "/etc/apache/apache2/conf/ssl/mysite.com.key"   
   SSLUseStapling off
  
   <FilesMatch "\.(cgi|shtml|pl|asp|php)$"> 
    SSLOptions +StdEnvVars 
   </FilesMatch>
    
   BrowserMatch ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
  
   SSLProxyEngine On
   ProxyRequests Off
   ProxyPreserveHost On
   ProxyPass '/.well-known/mercure' 'https://mysite.com:8443/.well-known/mercure' connectiontimeout=300 timeout=300
   ProxyPassReverse '/.well-known/mercure' 'https://mysite.com:8443/.well-known/mercure'   
 </VirtualHost>
```
Remember active _**mod_proxy**_ on web server

**Comment by wedel220** [comment]
@frizquierdo Hi! I've made the same setup, but mercure tells me that the protocol is "proto": "HTTP/1.1". Is there any way to proxy with Apache on http2?

And other problem I'm having is the connections closing about 10 mins after closing/refreshing the browser. With limit of 6 connections it's impossible to work with
