### ISSUE TITLE
Mercure keeps binding to port 80

### ISSUE THREAD

**Issue by sticky-web** [dunglas/mercure#644]
I'm using the Mercure hub 0.13, everything works fine on my development machine, but on my test server the hub keeps on trying to bind on port 80, resulting in a error, as nginx is already running on port 80.

`run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use`

I'm starting the hub with the following command:
```
MERCURE_PUBLISHER_JWT_KEY=$(cat publisher.key.pub) \
MERCURE_PUBLISHER_JWT_ALG=RS256 \
MERCURE_SUBSCRIBER_JWT_KEY=$(cat publisher.key.pub) \
MERCURE_SUBSCRIBER_JWT_ALG=RS256 \
./mercure run -config Caddyfile.dev
```

Caddyfile.dev is as follows:
```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
        {$GLOBAL_OPTIONS}
}

{$SERVER_NAME:localhost:3000}

log

route {
        redir / /.well-known/mercure/ui/
        encode zstd gzip

        mercure {
                # Transport to use (default to Bolt)
                transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
                # Publisher JWT key
                publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
                # Subscriber JWT key
                subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
                # Permissive configuration for the development environment
                cors_origins *
                publish_origins *
                demo
                anonymous
                subscriptions
                # Extra directives
                {$MERCURE_EXTRA_DIRECTIVES}
        }

        respond /healthz 200

        respond "Not Found" 404
}
```

When I provider the SERVER_NAME as an environment variable, without a domain, `SERVER_NAME=:3000`, the hub actually starts on port 3000, but runs in http mode, which only allows for anonymous subscriptions and is not what I need.

Server:
```
Operating System: CentOS Stream 8
Kernel: Linux 4.18.0-383.el8.x86_64
Architecture: x86-64
```

Full output when trying to start the Mercure hub:
```
2022/05/10 04:50:29.605	INFO	using provided configuration	{"config_file": "Caddyfile.dev", "config_adapter": ""}
2022/05/10 04:50:29.606	WARN	input is not formatted with 'caddy fmt'	{"adapter": "caddyfile", "file": "Caddyfile.dev", "line": 3}
2022/05/10 04:50:29.609	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2022/05/10 04:50:29.610	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2022/05/10 04:50:29.610	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc0003d6150"}
2022/05/10 04:50:29.627	INFO	tls	cleaning storage unit	{"description": "FileStorage:/root/.local/share/caddy"}
2022/05/10 04:50:29.628	INFO	tls	finished cleaning storage units
2022/05/10 04:50:29.642	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
2022/05/10 04:50:29.643	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0xc0003d6150"}
run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use
```

**Comment by mxmp210** [comment]
That is because caddy will always require port 80 to issue automated SSL to direct host .well-known requests.
If you are running setup inside docker, just map port to properly address this behavior which can be proxied via nginx or apache.

or as per [Caddy Documentation](https://caddyserver.com/docs/automatic-https#activation) - do not bind to any host to disable such automated SSL and it will work.

Alternatively you can [explicitly disable it](https://caddyserver.com/docs/json/apps/http/servers/automatic_https/), but not recommended as other sites can be served from same config

```
#{$SERVER_NAME}
:3000
```

Hope this helps others who are setting it up along with existing infrastructure which is common use-case.

**Comment by sticky-web** [comment]
Thnx for your reply. I was reading about that, and according to the [documentation](https://caddyserver.com/docs/automatic-https#hostname-requirements), Caddy should fallback to [local https](https://caddyserver.com/docs/automatic-https#local-https) because of the localhost domain. Where it uses its own CA to sign its own certificates and stores them in the local trust store, so I fail to understand why port 80 would be required here?

According to the [Mercure documentation](https://mercure.rocks/spec#authorization) to use (cookie) autorization "the connection MUST use an encryption layer such as HTTPS.". From my point of understanding, this falls away when I proxy from nginx https (trough letsencrypt) to a http connection on the mercure hub?

**Comment by frizquierdo** [comment]
The solution it's on set another HTTP port for Caddy server, and disable redirections:
```
{
	**http_port 8081**
	https_port 3000
	**auto_https disable_redirects**
	#{$GLOBAL_OPTIONS}
}

{$SERVER_NAME:mysite.com:3000}

```
