### ISSUE TITLE
Firefox 100 closes the connection if no new message is received after 30 seconds

### ISSUE THREAD

**Issue by Cocray** [dunglas/mercure#646]
Hello Kevin,

I have an issue with Firefox (version 100) and Mercure 0.13. I set the write_timeout to 0s, as mentioned in the doc, but Firefox still reset the connection after 30s if no new message is received. If I send a message every 25s, the connection doesn't reset. (No this is not the solution :D)

I don't have this issue with Chrome, the connection is open only once until the eventSource closes it or the tab/browser is closed.

Do I need to change the heartbeat config or is it a bug? In fact, I don't understand what is a heartbeat, there's no definition in the doc.

Thanks!

Olivier

**Comment by dunglas** [comment]
The heartbeat is just a comment sent overt the SSE connection to precisely prevent this kind of timeouts. Keeping the default value instead of disabling it should prevent this issue as well as many issues with proxies.

**Comment by Cocray** [comment]
Ok, thanks Kevin, I'll try it right now!

**Comment by Cocray** [comment]
It works well with a heartbeat set to 20s. Thanks Kevin!

**Comment by Cocray** [comment]
I spoke too quickly, it works with Firefox on Ubuntu, but not Firefox on Windows :(

**Comment by frizquierdo** [comment]
I think the problem is on Mozilla Firefox EventSource implementation, Chrome and Edge for example, reconnect inmediately. I use [ReconnectingEventSource](https://www.npmjs.com/package/reconnecting-eventsource). "This library ensures a reconnect always happens."

**Comment by Cocray** [comment]
Thanks @frizquierdo, we'll try it.

I close the issue as it seems it is not related to Mercure
