### ISSUE TITLE
If page opened at many  browser tabs , mercure staying pending

### ISSUE THREAD

**Issue by emrevural20** [dunglas/mercure#648]
Pages make request same mercure topic. After 5 or 6 tabs , mercure staying pending. If i close other tabs, mercure works automatically.

What is then reason that problem?
Are there any request limit? 

Thanks.

**Comment by dunglas** [comment]
Are you using HTTP/1 or HTTP/2+?

**Comment by dunglas** [comment]
You can see that in the network tab of the console.

**Comment by emrevural20** [comment]
HTTP/1

**Comment by dunglas** [comment]
It's intended then. You must use HTTP/2+ (which should be the default if you follow the installation guide) to not have this limit.

See the warning on https://developer.mozilla.org/en-US/docs/Web/API/EventSource for more details.

**Comment by emrevural20** [comment]
Thank you very much.
