### ISSUE TITLE
Private and public topic

### ISSUE THREAD

**Issue by sload** [dunglas/mercure#65]
Bonjour Kévin,

Je commence par te remercier pour ce super projet qui me simplifie énormément la vie en remplacement des WebSockets.

Je me permets de t'écrire car la documentation me semble floue (ou alors je rate quelque chose) sur la notion de mises à jour privées. Je comprends que cela se joue via la notion de "targets" que l'on spécifie au niveau des pushs mais comment spécifier au niveau du token des subscribers quels sont les targets auxquels ils ont droit ?

Merci pour tes éclaircissements ;-)

**Comment by MaximePinot** [comment]
Bonjour,

Si je reprends [l'example de la documentation sur symfony.com](https://symfony.com/doc/current/mercure.html#authorization):
```php
// src/Controller/Publish.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\Publisher;
use Symfony\Component\Mercure\Update;

class PublishController
{
    public function __invoke(Publisher $publisher): Response
    {
        $update = new Update(
            'http://example.com/books/1',
            json_encode(['status' => 'OutOfStock']),
            ['http://example.com/user/kevin', 'http://example.com/groups/admin'] // Here are the targets
        );

        // Publisher's JWT must contain all of these targets or * in mercure.publish or you'll get a 401
        // Subscriber's JWT must contain at least one of these targets or * in mercure.subscribe to receive the update
        $publisher($update);

        return new Response('published to the selected targets!');
    }
}
```

Alors, les *subscribers* doivent avoir le *payload* suivant dans le token JWT:
```json
{
  "mercure": {
     "subscribe": [
        "http://example.com/user/kevin",
        "http://example.com/groups/admin"
     ]
  }
}
```

A noter qu'il faut __au moins__  une *target*, pas forcément toutes.

**Comment by sload** [comment]
Bonjour Maxime,

Si je comprends bien ton message cela signifie que la partie "subscribe" (et à priori "publish") du JWT correspond aux targets et non pas aux topics ?

Merci pour ta confirmation,
Antoine

**Comment by Spomky** [comment]
Il y a une [vidéo plutôt claire](https://www.grafikart.fr/tutoriels/symfony-mercure-1151) sur cette notion de topcis/targets.

**Comment by sidikhalifa** [comment]
Bonjour,
**Spomky** pour la vidéo je l'ai suivi moi à la rasoir, Ce pendant j'arrive à notifié tout le monde mais lorsque je veux notifié une personne en particulier ça ne marche !  je ne sais pas, c'est qu'il a fait lui en arrière plan pour le faire marcher !

**Comment by MaximePinot** [comment]
Utilises-tu le [mécanisme d'autorisation](https://github.com/dunglas/mercure/blob/master/spec/mercure.md#authorization) par ``cookie`` ? Personnellement, je n'ai pas réussi à faire fonctionner cette méthode. Comme toi, dès que je spécifiais des *targets*, je ne recevais plus les messages.

Par contre, le mécanisme d'autorisation par ``header HTTP`` fonctionne de mon côté.
Pour faire fonctionner cette méthode, il faut le [polyfill EventSource](https://github.com/Yaffle/EventSource) et initialiser la connexion de cette manière:

```javascript
const url = new URL('http://127.0.0.1:3000');
url.searchParams.append('topic', 'http://example.com/books/1');
const eventSource = new EventSourcePolyfill(url, {
    headers: {
        'Authorization': 'Bearer {{ subscriber_token }}'
    }
});

eventSource.onmessage = function(e) {
    console.log(e.data);
}
```
Il faut remplacer ``{{ subscriber_token }}`` par le token JWT du *subscriber*.

**Comment by sidikhalifa** [comment]
Bonjour MaximePinot,
Merci d'avoir partager ton expérience :wink: 

Oui en effet j'utilise le mécanisme d'autorisation par `cookie`  
Et la j'ai essayé d'utilisé la deuxième méthode comme toi en utilisant l’autorisation par `Header Http`,
pour cela j'ai installé le **EventSourcePolyfill** depuis `yarn` et j'ai mis ceci dans mon `app.js` 
```
// assets/js/app.js

var { NativeEventSource, EventSourcePolyfill } = require('event-source-polyfill/src/eventsource');
const EventSource = NativeEventSource || EventSourcePolyfill
global.EventSource = EventSource;
global.EventSourcePolyfill = EventSourcePolyfill;
```
Et dans mon template 
```
const url = new URL('http://localhost:3000/hub');
url.searchParams.append('topic', 'http://tuto.my-website.fr/ping');

const es = new EventSourcePolyfill(url, {
       headers: {
             'Authorization': 'Bearer {{ subscriber_token }}'
         }
});

es.onmessage = e => { console.log(e.data); }
```
Et je me retrouve avec ceci :point_down: 

![Capture d’écran de 2019-03-22 17-32-41](https://user-images.githubusercontent.com/14994150/54838296-892b5780-4cc8-11e9-8f95-d4637bf40300.png)

as tu croisé cette erreur au paravent et comment tu faire pour la résoudre merci

**Comment by MaximePinot** [comment]
La documentation explique les raisons pour lesquelles une erreur HTTP 401 peut être retournée : [voir ici](https://github.com/dunglas/mercure#401-unauthorized).

As-tu bien remplacé ``{{ subscriber_token }}`` par le token JWT du *subscriber* ? Voir [mon premier message](https://github.com/dunglas/mercure/issues/65#issuecomment-475527420) pour le format du *payload*.

**Comment by sidikhalifa** [comment]
Merci Maxime infiniment pour ton information ça ma permis de vois en claire d'ou venais mon problème, oui en effet le problème venais effectivement de la manière dont je génère mon `token` c'est con il fallait juste filer au `subscribe`  un `tableau` alors que moi je lui donné un `string`  j'ai pensé qu'il marche en peux comme les arguments de la méthode `update` de `MercureBundle`    
```
public function generate(User $user)
{
      $id = $user->getId();
      $token = (new Builder())
            ->set('mercure', ['subscribe' => "http://tuto.my-website.fr/user/$id"])
            ->sign(new Sha256(), $this->secret)
            ->getToken();

      return sprintf("%s", $token);
}
```
après
```
public function generate(User $user)
{
      $id = $user->getId();
      $token = (new Builder())
            ->set('mercure', ['subscribe' => ["http://tuto.my-website.fr/user/$id"]])
            ->sign(new Sha256(), $this->secret)
            ->getToken();

      return sprintf("%s", $token);
}
```

Je partage ma solution ici au cas ou quelqu'un à le même problème :sweat_smile:

**Comment by nandrzej-m** [comment]
Finally managed to make it it work.
Video posted by Spomky https://www.grafikart.fr/tutoriels/symfony-mercure-1151
does in fact explain everything.
Setting `withCredentials: true` in EventSource constructor, makes it use the mercureAuthorization cookie. Without polyfill.
```
    const es = new EventSource(hubUrl, {
        withCredentials: true,
    });
```

What's left is to set the correct cors policy in mercure `CORS_ALLOWED_ORIGINS`.

Another crucial thing (I initially missed) is to set the `path` in the cookie correctly - so it can be accessed on the mercure hub url.
If the cookie with jwt is there, you should be able to open the hub url with topic, directly in the browser, and see incoming messages.
Running it alongside same url opened in incognito mode, shows nicely if the targets work.

**Comment by dunglas** [comment]
Closing as fixed, but it would be great to improve the docs on this topic because it looks like a common issue. Do you guys have suggestions regarding how to improve the docs?
