### ISSUE TITLE
Unable to Subscribe to Private Messages

### ISSUE THREAD

**Issue by mab05k** [dunglas/mercure#651]
Using the Mercure Debugging Tools to test/debug this issue. Followed the [subscribers documentation](https://mercure.rocks/spec#subscribers). See below with my filled in values.

The subscriber is subscribed to `https://localhost/organizations/{id}` that is matched by the canonical topic of the update (`https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e`). 

This canonical topic isn't matched by the topic selector provided in its JWS claim mercure.subscribe (`/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}`). 

However, an alternate topic of the update, `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/?topic=https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e`, is matched by it. 

Consequently, this private update **will be received by this subscriber**, while other updates having a canonical topic matched by the selector provided in a topic query parameter but not matched by selectors in the mercure.subscribe claim will not.

Topics to get updates for
```
https://localhost/organizations/{id}
```
Publish Topics
```
https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e
/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/?topic=https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e
```
Token
```
{
  "mercure": {
    "publish": [
      "*"
    ],
    "subscribe": [
      "/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}"
    ]
  }
}
```

I verified with the URI template tester the URI template is correct. I also verified that subscriptions are received with the token's subscribe array = `*`. Please help!

**Comment by dunglas** [comment]
Sorry I don't understand the problem. What you describe seems to be the expected behavior AFAIU.

**Comment by mab05k** [comment]
With the configuration I've described, I do not receive private subscription messages. Did I misunderstand the spec and configuration for private messages?

**Comment by mab05k** [comment]
Through some manual testing, I believe that subscribing to Private Messages does not work as [documented](https://mercure.rocks/spec#subscribers). I was able to receive Private Messages only when the subscribed topic matches the topic selector in the token (`mercure.subscribe`) and also matches either the alternate published topic. My examples are below, but I also tested this using the exact variables from the documentation with the same results.

Works
---
#### Subscribe
Topic: `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}`
Topic Selector (in JWT `mercure.subscribe`): `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}`

#### Publish
Topics:
- `https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e` (does not match the subscribed topic)
- `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/?topic=https%3A%2F%2Flocalhost%2Forganizations%2F107e2cc6-36f1-4785-b818-81f903d5004e` (matches the subscribed topic AND `mercure.subscribe`)

#### Result
Private message received!

Does not work (but should per the [documentation](https://mercure.rocks/spec#subscribers))
---
The topic being subscribed to matches the canonical topic of what is published AND the canonical topic in `mercure.subscribe` (JWT) matches the alternate topic of the published message. This message should be received but is not.
#### Subscribe
Topic: `https://localhost/organizations/{id}`
Topic Selector (in JWT `mercure.subscribe`): `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}`

#### Publish
Topics:
- `https://localhost/organizations/107e2cc6-36f1-4785-b818-81f903d5004e` (matches subscribed topic)
- `/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/?topic=https%3A%2F%2Flocalhost%2Forganizations%2F107e2cc6-36f1-4785-b818-81f903d5004e` (matches `mercure.subscribe`)

#### Result
No message received :(

I spent some time digging through the code (sorry I'm not a Go developer). My guess is it has something to do with this interaction: https://github.com/dunglas/mercure/blob/1d02714fa68662f826665c50b361875c70f9311d/subscription.go#L108

```
!canReceive(h.topicSelectorStore, []string{currentURL}, claims.Mercure.Subscribe)
```

My assumption is that `{currentURL}` is the subscribed topic, which won't match the template defined in `mercure.subscribe`.

I hope this additional detail is helpful! I do want to put out a big thank you to you @dunglas for all of the API Platform ecosystem. It's awesome and I love working with it.

**Comment by dunglas** [comment]
I think that they are two problems in your example:

1. You mix absolute and relative URLs. Try to use absolute URLs everywhere.
2. Your topic selector only matched URLs with a final `/`, but if the topic you use hasn't a final `/`, be sure to use a final `/` Everywhere

Let me know if this fixes the issue (and thanks for the kind words!)

**Comment by dunglas** [comment]
I reproduced the issue locally, I'm working on a fix!

**Comment by dunglas** [comment]
Could you try if https://github.com/dunglas/mercure/pull/687 fixes your issue please?

**Comment by mab05k** [comment]
Bad timing on my part. I'm traveling and will check it as soon as I get back. 

Thanks for the quick look and action on this!

**Comment by mab05k** [comment]
@dunglas Verified working on my end! Thanks again.

```bash
/srv/api # caddy list-modules -versions | grep mercure
http.handlers.mercure v0.14.0-beta.2
```

Below example (cleaned up based on your suggestions too :+1: ). Sharing for anyone else looking for examples.
#### Subscribe
```
/organizations/{id}
```

#### Publish
```
/organizations/107e2cc6-36f1-4785-b818-81f903d5004e
/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/?topic=%2Forganizations%2F107e2cc6-36f1-4785-b818-81f903d5004e
```

#### Token
##### Encoded
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiL29yZ2FuaXphdGlvbnMvMTA3ZTJjYzYtMzZmMS00Nzg1LWI4MTgtODFmOTAzZDUwMDRlL3s_dG9waWN9Il0sInBheWxvYWQiOnsiaWRwSWQiOiI5ZmM5Zjg1Yi1iNTc1LTQyZWEtYmMzNi1kOTJlYTNkNmE4MDciLCJ1c2VybmFtZSI6ImFkbWluQG9yZzEuY29tIiwiZ2l2ZW5OYW1lIjoiQWRtaW4iLCJmYW1pbHlOYW1lIjoiVXNlciJ9fX0._EzWUawhWUNrsTCKPBRd-puk8QgyWy0w0rIxjcc1Zsw
```
##### Decoded
```json
{
  "mercure": {
    "publish": [
      "*"
    ],
    "subscribe": [
      "/organizations/107e2cc6-36f1-4785-b818-81f903d5004e/{?topic}"
    ],
    "payload": {
      "idpId": "9fc9f85b-b575-42ea-bc36-d92ea3d6a807",
      "username": "admin@org1.com",
      "givenName": "Admin",
      "familyName": "User"
    }
  }
}
```
