### ISSUE TITLE
Run mercure on linux

### ISSUE THREAD

**Issue by TheoD02** [dunglas/mercure#654]
Hello to all,

I can't access mercury from another machine on same network.

I have a production machine (shared host) & a development machine.

I would like to use mercury on my site, so I have a linux machine available for mercury, I can run it in localhost and access it on the linux machine but I can't access it from my dev env via the ip or hostname I entered on the remote pc even on the local network. The server returns me an error "sent an incorrect response"
I am new to linux, maybe I have a missing configuration. If someone could help me

Thanks a lot :) !

**Comment by MrSnoozles** [comment]
As this is not related to *mercure* (not "mercury") but hosting applications in general, I don't you can expect support here. Sorry.
You could however use the free managed hub: https://mercure.rocks/pricing
