### ISSUE TITLE
Provide Subscriber Public Key via Single-Line-Variable

### ISSUE THREAD

**Issue by nuil** [dunglas/mercure#665]
Hi, 

we're using mercure via azure. Unfortunately it is not possible to provide the key via the env-variables. https://github.com/dunglas/mercure/pull/191 would have solved this. 

Any idea how to solve it now?

Thanks.

**Comment by dunglas** [comment]
If Azure doesn't provide a way to set multi-line environment variables, it's a limitation of its own. Unfortunately, there is nothing we can do on our site to fix this. Did you try to contact the support of Azure?
