### ISSUE TITLE
Subscriber not disconnected after token expired

### ISSUE THREAD

**Issue by LudovicGit** [dunglas/mercure#666]
Hello,

I have an issue with expired token. it seems not working

- I generate a token with 1 minute duration
- I launch the subscribe

`curl -N --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1Ni......o7Cs8Qva4lgEg' https://my_url/.well-known/mercure?topic=https://my_topic`

- **After expiration, the subscriber is not disconnected and he still can receive data from a publication**, but If I try to launch again to subscribe, I receive an Unauthorized message (and it's normal since the token is expired)

Is that possible to fix this problem by a specific Caddy configuration or is it a real security issue in Mercure hub ?

Thanks

**Comment by dunglas** [comment]
@LudovicGit https://github.com/dunglas/mercure/pull/679 should fix this.
