### ISSUE TITLE
DOCKER Mercure : How to deal with filesystem in read only ?

### ISSUE THREAD

**Issue by labanana34** [dunglas/mercure#667]
Hello there !

I know that maybe, I'm not in the rigth place to open this issue, but I didn't find anything on your docker page to do so:
https://hub.docker.com/r/dunglas/mercure

I'm trying to make your container work with a "read only" filesystem, which is a best practice for docker containers.

When I add this option in my docker-compose file :
`read_only: true`
I have the following error :
`2022/07/13 17:47:34 invalid bolt DSN "bolt://updates.db": open updates.db: read-only file system`

Usualy I have a more explicit error with a specific folder.
Then I just add a :
`        tmpfs:
            - /fuu/bar/`
In my docker-compose file and it's OK. But not here. Ok then !

I have looked for it for a while and found this piece of documentation:
https://mercure.rocks/docs/hub/config
Part: Bolt Adapter
`-# absolute path to "updates.db"
transport_url bolt:///var/run/database.db

-# path to "updates.db" in the current directory
transport_url bolt://database.db`

So if I look for my error, I can deduce that my container is trying to access to a file on this path : "/updates.db" or "/curent-directory-of-my-user/updates.db"
Having no clue about the user, I try to add this tmpfs:
`        tmpfs:
            - /updates.db`
Resulting in this error:
`2022/07/20 14:31:22 invalid bolt DSN "bolt://updates.db": open updates.db: is a directory`

The updates.db file is store at the root folder "/" ?
Ok ... So I try to share this file in read/write volumes !
`        volumes:
            - /home/fuu/bar/updates.db:/updates.db:rw`

Then I got this error:
`2022/07/20 14:46:43 invalid bolt DSN "bolt://updates.db": open updates.db: permission denied`

So it's a question of permission ? Which user try to access this file in the container ? No clue !
I try to access to the container to gather intel :
`$ sudo docker exec -ti mercure-hub /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: read init-p: connection reset by peer: unknown`

No access to the container -_-''
I'm tired to search for answer man ...

Here the questions:
Why do you store the update.db at the root folder "/" ? Not a clean way to do it in my opinion ...
Which user try to access it ? I try different owner to this file but can't find the wrigth one. Enlight me bro !
Why I didn't find any documentation about this ? I think it's strange that I didn't find anyone having the same problem, maybe I did something wrong ? :O

Best regards.

**Comment by labanana34** [comment]
Hello there !

I'm still stuck with my Mercure Container when I try to respect the best practice !
If someone have any lead ....

Best Regards.

**Comment by dunglas** [comment]
We basically use the official Caddy image. I'm not sure there is something we can do here.

**Comment by labanana34** [comment]
Hello Dunglas !

Thanks for your answer.

I manage to make the container run with the docker-compose command:
`read_only: true`
(Which is what I want to achieve for docker security best practice reason)

But it implies that I have to mount a volume like this :
```
volumes:
   - /fuu/bar/updates.db:/updates.db:rw
```
And then put the file /fuu/bar/updates.db with wrigth to 777.
Which is not a clean way to do it.

I think I'll try to create a custom docker image based on yours with this dockerfile:
```
FROM dunglas/mercure:v0.9.0

RUN apt-get update && apt-get install -y curl
RUN groupadd -g 1001 -r myuser && useradd -m -u 1001 -g 1001 -o -s /bin/bash myuser
USER myuser
HEALTHCHECK --interval=1m --timeout=30s --retries=3 CMD curl --fail http://localhost || exit 1
```
I'll see if it's work....

Best regards.
