### ISSUE TITLE
Browser Error: net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 OK

### ISSUE THREAD

**Issue by holema** [dunglas/mercure#672]
Hello,
first of all, thanks for the great project.

I use the mercure in a project to send real time messages from the server to the client. Everythin works fine on most installations. But with one installation I have the Problem, that I get exactly after 60seconds the Error:
 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 OK

After the Connection is lost, the connet is immediatly new established by the browser. But messages send during this time are not recognized by the client and lost.

I changed from Apache2, which I used as reverse-proxy to nginx but the problem is still the same.

Is this error from mercure, or propably the nginx/apache reverse proxy.

Best regards

**Comment by dunglas** [comment]
This indeed looks like a timeout on the reverse proxy side.

You must ensure that the write timeout configured on the reverse proxy is higher than the write time out configured for the Mercure hub.

**Comment by holema** [comment]
@dunglas 
Thanks for the fast reply.

The write_timeout on the nginx is set as described in your instruction to 24h and the mercure hub write_timeout is not set, so the default value should be the 600s

So I will now check the ha-proxy config of the reverse in front of the nginx.

**Comment by holema** [comment]
It was the timeout in the ha-proxy. 
There the client timeout for the specific frontend has to be set too.

Thanks for the idea where to search.
