### ISSUE TITLE
Unknown certificate authority (on Mac OS)

### ISSUE THREAD

**Issue by thomas2411** [dunglas/mercure#675]
Hello,

I try to run Mercure with Caddy for development purposes with Symfony on my local Mac OS.

I have downloaded **mercure_0.13.0_Darwin_x86_64.tar.gz** for Mac OS 12.4 (with Apple processor). I setup the Caddyfile.dev as follows. I have a MAMP Pro local Apache server for PHP, MySQL, Redis with a host https://devmk:8890 and self-signed certificate generated by MAMP Pro.

```
{
	{$GLOBAL_OPTIONS}
	admin off
	debug
}

{$SERVER_NAME:localhost}

log

route {
	redir / /.well-known/mercure/ui/
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Permissive configuration for the development environment
		cors_origins https://devmk:8890
		publish_origins *
		demo
		debug
		anonymous
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	respond /healthz 200

	respond "Not Found" 404
}
```
I run Mercure:
```
MERCURE_PUBLISHER_JWT_KEY='myjwtsecret' MERCURE_SUBSCRIBER_JWT_KEY='myjwtsecret' ./mercure run -config Caddyfile.dev
```
And when I try to subscribe or publish to a topic, I get CORS errors in the browser. And the Mercure shows this error:

```
http.stdlib	http: TLS handshake error from 127.0.0.1:61563: remote error: tls: unknown certificate authority
```

Any ideas how to handle it. It looks like Mac OS doesn't trust this CA. When I try to drag the certificate from Caddy  `/Users/myuser/Library/Application Support/Caddy/certificates/local/localhost` to a Key Chain, I get en error 27276 cannot import certificate

**Comment by dunglas** [comment]
You must accept the self-signed certificate issued by Caddy.

**Comment by thomas2411** [comment]
This is odd. I have updated to 0.14.beta-2, lcobucci/jwt (4.1.5 => 4.2.1), reenerated Secret key....and it works.
