### ISSUE TITLE
net::ERR_HTTP2_PROTOCOL_ERROR 200

### ISSUE THREAD

**Issue by thomask** [dunglas/mercure#676]
We keep seeing this error in devtools (Chrome 103 on macOS 12) on production. The error seems to appear every minute when a GET request is automatically made to Mercure. We don't see this issue in Dev, but neither do we see that automatic request every minute.

*Caddy config Prod*
```
mercure.{$DOMAIN}:80, :3000 {
	route /.well-known/mercure {
		encode zstd gzip

                 mercure {
			transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
			publisher_jwt {$MERCURE_JWT_SECRET} {$MERCURE_PUBLISHER_JWT_ALG}
			subscriber_jwt {$MERCURE_JWT_SECRET} {$MERCURE_SUBSCRIBER_JWT_ALG}

			cors_origins https://app.{$DOMAIN}
			auto_https off
		}

		respond /health 200

		respond "Not Found" 404
	}

	log
}
```

*Caddy config Dev*
```
mercure.{$DOMAIN}:443 {
	tls internal

	route /.well-known/mercure {
		encode zstd gzip

		mercure {
			transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
			publisher_jwt !ChangeMe! {$MERCURE_PUBLISHER_JWT_ALG}
			subscriber_jwt !ChangeMe! {$MERCURE_SUBSCRIBER_JWT_ALG}

			cors_origins https://app.{$DOMAIN}
			auto_https on
		}

		respond /health 200

		respond "Not Found" 404
	}

	log
}
```

*Dockerfile*
```
FROM caddy:2.5.1-builder AS builder

RUN xcaddy build \
      --with github.com/dunglas/mercure \
      --with github.com/dunglas/mercure/caddy

FROM caddy:2.5.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY ./Caddyfile.prod /etc/caddy/Caddyfile

EXPOSE 80

ENV MERCURE_TRANSPORT_URL=bolt:///data/mercure.db
```

*JS*
```
const eventSource = new EventSource(
    `https://mercure.${DOMAIN}/.well-known/mercure?topic=` +
        encodeURIComponent(
            `https://api.${DOMAIN}/videos/` + arg
        ),
    { withCredentials: true }
);
```

*Request headers*
```
:authority: mercure.******.com
:method: GET
:path: /.well-known/mercure?topic=https%3A%2F%2Fapi.******.com%2Fvideos%2Fvid_WFLp0jUo8kyAeZKcDNmv0GFa
:scheme: https
accept: text/event-stream
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,nl;q=0.8
cache-control: no-cache
cookie: mercureAuthorization=******;...
origin: https://app.******.com
pragma: no-cache
referer: https://app.******.com/
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

*Response headers*
```
access-control-allow-credentials: true
access-control-allow-origin: https://app.******.com
cache-control: private, no-cache, no-store, must-revalidate, max-age=0
content-security-policy: default-src 'self'
content-type: text/event-stream
date: Mon, 01 Aug 2022 13:31:18 GMT
expire: 0
pragma: no-cache
server: Caddy
x-accel-buffering: no
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

Caddy Runs inside a Docker Container on AWS ECS, behind an Application Load Balancer. The LB takes care of SSL termination.

We have tried going through the Mercure source, but haven't found anything interesting (apart from maybe [this](https://github.com/dunglas/mercure/blob/ec7044016b449a70e79acb3715fcd7498e8e9daf/config.go#L94) where the default write-timeout seems to be 60s instead of 600s, but from the comments I infer this file is not used when using the Caddy Server Module)

**Comment by dunglas** [comment]
This looks like a duplicate of https://github.com/dunglas/mercure/issues/373 and https://github.com/dunglas/mercure/issues/672.

This kind of error usually happens when a reverse proxy closes the connection before Mercure does. Try to set `write_timeout` to `50s` or something like that.

**Comment by itodor** [comment]
@dunglas sorry for re-activating closed issue, just wanted to ask you about your advice (updating `write_timeout` to be lower than GCP LB), I'm using helm chart https://artifacthub.io/packages/helm/mercure/mercure but this one doesn't seem to have this option included to modify. I'm using this one because the one on github which had `backendConfig` k8s object seems to be deprecated.

My question is, is there chance using this helm chart (that seems to be managed by you personally?) to update write_timeout value or I will have to manage custom install and not using helm for this problem?

Thanks in advance!
