### ISSUE TITLE
Make usage of Authorization header configurable

### ISSUE THREAD

**Issue by jkabat** [dunglas/mercure#678]
I want to use HUB on domains which are protected by BASIC auth by default. At the moment order of mercure authorization is to check HEADER, then QUERY then COOKIE. With this order my ES connection always fails with 401 even if JWT token cookie is valid. Using different domains for the HUB is not a solution... what do you suggest?

How to cope with basicauth + JWT token cookie at the same time?

**Comment by dunglas** [comment]
You could tweak the configuration of your proxy (or Mercure hub through Caddy configuration) to drop the header.
