### ISSUE TITLE
Deeplinks to documentation pages are broken (404)

### ISSUE THREAD

**Issue by bb** [dunglas/mercure#690]
## Example
opening https://mercure.rocks/docs/ecosystem/hotwire directly leads to a 404 error.

## Workaround

go to https://mercure.rocks/docs, in the menu click "ecosystem", then "Hotwire integration".

Observe that the URL in the address bar is exactly the one above which does not work. Doing a tab reload (cmd+r) also leads to 404.

## Expectation

Opening the deep link directly should work

## nice to have

Add the header+menu to the 404 page

**Comment by dunglas** [comment]
This is fixed now!
