### ISSUE TITLE
everybody can subscribe on all topics

### ISSUE THREAD

**Issue by LudovicGit** [dunglas/mercure#691]
Hello,

Maybe I missed something about topics but It seems there are not check on topic listening. Even if I don't have a topic in my subscribe list in JWT, I can listening another one.

Token used for the push :
![image002](https://user-images.githubusercontent.com/9384031/185967164-9404d6a7-8f33-407b-a782-e067853fe1d6.png)
(tried also with  https://mysite.com/users/{id} in publish array)

Token used for subscribe :
![image003](https://user-images.githubusercontent.com/9384031/185967262-8946a977-f1c2-40b2-8edf-4c5308127287.png)
 
Step 1 :
Subscribing on topic https://mysite.com/users/1 (even if JWT says we can listen on id: 619)

`curl -N https://mercure-server.com/.well-known/mercure?topic=https://mysite.com/users/1 --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJodHRwczpcL1wvbXlzaXRlLmNvbVwvdXNlcnNcLzYxOSJdLCJwYXlsb2FkIjp7InVzZXIiOiJ0b3RvIn19fQ.zMqSYv1Quud_blAZwmbOCQsb5QVGNPQ70f0TqIj_n6Y'`

Mercure Server ouput:
`http.handlers.mercure   New subscriber  {"subscriber": {"id": "urn:uuid:a39a411f-4e24-45a0-991b-3c32566cd58d", "last_event_id": "", "remote_addr": "10.143.30.42:35064", "topic_selectors": [https://mysite.com/users/619], "topics": [https://mysite.com/users/1]}}`
 

 
Step 2:
Pushing on topic: https://mysite.com/users/1'
`curl -d 'topic=https://mysite.com/users/1' -d 'data={"foo": "updated value"}' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.h_uDtKKh56JeAQf9jT_DSjf7uCoja2kbZqKa2-bAYrQ' -X POST https://mercure-server.com/.well-known/mercure`

Mercure Server ouput:
`http.handlers.mercure   Update published        {"update": {"id": "urn:uuid:dae50c4a-61bb-4670-9ffe-75bb4c5f362c", "type": "", "retry": 0, "topics": [https://mysite.com/users/1], "private": false}, "remote_addr": "10.143.30.42:35066"}`

`http.handlers.mercure   Update sent     {"subscriber": {"id": "urn:uuid:a39a411f-4e24-45a0-991b-3c32566cd58d", "last_event_id": "", "remote_addr": "10.143.30.42:35064", "topic_selectors": [https://mysite.com/users/619], "topics": [https://mysite.com/users/1]}, "update": {"id": "urn:uuid:dae50c4a-61bb-4670-9ffe-75bb4c5f362c", "type": "", "retry": 0, "topics": [https://mysite.com/users/1], "private": false}}`
 
Result on subscriber:
```
id: urn:uuid:49e9d23c-e853-4307-9f16-904e88f73bbb
data: {"foo": "updated value"}
```

Maybe I missed something but I don't understand why I can listen on a topic without rights

Thanks :)

**Comment by dunglas** [comment]
You can listen on any topic by default but only for public updates. Mark the update as private and only authorized users will receive it.

**Comment by LudovicGit** [comment]
Ah yes indeed, thanks ;)
