### ISSUE TITLE
401 Subscriber unauthorized, unable to parse JWT: unable to parse RSA public key: invalid key: Key must be a PEM encoded PKCS1 or PKCS8 key

### ISSUE THREAD

**Issue by ElrickAl** [dunglas/mercure#701]
Hi, @dunglas ! 
In my architecture I use AWS ECS for back and mercure (separate instances in the same private network + ALB). 
Everything works fine locally with this docker-compose config (put here mercure only): 
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "8070:80"
        networks:
            - internal
         
Mercure instance run with this Dockerfile (can contain some redundant information, I guess)
FROM dunglas/mercure:latest

ENV MERCURE_TRANSPORT_URL=local://local \
    MERCURE_PUBLISHER_JWT_ALG=RS256 \
    MERCURE_SUBSCRIBER_JWT_ALG=RS256

COPY Caddyfile /etc/caddy/Caddyfile

and here is my Caddyfile:
{
auto_https disable_redirects
}

{$SERVER_NAME}:80

log

route {
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
		cors_origins {$MERCURE_EXTRA_DIRECTIVES}
        publish_origins {$MERCURE_EXTRA_DIRECTIVES}
	}

	respond /healthz 200

	respond "Not Found" 404
}

All environment variables are provided, but have this error: 
      "msg": "Subscriber unauthorized",
      "error": "unable to parse JWT: unable to parse RSA public key: invalid key: Key must be a PEM encoded PKCS1 or PKCS8 key"
     and next log show no information in Authorization header :  "Authorization": []
     
I assumed that there was my publisher and subscriber keys issue (I generated them like this: https://mercure.rocks/docs/hub/config#:~:text=HA%20version)-,JWT%20Verification,-When%20using%20RSA and converted them in one line (instead multiple) for ECS to store them), but that doesn't help me :(

**Comment by janklan** [comment]
I've got the same issue with Elastic Beanstalk, so I wouln't say it's ECS-specific. 

You don't say in which context are you trying to use Mercure, but in my case I'm running a Symfony application.

The docs are pretty ambigous when it comes to RS256 - you're supposed to set the two separate public keys in Caddy (one for publisher, one for subscriber, see https://mercure.rocks/docs/hub/config#jwt-verification), and the *one* "secret key" in the Symfony application (https://symfony.com/doc/current/mercure.html#configuration)

So what's the "secret key"? Is is one of the public keys given to Caddy? Or is it meant to be a private key counterpart of one of them? Which one? My application is both publishing and subscribing.

Am I missing something on how the JWT signing works? 

Anyway, switching the algorithm to HS256 and using the same string value everywhere made the 401 error go away, but I would not call it a solution.

**Comment by dunglas** [comment]
Hi there, I'm pretty sure that the problem is related to mine endings. You need to keep them, removing them will likely break the PEM format.

According to https://github.com/aws/amazon-ecs-agent/issues/435, ECS does support multi-line environment variables, but you need to use the API or the CLI to set them.

**Comment by dunglas** [comment]
@janklan give access to the private key to your Symfony app (to generate the JWT), and to the corresponding public key to the Mercure hub (to verify the JWT).
