### ISSUE TITLE
Mercure stop hangs and doesn't clear port

### ISSUE THREAD

**Issue by pangus45** [dunglas/mercure#707]
Version 2.5.2 on Ubuntu 22.04 x86_64

Hub was running for a day on remote server for first time, started with `mercure start -config ~/Caddyfile.mine`. 

Changed a few things and wanted to restart today. Typed `mercure stop` and froze with no output.

Killing process leaves port open so I get the `bind: address already in use` error.

If this is not fixable, is there a way to free up the port after the kill other than reboot?
<br>

Also on local Ubuntu 22.04, I run mercure using `mercure run -config ~/Caddyfile.dev `

I use ctrl+c to stop and maybe 1 in 10 times, it leaves the port blocked.

**Comment by pangus45** [comment]
I see the port cleared itself after the kill in the time it took me to write this

**Comment by pangus45** [comment]
Ah ok so it will stop if there's no active subscriptions. In my case I close the connected webpage and then `mercure stop` works instantly.

Is this by design?

**Comment by frizquierdo** [comment]
> Ah ok so it will stop if there's no active subscriptions. In my case I close the connected webpage and then `mercure stop` works instantly.
> 
> Is this by design?

Are you using Supervisor for exec Mercure??
