### ISSUE TITLE
Running Mercure on a server that already serves sites over SSL

### ISSUE THREAD

**Issue by PavelPetrov-WebBambooLtd** [dunglas/mercure#71]
Hello,
I redesigned one of my systems to use mercure without realizing that, the binary will fail binding to port 443 because apache2 is already using it. Does any of you know for a workaround for that? Is my only option to spawn another server for that?

Thanks in advance and kudos for the great software, I'm really enjoying it so far.

**Comment by cklm** [comment]
There is no workaround for that - you cannot bind a single port to two applications. But there is no need to bind mercure to 443 - you can use any other port (like 3000 as suggested in the documentation).

**Comment by GregoireHebert** [comment]
If you really cannot change one of the two ports, you should set a reverse proxy to handle this situation.

**Comment by PavelPetrov-WebBambooLtd** [comment]
I based the question on the presumption that I can use the SSL certificate only on point 443 which I now understand is wrong :) I ended up  running it on a separate VPS but will definately try binding to a new port or using an nginx reverse proxy for my other instances.

Thanks for your help!
