### ISSUE TITLE
"message":"SSL certificate problem: certificate has expired for https://

### ISSUE THREAD

**Issue by souna23** [dunglas/mercure#711]
{"message":"Uncaught PHP Exception Symfony\\Component\\Mercure\\Exception\\RuntimeException: \"Failed to send an update.\" at /.../vendor/symfony/mercure/src/Hub.php line 104","context":{"exception":{"class":"Symfony\\Component\\Mercure\\Exception\\RuntimeException","message":"Failed to send an update.","code":0,"file":"/.../vendor/symfony/mercure/src/Hub.php:104","previous":{"class":"Symfony\\Component\\HttpClient\\Exception\\TransportException","message":"SSL certificate problem: certificate has expired for \"https://.../.well-known/mercure\".","code":0,"file":"/.../symfony/http-client/Chunk/ErrorChunk.php:56","previous":

**Comment by souna23** [comment]
i did not find a docs about how we renew the certificate

**Comment by dunglas** [comment]
Which version are you using? With the default settings the renewal should be automatic.

**Comment by souna23** [comment]
i am using the latest one 0.6.1 with the latest version of mercure hub 0.14.1

**Comment by dunglas** [comment]
Do you have any specific config regarding TLS certs? Could you copy your Caddyfile for instance?

**Comment by souna23** [comment]
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
	http_port    8889
	https_port   8888
	admin :2015
}

{$SERVER_NAME:mercure.mydomain.com}

log

route {
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
	        cors_origins https://mydomain.com https://www.mydomain.com
		publish_origins *
		anonymous
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	respond /healthz 200

	respond "Not Found" 404
}

**Comment by souna23** [comment]
i am getting these errors in debug mode 

tls.issuance.acme.acme_client	challenge failed	{"identifier": "mercure.mydomain.com", "challenge_type": "http-01", "problem": {"type": "urn:ietf:params:acme:error:unauthorized", "title": "", "detail": "xxx.xxx.xxx.xxx: Invalid response from http://mercure.mydomain.com/.well-known/acme-challenge/zq8rWx0N5H7UEB04UDCJ9l1Vr8ooNvRSOgpkWDXNCIQ: 404", "instance": "", "subproblems": []}}

tls.issuance.acme.acme_client	validating authorization	{"identifier": "mercure.mydomain.com", "problem": {"type": "urn:ietf:params:acme:error:unauthorized", "title": "", "detail": "xxx.xxx.xxx.xxx: Invalid response from http://mercure.mydomain.com/.well-known/acme-challenge/zq8rWx0N5H7UEB04UDCJ9l1Vr8ooNvRSOgpkWDXNCIQ: 404", "instance": "", "subproblems": []}, "order": "https://acme-v02.api.letsencrypt.org/acme/order/807126617/140647082427", "attempt": 1, "max_attempts": 3}

tls.issuance.acme.acme_client	challenge failed	{"identifier": "mercure.mydomain.com", "challenge_type": "tls-alpn-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "xxx.xxx.xxx.xxx: Error getting validation data", "instance": "", "subproblems": []}}

ERROR	tls.renew	could not get certificate from issuer	{"identifier": "mercure.mydomain.com", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - xxx.xxx.xxx.xxx: Error getting validation data"}

**Comment by dunglas** [comment]
It looks like you have a network problem, Let's Encrypt isn't able to validate `mercure.mydomain.com`. Is your domain publicly available on internet? This is necessary to use Let's Encrypt.

Anyway, this issue doesn't look related to Mercure but to your TLS config.

**Comment by souna23** [comment]
thank you, everything is okey now, the problem was on the port number
