### ISSUE TITLE
Mercure Hub stops working after hours or up to 10 days - Certbot?

### ISSUE THREAD

**Issue by pangus45** [dunglas/mercure#715]
Hub had been stopping after a few hours or a day so I set it to log. It then worked fine for 10 days straight so I thought the logging had randomly fixed it. 

I found it not working today with the eventsource request in the network tab of chrome dev tools showing "pending". 

`pidof mercure` shows the process is still running, as did a ""cleaning storage unit" message in log a few hours after the last publish.

Log shows normal assortment of "New subscriber", "Update sent", "Subscriber Disconnected" and "handled request" until 11:53am on 13th Nov then nothing after that. New updates were being published about once every 5 minutes at this point.

I looked through system logs and in syslog I found the closest event to be...

`Nov 13 12:00:01 my-mercure-hub CRON[46933]: (root) CMD (test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew)`

It's not out of the question that there was no updates from 11:53:30 until then so this is my primary (but probably innocent) suspect. It doesn't look like my certificate has been renewed. 59 days remaining and began at 90.

Running Version 2.5.2 on its own server on Ubuntu 22.04 x86_64 on Digital Ocean droplet. 1GB ram and graphs show it pretty steady at about 40%.

Rebooting server and restarting hub works fine until the next time - could be hours - could be 10 days.

Any suggestions greatly appreciated. 

I've commented out the certbot cronjob in /etc/cron.d/certbot just in case.

**Comment by pangus45** [comment]
I don't have nginx installed. Thought I'd add this as my Googling "certbot crashes server" has lead me there first.

**Comment by dunglas** [comment]
Hi,

Why do you use Certbot instead of Caddy's native Let's Encrypt support?

**Comment by pangus45** [comment]
If I remember right, when I first started the hub, it complained about no certificate, so I then used certbot to obtain one and it then worked. Been a while so I may not be remembering correctly. Will remove certbot and look into the native way.

Stopped again - after 21 days. About to look into the logs so may find something else this time.

**Comment by pangus45** [comment]
Failed again. 6.38am.

**Comment by dunglas** [comment]
Could you try to remove certbot and use the native TLS capacities of Caddy, so we can be sure that it's not a certbot-related issue?

**Comment by pangus45** [comment]
Will do. I'll spin up a fresh server (Digital Ocean droplet) from scratch just to be sure. Might be a few days before I get the time.

Is there a Linux distro other than Ubuntu that you think I might have more luck with? Perhaps one that's more tried and tested? Or one that's more stripped-down?

Or perhaps it's better to use the exact same Ubuntu droplet so we're keeping all other variables constant?

**Comment by dunglas** [comment]
As it's a Go static binary, any distribution should be ok.

**Comment by pangus45** [comment]
OK I'll stick with Ubuntu then and that keeps all variables but certbot constant. Also, if I can't get it working without certbot, then I guess that's another clue to what I'm doing wrong. Thanks again.

To be continued...
