### ISSUE TITLE
Failed to send an update.

### ISSUE THREAD

**Issue by Elfomen** [dunglas/mercure#716]
Hello, i am just starting with mercure and i launched my first mercure server and got some errors.

I have build an API and wan't to have real time notifications on my reactjs front end app.

Here is the mercure server launched

![server started](https://user-images.githubusercontent.com/75611134/202438827-80fbe7d7-7982-4f4b-a003-fb524a4c0423.png)

Then i created a JWT:

 
![jwt created](https://user-images.githubusercontent.com/75611134/202439163-e320ef3e-d2cd-4631-8ad6-7a7417aa645d.png)

My symfony .env file looks like: 

![env](https://user-images.githubusercontent.com/75611134/202439442-3f119c1a-4f79-4d32-a0e2-768a9baa9652.png)

So i first used postman to make a post request to http://localhost:3000/.well-known/mercure, and that worked perfectly, my front end application was updated successfully.

Now i want to Use the mercure attribute to hint API Platform that it must dispatch updates so that any time an object of my entity type is created, updated or deleted, the new version is sent to all connected clients through the Mercure hub

My entity looks like below: 

`#[ORM\Entity(repositoryClass: ConversationRepository::class)]
#[ApiResource(
    mercure:true ,
    security:'is_granted("ROLE_USER")' ,
    operations:[
        new Delete(
            openapiContext:[
                'security' => [[ 'bearerAuth' => [] ]] ,
            ]
        ) , 
        new Get(
            uriTemplat`

You can see that mercure is set to trrue, but when there is a post, put or delete request on my entity, i get the following errors
![error](https://user-images.githubusercontent.com/75611134/202441215-b848fe75-7383-4515-bf99-d36280ace9c8.png)

The mercure console gives me the following error

`{"level":"info","ts":1668685032.1344423,"caller":"mercure/publish.go:21","msg":"Topic selectors not matched, not provided or authorization error","remote_addr":"127.0.0.1:38880","error":"unable to parse JWT: signature is invalid"}
127.0.0.1 - - [17/Nov/2022:12:37:12 +0100] "POST /.well-known/mercure HTTP/1.1" 401 13 "" "Symfony HttpClient/Curl"`

I really don't know what i did wrong, meanwhile it works normally when i use post man to  perform a post request to mercure hub. 

I am stocked at this point for a while, i haven't seen something helpful on the internet yet

**Comment by langziyang** [comment]
i have simple demo for you 
[https://github.com/langziyang/symfony_mercure](url)

**Comment by dunglas** [comment]
Could you try to use the Caddy version instead of the legacy binary?

**Comment by mwansinck** [comment]
We experience the same issue with Mercure, using the dunglas docker images. By estimate, since version 0.14.

Mercure is responding to HTTP calls, 

```
GET /.well-known/mercure
>> Missing "topic" parameter.
```

Seems that the underlaying storage engine is non responsive.

Memory usage is around 848MiB, CPU load is 0.00, after restarting the docker container, the problem disappears and Mercure is responsive again. Memory usage is around 23 MiB after restart.

**Comment by skPink** [comment]
@Elfomen Do you have fix ?

**Comment by dunglas** [comment]
Could you try to run the hub in debug mode and generate a profile (https://mercure.rocks/docs/hub/debug) when the issue occurs, so we can see what's going on? Thanks!

**Comment by skPink** [comment]
@dunglas For me i use latest version of mercure with an old binary, i download the CaddyServer version with docker and work perfect
