### ISSUE TITLE
Deploy mercure bundle in test server

### ISSUE THREAD

**Issue by ManoloAMD** [dunglas/mercure#722]
Hi excelent work guys,

Sorry for my english, i need help in deploy config please, i don't khown if have a bug or error in my config nginx, in my log Developer Tools i see this error: 

**EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.**

I read many issues but I did not find a solution.

Symfony 5.4.9
Ionic Angular 6.20.3
symfony/mercure-bundle 0.3.5

**My template (nginx docker)**
server {
    listen 80 default_server;
    server_name _;
    return 301 https://my-domain.es;
}

server {
    listen 443 ssl default_server;
    server_name ${NGINX_DOMAIN_TEST};
    root /var/www/api-project/public;
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_certificate /etc/ssl/certs/my-cert.es.chained.crt;
    ssl_certificate_key /etc/ssl/private/my-key.es.key;

    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$args;
    }

    location /.well-known/mercure {
        proxy_pass http://mercure:3000/.well-known/mercure;
	chunked_transfer_encoding off;
	proxy_buffering off;
	proxy_cache off;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
   }

**My .ts (ionic angular)**
subscribeEventSource() {
    const url = new URL('https://my-domain.es/.well-known/mercure');

    url.searchParams.append(
      'topic',
      `https://${host}` + '/api/show/chat/' + this.user.rooms_id
    );
    const es = new EventSource(url, { withCredentials: true });

    es.onmessage = (event: any) => {
      let message = JSON.parse(event.data);
      const user = this.user.users_id;
     // Do something ...
    }
}

**My controller**
#[Route("/show/chat/{id}", name: "chat_show")]
  public function showChat(
    Request $request,
    Room $room,
    MessageRepository $messageRepository,
    SerializerInterface $serializer
  ): Response {
    $host = $this->toolsService->getHost();
    $messages = $messageRepository->findBy(
      [
        "room" => $room,
      ],
      ["created_at" => "ASC"]
    );

    $messages = $serializer->serialize($messages, "json", [
      "groups" => ["message"],
    ]);

    $userConnected = $this->user->getId();

    $subscribe = "https://" . $host . "/api/show/chat/" . $room->getId();
    $tokenJWT = $this->toolsService->getJWT($subscribe);

    $response = new JsonResponse(
      [
        "messages" => $messages,
      ],
      Response::HTTP_OK
    );

    $response->headers->setCookie(
      Cookie::create("mercureAuthorization")
        ->withValue($tokenJWT)
        ->withExpires()
        ->withPath("/")
        ->withDomain($host)
        ->withSecure(true)
        ->withHttpOnly(true)
        ->withSameSite(Cookie::SAMESITE_NONE)
    );

    $response->headers->set("Content-Type", "text/event-stream");
    $response->headers->set("Cache-Control", "no-cache");

    return $response;
  }

Run in device android - log DevTools :
![log](https://user-images.githubusercontent.com/32300356/206947093-8ae7e2fd-25ca-48a3-ad04-875462e2a234.png)

Config docker-compose mercure:
![docker-compose](https://user-images.githubusercontent.com/32300356/206947574-09ef3726-321e-4fb5-8123-5cbc2b583164.png)

Config docker-compose-override mercure:
![docker-override](https://user-images.githubusercontent.com/32300356/206947755-01e5313b-d91c-409f-8936-58874081dfad.png)

**Questions:**
Is there something you need to do to implement mercure-container on a server?
Why no documentation of deploy in prod only localhost?

Thanks :)

**Comment by dunglas** [comment]
Can you show the body of the response you get please? If you could provide a repo containing a minimal reproducer, this would help a lot!

**Comment by ManoloAMD** [comment]
Ok right now I have a lot of work, I will do it soon

**Comment by dunglas** [comment]
Basically, it looks like you don't hit the Mercure hub but an HTML page.
