### ISSUE TITLE
Dead link in documentation / Seeking for info

### ISSUE THREAD

**Issue by Nincha** [dunglas/mercure#726]
Hi! :)

On the [troubleshooting page](https://mercure.rocks/docs/hub/troubleshooting), the link is dead at this sentence:

`If you use the Symfony CLI and want to use an external hub, be sure to read [this issue](https://github.com/symfony/cli/issues/424).`

---

On the other hand, I'm trying to configure a Mercure Hub in relation to a Symfony 5.4 installation.

Here's my `Caddyfile.dev`:

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
	{$GLOBAL_OPTIONS}
}

{$SERVER_NAME:localhost}

log {
	format filter {
		wrap console
		fields {
			uri query {
				replace authorization REDACTED
			}
		}
	}
}

{$EXTRA_DIRECTIVES}

route {
	encode zstd gzip
  
	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Permissive configuration for the development environment
                cors_origins *
		publish_origins *
		demo
		anonymous
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	redir / /.well-known/mercure/ui/
	respond /healthz 200
	respond "Not Found" 404
}
```

I've served a small test route to test the hub with javascript : 

```
{% block body %}
    <h1>Test Mercure</h1>
    <button id="publish-button">Publish notification</button>
    <div id="notification-container"></div>

    <script>
      const sourceUrl = "{{ mercure('http://localhost:9090/.well-known/mercure/events')|escape('js') }}"
      const eventSource = new EventSource(sourceUrl, {withCredentials: false})
      console.log(eventSource);
      eventSource.onmessage = event => {
        // Will be called every time an update is published by the server
        console.log(JSON.parse(event.data))
      }

      const publishButton = document.getElementById('publish-button')
      publishButton.addEventListener('click', () => {
        fetch('http://localhost:9090/.well-known/mercure', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(
            {
                text: 'Test notification'
            }
          )
        })
        .then(response => console.log('Notification published!'))
        .catch(error => console.error('Error during process:', error))
      })
    </script>
{% endblock %}
```

Whenever I try to hit the button I get a CORS error: `Access to fetch at 'http://localhost:9090/.well-known/mercure' from origin 'https://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Am I missing something, maybe that was pointed out on the dead link from the documentation? It seems using `anonymous` mode + `cors_origins *` should prevent CORS errors and the need to use JWT validation?

Thanks in advance for any piece of help and cheers anyway!

**Comment by dunglas** [comment]
We need to update this page, this problem should be gone now that Symfony switched back to the official Docker image.

If you used Flex to generate the config, you should have something like this in your `docker-compose.yml` file: https://github.com/symfony/recipes/blob/main/symfony/mercure-bundle/0.3/manifest.json#L17

This should work out of the box, without needing a custom Caddyfile.

But yes, adding `cors_origins https://127.0.0.1:8000` should also fix your issue. the `anonymous` directive is only useful if you want to allow anonymous subscribers (otherwise they will need to be authenticated), it's not related to CORS.

Also, you don't use the same domain for your Symfony app (`127.0.0.1`) and your Mercure hub (`localhost`). Try to use the same domain everywhere (`localhost` is better to prevent some TLS issues).

**Comment by Nincha** [comment]
Thanks for your insights. :)

Glad to know the mentionned issue with Docker is gone.

Currently I am not using Docker, but the Symfony Dev Server, so I downloaded a Windows binary for Mercure and that's why I'm using Caddy configuration files along with `$env:MERCURE_PUBLISHER_JWT_KEY='XXXX'; $env:MERCURE_SUBSCRIBER_JWT_KEY='XXXX'; $env:SERVER_NAME=':9090'; $env:ALLOW_ANONYMOUS='1'; .\mercure.exe run -config Caddyfile.dev` to launch the Mercure server.

I currently have 3 urls in the project: 
* https://127.0.0.1:8080 -> Symfony 5.4 as an API
* https://localhost:8080 -> Quasar app (frontend with Vue) (above Symfony can be accessed via proxy on https://localhost:8080/api)
* https://localhost:3000 -> Mercure server

That said, considering your feedback I'm still a bit surprised because like you say, it should work with cors_origins specifying both Urls, but it still throws an error. I'll give a try on setting a common domain for Symfony and Mercure and give a heads up about that. ;)

I also saw in Symfony documentation "If you use the [Symfony Local Web Server](https://symfony.com/doc/5.4/setup/symfony_server.html), you must start it with the --no-tls option." ; I'm not sure if that means things can't work with TLS/Symfony dev server? If that's so, I'd definitely need to consider migrating to Docker since I need TLS for other reasons in local dev.

Thanks again and have a great day!

**Comment by dunglas** [comment]
So if you don't use Docker:

- set the URL of you Quasar app as value of in the `cors_origins`
- start the Mercure hub with TLS enabled and be sure to visit the homepage of the hub to validate the self-signed certificate generated by Caddy before running your JS code

This should work. If it's not the case, can you copy the error please?
