### ISSUE TITLE
Updates.db Steadily Growing

### ISSUE THREAD

**Issue by drychlik76** [dunglas/mercure#74]
Hello,
I have noticed that the updates.db file continues to grow in size after publishing messages.  I've had the server running for about a week and now the updates.db file is a little greater than 504 MB.  Am I to assume that if I set an expiration time on the JWT, the message will remove from the updates.db file?

Thank you in advance.

**Comment by dunglas** [comment]
Currently this file is never dropped/cleaned up (it stores the list of updates to allow retrieving old ones).
But indeed it we could provide an expiration mechanism for stored events to prevent this file to grow.

**Comment by drychlik76** [comment]
Thank you sir.  Great work on this by the way; this is really great and we are excited to see where mercure goes.  

This brings up another question.  As a subscriber, how would I craft a subscription to get the old event messages from the hub?

**Comment by balabis** [comment]
Hey @dunglas, is this expiration mechanism implemented in some way now? We are facing the same issue, when the file is constantly growing and have to manually empty it.

**Comment by maxgu** [comment]
I have some problem now - Mercure runs on small droplet - 25Gb and for a week it eat all disk space and broke.
How I can trunk DB? Or (best solution) clear old messages, for example - clear all, witch older 3 days?

**Comment by maxgu** [comment]
@balabis I found solution - https://mercure.rocks/docs/hub/config - Bolt Adapter section

**Comment by melroy89** [comment]
Sorry the documentation of Mercure is once again not clear enough. What is the unit of `size`?  `bolt:///var/run/mercure.db?size=100`

Eg. What does 100 means? 100 bytes? 100 kB? 100MB? 100GB?

**Comment by melroy89** [comment]
> 100 events.

Thanks! Maybe document this :)

**Comment by melroy89** [comment]
Ps. so now the mercure.db I got has a size of 3.8GB. So let's say I set a limit of a thousand (1000) events in my case, what size would this result into? Like 10MB? or .. It's a bit of a gut feeling you know what I mean, what I do know is that server owners don't want 5, 10, or 15GB mercure database files :).
