### ISSUE TITLE
mercure package fails API Platform build - caddy version mismatch

### ISSUE THREAD

**Issue by brettins** [dunglas/mercure#742]
Hi, I'm unable to build the newest version of API Platform. I did a github template repository, then
`docker compose pull --include-deps`
and
`docker compose up -d`
but it fails:
```
#33 5.941 go: downloading github.com/dunglas/mercure v0.14.4
#33 6.471 go: github.com/dunglas/mercure/caddy@upgrade (v0.14.4) requires github.com/caddyserver/caddy/v2@v2.6.2, not github.com/caddyserver/caddy/v2@v2.5.1
#33 6.473 2023/01/24 18:44:40 [FATAL] exit status 1
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c xcaddy build 	--with github.com/dunglas/mercure/caddy 	--with github.com/dunglas/vulcain/caddy]: exit code: 1
```

**Comment by dunglas** [comment]
Can you try to run `docker system prune -a` or to update manually all images (including the Caddy image) used by API Platform? Unfortunately, there is no way to force Docker to upgrade images used in `FROM` clauses except by clearing entirely the cache or updating them separately.

**Comment by brettins** [comment]
That worked, thank you. It's interesting that the required versions cannot be specified to override cache values, though. That seems like a big failing in the docker system.
