### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghoumatn** [dunglas/mercure#750]
Hi, I got this error "Segmentation fault" when I run this commande "./mercure run -config Caddyfile.dev"

OS / Distribution
Debian 10 - Plesk

**Comment by dunglas** [comment]
Could you please try to get a core dump so we can debug? https://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-on-a-segmentation-fault

Thanks

**Comment by ghoumatn** [comment]
After hours of searching how to enable kernel dumps on debian, I can't figure out how to core dump and debug the problem, always getting "Segmentation fault" without any informations. I tried this command :

`ulimit -c unlimited`

also I tried with gdb

The same configuration is working good on Ubuntu 18.04.6 with Vesta Cpanel

**Comment by dunglas** [comment]
And could you provide us a reproducer?

**Comment by ghoumatn** [comment]
Now I got this error when i re-install new version

Reproduce line:
1) Installing Mercure
`wget https://github.com/dunglas/mercure/releases/download/v0.14.4/mercure-legacy_0.14.4_Linux_x86_64.tar.gz && mkdir mercureplesk && tar -zxvf mercure-legacy_0.14.4_Linux_x86_64.tar.gz -C mercureplesk`

2) Copy file Caddyfile.dev from my old configuration to folder mercureplesk, the file have this config:
`{
    {$GLOBAL_OPTIONS}
    http_port 3000
    https_port 3000

}


localhost:3000

route {
	redir / /.well-known/mercure/ui/
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key
		publisher_jwt "Q9SATBUDWE"  {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt "Q9SATBUDWE" {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Permissive configuration for the development environment
		cors_origins *
		publish_origins *
		demo
		anonymous
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	respond /healthz 200

	respond "Not Found" 404
}
`


3) Run server:
` sudo ./mercure run -config Caddyfile.dev`


4) Error showing:
`
2023/02/14 10:04:03 /!\ This Mercure binary is deprecated, use the binary based on Caddy Server instead! See https://mercure.rocks/docs/UPGRADE
2023/02/14 10:04:03 invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined panic: invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined

goroutine 1 [running]:
log.Panic({0xc0000a3cd0?, 0x0?, 0x0?})
        /opt/hostedtoolcache/go/1.19.4/x64/src/log/log.go:388 +0x65
github.com/dunglas/mercure.NewHubFromViper(0xc0000f41a0)
        /home/runner/work/mercure/mercure/config.go:135 +0x6f
github.com/dunglas/mercure.Start()
        /home/runner/work/mercure/mercure/config.go:251 +0x35
github.com/dunglas/mercure/cmd.glob..func1(0x107ac00?, {0xb30a16?, 0x3?, 0x3?})
        /home/runner/work/mercure/mercure/cmd/root.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x107ac00, {0xc000034090, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x107ac00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/dunglas/mercure/cmd.Execute()
        /home/runner/work/mercure/mercure/cmd/root.go:29 +0x25
main.main()
        /home/runner/work/mercure/mercure/cmd/mercure/main.go:6 +0x17`

**Comment by ghoumatn** [comment]
Sorry for closing the issue, that's a mistake, the problem remains the same.  😅

**Comment by dunglas** [comment]
You use a Caddyfile with the binary that isn't using Caddy. Download the version that doesn't contain **legacy** in the filename.

**Comment by ghoumatn** [comment]
Now it worked with the following version: mercure_0.14.4_Linux_x86_64.tar.gz

I appreciate your help so much.
