### ISSUE TITLE
Authorization URI query parameter

### ISSUE THREAD

**Issue by netz0** [dunglas/mercure#753]
The documentation says that passing the authorization as a query parameter is supported:
https://mercure.rocks/spec#authorization

```
Three mechanisms are defined to present the JWS to the hub:

using an Authorization HTTP header

using a cookie

using an authorization URI query parameter
```

Every JS code I tested, and any other coding language, does not work and results in 401. Using CURL directly with authentication headers works. Is the documentation correct? I don't think authorization by URI is allowed unless it has to somehow be enabled manually in the hub or the documentation is incorrect, and it requires some specific format to work.

**Comment by dunglas** [comment]
Do you have an example of a URL that fails, please?
