### ISSUE TITLE
Build Caddy with Mercure

### ISSUE THREAD

**Issue by dkarlovi** [dunglas/mercure#766]
Currently I can use Mercure as a "special Caddy". Would it be possible to do the opposite: build Caddy with Mercure as a module?

This is useful if you want to have a Caddy instance which is has both some other modules and Mercure included, example

```
xcaddy build \
    --with github.com/caddyserver/cache-handler
```

Would just doing:

```
xcaddy build \
    --with github.com/caddyserver/cache-handler \
    --with github.com/dunglas/mercure
```

or similar work as expected?

**Comment by dunglas** [comment]
Yes! https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L15-L17
