### ISSUE TITLE
Getting a 401 Unauthorized

### ISSUE THREAD

**Issue by BowlOfSoup** [dunglas/mercure#77]
I'm trying to connect to the Mercure hub.
I have this code to subscribe (don't worry it's a test JWT):

```
var token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJhc2QiXX19.pdpWxTWkHqxT8v-hMJ6pl7dWD5PomhFWdx6yhQiUp0c";

document.cookie = "mercureAuthorization="+token+"; path=/hub; expires=Thu, 18 Dec 2020 12:00:00 UTC;";

const es = new EventSource('http://localhost:3000/hub?topic=' + encodeURIComponent('asd'), { withCredentials: true });
es.onmessage = e => {
    // Will be called every time an update is published by the server
    console.log(JSON.parse(e.data));
}
``` 

And it straight up **gives me a 401**.

This is my Mercure start command:
```
JWT_KEY='aVerySecretKey' ADDR='localhost:3000' CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000 ~/Applications/mercure
```

Im trying this on a Mac.

**Comment by BowlOfSoup** [comment]
Somehow i've changed `CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000` to `CORS_ALLOWED_ORIGINS=http://localhost:8000` and ran my test website also on `http://localhost:8000` and it seems to work. I'm a bit confused on why but i'm glad it works now.

**Comment by dunglas** [comment]
Hi,

It depends of the host you use inside the browser. Be sure that all hosts match, browser-side 127.0.0.1 and localhost are different hosts. So CORS can allow one, but not the other.

Closing for now, feel free to reopen if needed.
