### ISSUE TITLE
[QUESTION] Dockerfile ports

### ISSUE THREAD

**Issue by Guikingone** [dunglas/mercure#79]
Hi everyone, 

Small question about the ports used by the Dockerfile, it is possible to change the default `80 443` value to something like `8080 443`? 🤔 

I've tried to do it via env variables but it doesn't seem to work :/ 

Thanks again for the feedback and have a great day :)

**Comment by dunglas** [comment]
We should read the `PORT` environment variable if provided. It will fix the issue. PR welcome. This should probably be handled here: https://github.com/dunglas/mercure/blob/master/hub/server.go#L22
