### ISSUE TITLE
v0.15.1 mercure release requires v2.7.2 of caddy, breaking API Platform docker builds

### ISSUE THREAD

**Issue by BurningDog** [dunglas/mercure#798]
The [API Platform Dockerfile](https://github.com/api-platform/demo/blob/main/api/Dockerfile#L101C1-L103) uses 2.6.4 of Caddy:  

```
RUN xcaddy build v2.6.4 \
	--with github.com/dunglas/mercure/caddy \
	--with github.com/dunglas/vulcain/caddy
```

This results in building `caddy` with the latest version of `mercure` - v0.15.1 - but [this release](https://github.com/dunglas/mercure/releases/tag/v0.15.1) requires v2.7 of Caddy.

Docker container builds fail with the following:

```
6.092 2023/08/04 14:44:31 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go get -d -v github.com/dunglas/mercure/caddy github.com/caddyserver/caddy/v2@v2.6.4 
6.369 go: downloading github.com/dunglas/mercure v0.15.1
6.370 go: downloading github.com/dunglas/mercure/caddy v0.15.1
6.969 go: github.com/dunglas/mercure/caddy@upgrade (v0.15.1) requires github.com/caddyserver/caddy/v2@v2.7.2, not github.com/caddyserver/caddy/v2@v2.6.4
6.970 2023/08/04 14:44:32 [FATAL] exit status 1
```

Should the API Platform Dockerfile be pinned to use a specific version of `Mercure` for the `2.6.4` build?

**Comment by dunglas** [comment]
This has been fixed in recent API Platform versions: https://github.com/api-platform/api-platform/issues/2452#issuecomment-1664107467

To fix this issue, you can either switch to the new method to install Caddy (better), or change `v2.6.4` by `v2.7.2`.
