### ISSUE TITLE
Room support

### ISSUE THREAD

**Issue by mitalcoi** [dunglas/mercure#80]
Hi, Dunglas!
Mercure is great idea and project, but it really needs in rooms feature. 
For example, we have SaaS platform with isolated owners, and we want to to stream realtime updates only to specific owners, not to all users. In current implementation we can't achieve that behavior (or I missed something)
Do you have any plans or ideas regarding that functionality?

**Comment by GregoireHebert** [comment]
Hello @mitalcoi you can already do something approaching the behaviour of a room / lobby system.

2 ways to do so IMO. 
First one is from an API perspective. You handle the room creation from your API and you let your users subscribe to the mercure hub through this room.  For instance you would subscribe to the resource `/rooms/1`
and only users from this room will actually subscribe to this room and get the data.

Second one, is to imagine a low level API, separated from you system, dedicated to this feature.

So either way you can actually manage proper room/lobby system, keeping scalability in mind.

**Comment by tpharaoh** [comment]
I accomplished a teams based notifications with the help of a guy from upwork, our code is open source on https://github.com/tpharaoh/apiplatformtemplate

user belongs to team
team gets token
publish to token

On login the API returns Mercure token for the team and user subscribes to that

**Comment by dunglas** [comment]
For the record, this is now supported: https://mercure.rocks/spec#active-subscriptions
