### ISSUE TITLE
Mercure.db keep increasing like crazy

### ISSUE THREAD

**Issue by simon-fa** [dunglas/mercure#805]
I use caddy docker 2.7.3 with mercure and vulcain (from api platform)

`
FROM caddy:${CADDY_VERSION}-builder-alpine AS api_platform_caddy_builder

RUN xcaddy build \
    --with github.com/dunglas/mercure \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain \
    --with github.com/dunglas/vulcain/caddy

FROM caddy:${CADDY_VERSION} AS api_platform_caddy

WORKDIR /srv/api

COPY --from=api_platform_caddy_builder /usr/bin/caddy /usr/bin/caddy
COPY --from=api_platform_php /srv/api/public public/
COPY docker/caddy/Caddyfile /etc/caddy/Caddyfile
`

Since I updated to caddy 2.7.3,  I have a problem with mercure.db, that keep increasing...

![Capture d’écran du 2023-08-17 22-44-48](https://github.com/caddyserver/caddy-docker/assets/137528520/de7a5567-4a44-4d8e-ad97-a97d7bde9f73)

I also have this kind of errors in the logs :
`{"level":"info","ts":1692304021.0643678,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:54501f60-71a5-44a8-9b1e-1c46c8982860","last_event_id":"","remote_addr":"41.213.166.56:59410","topic_selectors":["users/102/chats","users/102/notifications","users/102/device-alive","users/102/device-connected","users/102/device-disconnected","users/102/business/46/notifications"],"topics":["users/102/business/46/notifications"]},"error":"**deadline exceeded**"}
`

**Comment by simon-fa** [comment]
Unable to flush and deadline exeeded everywhere
`{"level":"info","ts":1692305144.9292586,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:8ce659f1-3549-40af-8811-0509bd7113db","last_event_id":"","remote_addr":"83.112.237.64:56703","topic_selectors":["users/677/chats","users/677/notifications","users/677/device-alive","users/677/device-connected","users/677/device-disconnected","users/677/business/202/notifications"],"topics":["users/677/notifications"]},"error":"**deadline exceeded**"}
{"level":"info","ts":1692305155.261554,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:79c190dc-53d5-43c2-b774-16b8a827527c","last_event_id":"","remote_addr":"89.157.64.11:61529","topic_selectors":["users/777/chats","users/777/notifications","users/777/device-alive","users/777/device-connected","users/777/device-disconnected","users/777/business/203/notifications"],"topics":["users/777/business/203/notifications"]},"error":"**deadline exceeded**"}
{"level":"info","ts":1692305170.522563,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:f7efeab9-ada8-4673-a2df-709bd5318a8e","last_event_id":"","remote_addr":"82.64.221.11:65104","topic_selectors":["users/60/chats","users/60/notifications","users/60/device-alive","users/60/device-connected","users/60/device-disconnected","users/60/business/16/notifications"],"topics":["users/60/business/16/notifications"]},"error":"**deadline exceeded**"}
{"level":"info","ts":1692305186.1313157,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:2261a2f7-7be7-496c-ad6e-a79a38278cb3","last_event_id":"","remote_addr":"41.213.166.56:59410","topic_selectors":["businesses/46/appointments"],"topics":["businesses/46/appointments"]},"error":"**deadline exceeded**"}
{"level":"info","ts":1692305207.786153,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:b8a45409-156f-44cc-8a8e-162f7e5437a5","last_event_id":"","remote_addr":"176.169.102.207:51851","topic_selectors":["users/236/chats","users/236/notifications","users/236/device-alive","users/236/device-connected","users/236/device-disconnected","users/236/business/110/notifications"],"topics":["users/236/business/110/notifications"]},"error":"**deadline exceeded**"}
{"level":"info","ts":1692305224.9158037,"logger":"http.handlers.mercure","msg":"Unable to flush","subscriber":{"id":"urn:uuid:ff85391f-7ce6-4a35-914d-b7df98a251ad","last_event_id":"","remote_addr":"41.213.166.56:59410","topic_selectors":["users/102/chats","users/102/notifications","users/102/device-alive","users/102/device-connected","users/102/device-disconnected","users/102/business/46/notifications"],"topics":["users/102/business/46/notifications"]},"error":"**deadline exceeded**"}
`

**Comment by simon-fa** [comment]
Ok, it was a problem with our app, my bad.

**Comment by dunglas** [comment]
Closing then 😅. Out of curiosity, could you explain what happened, this may help other people having the same issue.

**Comment by maarekj** [comment]
I seem to have the same problem.
I don't see what could be triggered on my app.

Any idea?

@simon-fa
