### ISSUE TITLE
feat: Add a health check endpoint

### ISSUE THREAD

**Issue by Xusifob** [dunglas/mercure#808]
Hello everyone; 

I am currently using a mercure server on AWS and would like to add a health check so that if the server does not reply it can be shut down and rebuilt automatically.

I can not use the `/.well-known/mercure` endpoint as I am using authentification to access the topics.

Would it be possible to access a `/.well-known/health_check` that returns a HTTP 200 with some information about the server's health.

**Comment by cvergne** [comment]
👋 I think it's missing in the documentation, but there is already an healthcheck endpoint on `/healthz` which returns an empty HTTP 200.

**Comment by Xusifob** [comment]
Thanks for the reply 

Is there a repository with documentation so I can update it ? I did not find any

**Comment by dunglas** [comment]
The documentation is in this repo: https://github.com/dunglas/mercure/tree/main/docs

**Comment by maxhelias** [comment]
PR is open #891
