### ISSUE TITLE
Routes for API Platform and Mercure

### ISSUE THREAD

**Issue by beLogiC** [dunglas/mercure#81]
Hello,
i got mercure to work with my api platform.
Its all fine but I cant subscribe to the routes, because i dont know them.

I have the following entity: "Customer"

If i create/change or delete something it publishes the changes like it should.

I tried the following routes:
localhost:3000/api/customers
localhost:3000/api/customers.jsonId

also i tried:
localhost:3000/api/customers/1
localhost:3000/api/customers/1.jsonId

and some useless links that I tried because i was frustrated.

What would be the URL to subscribe?

sorry for my bad english 💃

**Comment by soyuka** [comment]
```localhost:3000/api//customers/{id}```

You can test it via https://uri-template-tester.mercure.rocks/

**Comment by beLogiC** [comment]
I typed my Symfony Api Platform URL into the top field: "http://localhost:3000/api/customers"

localhost:3000/api/customers
localhost:3000/api/customers/{id}
does not match

In the bottom field I need to paste what? 
What do i need to put into {id} if i dont know the Id because I need to create the customer first?

Actually I wanted to know how do I find out the Routes for Mercure out of my API Platform routes.

I dont need just a solution 😀 i want to understand it.

**Comment by soyuka** [comment]
the topics you want to subscribe too are given by the `Link` header when you create a resource, just check that out :). 
https://github.com/api-platform/core/blob/master/src/Mercure/EventListener/AddLinkHeaderListener.php
https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php

is where api platform logic happens regarding mercure

**Comment by beLogiC** [comment]
I got:
<http://localhost:8000/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation",<http://localhost:3000/hub>; rel="mercure"

I tried to subscribe to "http://localhost:8000/api/docs.jsonld" but it didnt work
> http://www.w3.org/ns/hydra/core#apiDocumentation 

Is clearly not the thing ( for what is that link? is it a type of docu or something?)

Sorry if i am too stupid, but i am actually completely new in that 😀

**Comment by beLogiC** [comment]
ok, its working... i debugged the package and i got my url:

If you have a URL from your API Platform: http://localhost:8000/api/customers
You just put: 
> http://localhost:8000/api/customers/{id}

as Hub Subscription. ( {id} as wildcard not as placeholder )

I think I am just too stupid and my english is bad but I hope if someone else is same then me, then he dont need 10 years to figure it out :)
ty everonye
