### ISSUE TITLE
feat: Support JWKS for JWT validation

### ISSUE THREAD

**Issue by broncha** [dunglas/mercure#812]
Hi all,

I am working on adding support for JWKS in Mercure. With this update, you would simply configure the JWKS URL and Mercure would validate the subscriber and publisher JWT based on the Key ID and the keys in the JWKS.

I have everything working (tested the binary with other apps publishing and subscribing). However, I am struggling with timeout on one of the tests. Can anyone have a look at it and point out my mistake with the test?

Here is the commit that adds JWKS support to Mercure https://github.com/broncha/mercure/commit/f6d90156a246ad7f64e6af889e442767db999dff

And the test that is timing out is `TestSubscribePrivateWithJWKS` in `subscribe_test.go`

**Comment by dunglas** [comment]
Hi @broncha. Nice feature! Don't hesitate to open a PR, I'll try helping to have the tests green.

**Comment by broncha** [comment]
@dunglas Opened a draft PR here https://github.com/dunglas/mercure/pull/813
