### ISSUE TITLE
JWT RS256 support for better integration with ApiPlatform and security

### ISSUE THREAD

**Issue by dvc** [dunglas/mercure#82]
Hello everybody!

Shared jwt-secret or static tokens is not so protected as public key on Mercure side. IMHO :)

see also: https://github.com/api-platform/api-platform/issues/1123

**Comment by dunglas** [comment]
Indeed, it would be nice to have support for other algorithms. PR welcome!

**Comment by Spomky** [comment]
>  is not so protected as public key

There is no reason to say that unless you use a hashing function like MD5 or SHA-1.
The advantages with symmetric key algorithms is that they are fast.

Anyway I concur with @dunglas and other algorithms should be supported

**Comment by dunglas** [comment]
See #156
