### ISSUE TITLE
Why can i subscribe to topics which are not specified in the JWT token ? 

### ISSUE THREAD

**Issue by celian-hamon** [dunglas/mercure#832]
My jwt token :
`"mercure": {
    "subscribe": [
      "0af424b62966a12576214346f"
    ]
  },`

i can subscribe and get any update from any endpoint not just this one. How to restrict access ?

**Comment by dunglas** [comment]
Mark the update as `private` to restrict who can subscribe to them.

**Comment by celian-hamon** [comment]
oh ! thank you had'nt read properly the documentation
