### ISSUE TITLE
use Mercure on AWS

### ISSUE THREAD

**Issue by sidikhalifa** [dunglas/mercure#84]
Hello,

When I put in production `Mercure` on `AWS` and launch it with the command:
> JWT_KEY='myJWTKey' ADDR='3000' ACME_HOSTS='my_website.com' ./mercure

And i go to `https://my_website.com:3000/hub` this page runs to infinity!

someone have idea?

Thanks
Sidi

**Comment by dunglas** [comment]
IIRC, Let's Encrypt only supports the 80 and 443 ports. Try removing the `ADDR=3000` part.

**Comment by sidikhalifa** [comment]
thanks for your response, i try, but is not work maybe because on AWS use security VPC!
