### ISSUE TITLE
Switch from golang-jwt/jwt to go-jose/go-jose

### ISSUE THREAD

**Issue by dunglas** [dunglas/mercure#851]
https://github.com/go-jose/go-jose has the benefit of natively supporting JWK (#470, #813) and of being already a dependency of Caddy (so we don't bloat the final binary).

WDYT @broncha?

**Comment by broncha** [comment]
@dunglas looks like `go-jose` only support jwks as string (I may be wrong, I just had a quick look). So we would need to handle the fetching and caching the keys from the provided URL.

**Comment by broncha** [comment]
Hi @dunglas I might be able to give this time in coming weeks. Been super busy!

**Comment by dunglas** [comment]
@broncha it looks like `go-jose` isn't gaining traction while `go-jwt` is actively maintained and JWK/JWKS support can easily be added with the `keyfunc` function. Let's stay with `go-jwt`!

I did the upgrade to go-jwt v5 in #262.
