### ISSUE TITLE
Strugling to format http.log.access.log0 logs to full json

### ISSUE THREAD

**Issue by vmignot** [dunglas/mercure#859]
Hello,

I'm using mercure on Kubernetes, using the 0.14.10 version of the chart.

Mercure works fine, but the logs are not fully json, eg:
`2024/01/19 14:53:08.892    INFO    http.log.access.log0    handled request    {"request": {"remote_ip": "100.64.123.21", "remote_port": "43368", "proto": "HTTP/1.1", "method": "GET", "host": "mercure.transverse", "uri": "/healthz", "headers": {"User-Agent": ["got (https://github.com/sindresorhus/got)"], "Accept": ["application/json"], "Authorization": [], "X-Correlation-Id": [""], "X-Source": ["appel-medical"], "Accept-Encoding": ["gzip, deflate, br"], "Connection": ["close"]}}, "user_id": "", "duration": 0.000019388, "size": 0, "status": 200, "resp_headers": {"Server": ["Caddy"], "Content-Type": []}}  `

I've tried to override the logs format using the following values: 
```
  globalOptions: |
    log default {
      include http.handlers.mercure http.log.access.log0
      output stdout
      format json
      level INFO
    }
```
But this results in an error: 
`Error: loading initial config: loading new config: setting up default log: include and exclude must not intersect, but found http.log.access.log0 in both lists`

Is there another solution I have not think of? 

Thanks!

**Comment by dunglas** [comment]
This will probably be fixed by https://github.com/caddyserver/caddy/pull/5980.

In the meantime, you'll probably have to tweak the Caddyfile to wrap the JSON logger instead of "console".

**Comment by vmignot** [comment]
Ok thanks, I've tried a lot to tweak the Caddyfile, but without success. I'll wait for the new release in that case :-)

Regards
