### ISSUE TITLE
The IETF draft should not mention "this repository"

### ISSUE THREAD

**Issue by stof** [dunglas/mercure#87]
>    *  Hub: A server that handles subscription requests and distributes
>      the content to subscribers when the corresponding topics have been
>      updated (a hub implementation is provided in this repository).
>      Any hub MAY implement its own policies on who can use it.

Saying `in this repository` in the IETF draft does not make sense, as https://datatracker.ietf.org/doc/draft-dunglas-mercure/ is not displayed in the context of a repository.

**Comment by dunglas** [comment]
Good catch! Thanks Christophe I’ll update the draft.
