### ISSUE TITLE
OTEL traces / metrics support

### ISSUE THREAD

**Issue by dkarlovi** [dunglas/mercure#901]
Please consider adding support for producing OTEL traces / metrics. It would allow integrating Mercure into streamlined observability deployments without much fuss.

**Comment by dunglas** [comment]
Mercure already adds metrics metrics to the OpenMetrics and Prometheus endpoint provided by Caddy: https://caddyserver.com/docs/metrics

Isn't it enough?

**Comment by dkarlovi** [comment]
It should be enough, I've tried that, but probably missed something.
