### ISSUE TITLE
Intermediate certificate

### ISSUE THREAD

**Issue by BenjaminTappnad** [dunglas/mercure#91]
Hi,

On my production environment I have an intermediate certificate. So in total I have 3 files:

- the certificate of my domain
- the private key
- the intermediate certificate

In the configuration I can only set the first 2, but not the last one. So I get this kind of error when I try to publish something to Mercure:

`http: TLS handshake error from 217.70.191.82:45486: remote error: tls: unknown certificate authority`

Could you please help me?

**Comment by dunglas** [comment]
The cert file contains PEM encoded data. PEM allows to store several certificates (including intermediate ones) in a single file. You can combine both certificates using this command:

    cat first_cert.pem second_cert.pem > combined_cert.pem

Be careful, the order matters!
