### ISSUE TITLE
max client connections

### ISSUE THREAD

**Issue by progmancod** [dunglas/mercure#93]
how many simultaneous client connections can the hub support?

**Comment by Ilshidur** [comment]
Hello.

You should find an answer in these tweets :

* https://twitter.com/dunglas/status/1115859943616319488

> 🚀⚡️ The http://Mercure.rocks  hub (open source version) is able to handle ~40k simultaneous persistent connections on a single @awscloud EC2 t3.micro instance!
A big thanks to @Glory4GamersFR and @Hartistik for providing this load test!

* https://twitter.com/dunglas/status/1055872758679326720 (in french)

> Merci ! La version open source est stateful, donc elle gère au max 65534 connection simultanées par hub. En pratique beaucoup moins (ça dépend de la puissance de la machine). 1/2

*my poor translation :*

> Thanks ! The open source version is stateful, thus it handles a maximum of 65534 simultaneous HTTP connections. In a real use case, a little less (depending on the machine's hardware).
