### ISSUE TITLE
[Question] pattern matching

### ISSUE THREAD

**Issue by LeJeanbono** [dunglas/mercure#95]
When we subscribe with pattern matching like :
`const url = new URL('https://example.com/hub');
url.searchParams.append('topic','https://example.com/books/{id}');`
Can we have a way to get somewhere the corresponding value of `{id}` ?

If I push on `https://example.com/books/56`
I want to get `id => 56`
Thanks :)

**Comment by dunglas** [comment]
you can do it client-side using a lib such as https://github.com/geraintluff/uri-templates#guess-variables-from-uri-de-substitution

**Comment by LeJeanbono** [comment]
Ok, so I need to pass context in data body.
Thanks
