### ISSUE TITLE
Error ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by LeJeanbono** [dunglas/mercure#96]
Hi !
Firstly, thanks for your tool :)
I'm facing actually an error in console : `net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`
The stream close to open a new one.
I read something about header `Transfer-Encoding: chunked`  https://stackoverflow.com/questions/13590755/eventsource-disconnects-after-first-message
Any Idea ?

**Comment by dunglas** [comment]
A proxy server or any a similar network equipment probably kills IDLE connections.
You can change the settings of your reverse proxy (example for NGINX: https://github.com/dunglas/mercure#how-to-use-nginx-as-an-http2-reverse-proxy-in-front-of-the-hub), or use `HEARTBEAT_INTERVAL` configuration option to prevent the connection to be marked as IDLE by the proxy.

**Comment by hepisec** [comment]
The link to the documentation has changed: https://mercure.rocks/docs/hub/cookbooks#using-nginx-as-an-http-2-reverse-proxy-in-front-of-the-hub

**Comment by Glideh** [comment]
Had that error with **pfSense's HAProxy**. Mercure's default `HEARTBEAT_INTERVAL` seems to be 40s.
In pfSense HAProxy, I've set the corresponding **backend** > **Timeout / retry settings** > **Server timeout** to 60000ms (default 30000ms)
It seems to do the trick
