### ISSUE TITLE
FATA[0000] invalid argument

### ISSUE THREAD

**Issue by crowincage** [dunglas/mercure#97]
Hi,

I'm trying to start mercure inside a virtualbox running Centos 7.
Using the example from Readme:

`JWT_KEY='myJWTKey' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure`

results in 
`FATA[0000] invalid argument`

I'm using the latest release of mercure 0.5.0 from the release page.

Is there some kind of verbose mode or any log files?
Are there any requirements that needs to be additionally installed on the machine?

Any hints on this would be appreciated.

thanx!

**Comment by dunglas** [comment]
`CORS_ALLOWED_ORIGINS=*`, you should probably escape `*` because it's a special char in shells.

**Comment by crowincage** [comment]
nope - doesn't work :-/ always the same

`JWT_KEY='myJWTKey' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS='10.0.2.15' PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure`
`FATA[0000] invalid argument`

Also tried to set an IP address for CORS_ALLOWED_ORIGINS - still the same. Also on previous version 0.4.2.

Last I've also tried something like:

`JWT_KEY='myJWTKey' ./mercure` - also gives the same invalid argument.

**Comment by dunglas** [comment]
Weird. I never got this error message. Are you using Docker?

**Comment by dunglas** [comment]
According to Google, it looks like a permission/FS issue.

**Comment by crowincage** [comment]
Yeah I have no idea why this isn't working.
I've just tried the same on our staging machine - also Centos 7 - there I can start mercure as mentioned in the Readme. Also if I start it directly on my Mac (of course Darwin release) - also everything works fine. So I guess it could be an issue on VirtualBox.

No - not using docker yet, maybe I'll give it a try.

**Comment by crowincage** [comment]
So if anyone has the same problem sometime - I've changed the Vagrant synced_folder to type "nfs"

from 
`config.vm.synced_folder "./", "/var/myproject"`
to 
`config.vm.synced_folder "./", "/var/myproject", type: "nfs"`

and now I can start mercure as mentioned in the Readme!

thank's!

**Comment by keganv** [comment]
@crowincage I am using a Vagrant machine with centos 7 as well. I am using an Angular frontend and using Symfony on the Vagrant machine. I can get the mercure hub started but I am getting failed responses on my frontend with the MERCURE_PUBLISH_URL set to `http://localhost:3000/hub`. Do you have an example of what you used to get the streaming to work from your host machine? Thank you!

**Comment by crowincage** [comment]
We're using nginx as a proxy in front of mercure as mentioned here:
https://github.com/dunglas/mercure#how-to-use-nginx-as-an-http2-reverse-proxy-in-front-of-the-hub
Which MERCURE_PUBLISH_URL do you mean? Can't see this option anywhere. Or do you mean PUBLISH_ALLOWED_ORIGINS?

**Comment by dunglas** [comment]
Where did you see `MERCURE_PUBLISH_URL`? Indeed this option doesn't exist.

**Comment by keganv** [comment]
The `MERCURE_PUBLISH_URL` is part of the Symfony bundle configuration.

**Comment by keganv** [comment]
Also, I got it working on a CentOS 7 Vagrant environment by using `ADDR='0.0.0.0:3000` in the terminal command.

**Comment by gallyamow** [comment]
I got this error when run mercure over systemctl and fixed it by adding `WorkingDirectory=/tmp`  in unit file.
