### ISSUE TITLE
How to detect if user abort conncetion?

### ISSUE THREAD

**Issue by VereschakSun** [dunglas/mercure#977]
Hello.  I try to find a solution for detection if the user closes the browser and the client has lost the SE connection.  Do you have a configuration for webhooks for this? 
For example. I will add my endpoint for lost connection to mercure config. If the user  disconnects, will I receive a post request to my backend with information about the user

**Comment by soyuka** [comment]
Once the browser is closed you can't do anything. The only solution is to have a ping system and to check if no `ping` as been sent in a while, then you can assume user left.

**Comment by VereschakSun** [comment]
Thank you!

**Comment by abda11ah** [comment]
If you subscribe to the presence endpoint topic ./well-know/mercure/subscriptions/{topic}/{subscriber}, 
then this subscription will return active:false when the other user closes his browser.
