### ISSUE TITLE
Cannot sub to mercure through https with EventSource

### ISSUE THREAD

**Issue by thomasmoreaumaster** [dunglas/mercure#98]
Hi Mercure Team,

I push this issue even if i know it has small chance to be a real issue, sorry about that. But if you can give me a clue i will be happy.

My problem is that i can subscribe to my mercure server through HTTPS using cURL and i can see updates.

But when i use eventSource it doesn't work, the eventSource stay in readyState 0, connecting...

Is there any chance you might guess the reason ?

Anyway thanks a lot for your time,
Thomas.

**Comment by dunglas** [comment]
Did you checked CORS settings? Do you have anything in the console that can help? Otherwise you'll have to use a tool like Wireshark to debug at a lower level.

**Comment by thomasmoreaumaster** [comment]
Yes i put a variable to my compute engine CORS_ALLOWED_ORIGINS=* so i can test my developments locally.

/docker# vim docker-compose.yml
var env : 
- JWT_KEY=aNewGreatToken 
- DEMO=1 
- ALLOW_ANONYMOUS=1 
- PUBLISH_ALLOWED_ORIGINS='*'
- CORS_ALLOWED_ORIGINS='*'

I got nothing in my console, neither in my network tool.

i just can console.log the eventSource

`EventSource {url: "https://mercure.decathlon.com/hub?topic=http://127.0.0.1/api/v1/stores/350/messages", withCredentials: false, readyState: 0, onopen: null, onmessage: null, …}
onerror: null
onmessage: ƒ (e)
onopen: null
readyState: 0
url: "https://mercure.decathlon.com/hub?topic=http://127.0.0.1/api/v1/stores/350/messages"
withCredentials: false
__proto__: EventSource`

And if i run my mercure server locally everything works fine.

Ok Let's do it with WireShark lol :)

Thanks a lot for your time :)
Thomas.

**Comment by thomasmoreaumaster** [comment]
Hi @dunglas,

I used wireshark to try to understand why i can subscribe with cURL and not with my Angular eventSource.

I look for differences between 2 wireshark records and i found one difference : 
cURL is using http-over-tls protocol on SSL part while 
Angular eventSource is using http2.

Do you think it might be the cause ? do you suggest me to look somewhere else ? But where  :) ?

Thanks for your time,
Thomas.

![Screenshot from 2019-06-09 12-49-23](https://user-images.githubusercontent.com/9032878/59158088-6897c000-8ab5-11e9-9990-06cc4e7e1050.png)
![Screenshot from 2019-06-09 12-49-02](https://user-images.githubusercontent.com/9032878/59158092-71889180-8ab5-11e9-8535-fdab4faa7597.png)

**Comment by thomasmoreaumaster** [comment]
hi @dunglas,

Problem solved i use nginx with http1 & 2 and now the problem is solved.

Thanks again for your time,
Thomas.
