### ISSUE TITLE
Error: loading initial config: loading new config: 

### ISSUE THREAD

**Issue by ma-gu-16** [dunglas/mercure#985]
Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 1: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: "": invalid transport: timeout

after a day if i start the server again i got the above log. and its not possible to start the server. 
when i delete the mercure.db it starts as usually.  how can i prevent this  ? 

my config:

`#
{
	{$GLOBAL_OPTIONS}
	debug
    admin off
	email xxx
}

{$CADDY_EXTRA_CONFIG}

https://xxx.com {
	log {
		format filter {
			fields {
				request>uri query {
					replace authorization REDACTED
				}
			}
		}
	}

	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
		# Publisher JWT key secret
		publisher_jwt xxx
		# Subscriber JWT key secret
		subscriber_jwt xxxx

        subscriptions

		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	{$CADDY_SERVER_EXTRA_DIRECTIVES}

	redir / /.well-known/mercure/ui/

	respond /healthz 200
	respond /robots.txt `User-agent: * Disallow: /`
	respond "Not Found" 404
}
`

**Comment by dunglas** [comment]
May it be related to https://github.com/dunglas/mercure/issues/898#issuecomment-2115381506?

It looks like there are issues with BoltDB and locking.

**Comment by ma-gu-16** [comment]
I fixes it. I had multiple mercure processes running. This made couple of problems. Looks Like Its fixed.
