### ISSUE TITLE
Golang client

### ISSUE THREAD

**Issue by ghost** [dunglas/mercure#99]
Is there a golang client ?

Want to use this for IOT and also non web GUI like flutter.

The system with hateos looks like a genius solution to a tough long standing problem. Congrats !!

**Comment by dunglas** [comment]
https://github.com/donovanhide/eventsource should do the trick (I never tested it).
https://github.com/r3labs/sse also provides a client.

**Comment by gedw99** [comment]
Thanks for those. Will dig into them.

Once happy with client, should we add it as a CMD to allow people to have a base reference point for client / server interaction ? Could add a real golang based example for Todo reference app later. I am working on this in golang

**Comment by dunglas** [comment]
Yes, we should add a GoLang client example in https://github.com/dunglas/mercure/tree/master/examples
